In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
# models generation directory: LLM4DC/CoT.response
# predicted dataset by model:  LLM4DC/CoT.response/{model}/datasets_llm
# predicted workflow by model:  LLM4DC/CoT.response/{model}/recipes_llm
# predicted operations by model:  LLM4DC/CoT.response/{model}/operation
# logging:  LLM4DC/CoT.response/logging

# all the sample tables are under: LLM4DC/datasets
# query: 1-30 [menu]: LLM4DC/datasets/menu_datasets
# clean table (ground truth) LLM4DC/datasets/menu_datasets/clean_tables/
# clean workflow (silver ground truth):  LLM4DC/datasets/menu_datasets/workflows

# query: 31-61 [chicago]: LLM4DC/datasets/CFI_datasets
# clean table (ground truth): LLM4DC/datasets/CFI_datasets/cleaned_tables/
# clean workflow (silver ground truth):  LLM4DC/datasets/CFI_datasets/workflows

# query: 62-91 [ppp]:LLM4DC/datasets/ppp_datasets
# clean table (ground truth): LLM4DC/datasets/ppp_datasets/cleaned_tables/
# clean workflow (silver ground truth):  LLM4DC/datasets/ppp_datasets/workflows

# query: 92-110 [dish]: LLM4DC/datasets/dish_datasets
# clean table (ground truth): LLM4DC/datasets/dish_datasets/cleaned_tables/
# clean workflow (silver ground truth):  LLM4DC/datasets/dish_datasets/workflows

# query: 111-126 [flights]: LLM4DC/datasets/flights
# clean table (ground truth): LLM4DC/datasets/flights/cleaned_tables/flights_data_p{query_id}.csv
# clean workflow (silver ground truth):  LLM4DC/datasets/flights/workflows/flights_p{query_id}.json

# query: 127- 154 [hospital]: LLM4DC/datasets/hospital
# clean table (ground truth): LLM4DC/datasets/hospital/clean_tables/
# clean workflow (silver ground truth):  LLM4DC/datasets/hospital/workflows

In [2]:
import re

In [3]:
import json

In [4]:
import ast
# LLM-based history update solution
import importlib.util
import inspect
from typing import List
import requests
import json
import re
import difflib
from collections import Counter
# from spellchecker import SpellChecker
from datetime import datetime
import pandas as pd
import ast
import random
import logging 
# from history_update_problem.call_or import export_rows
from call_or import *
from evaluation import *

In [5]:
models = ['llama3.1',  'mistral', 'gemma2','deepseek-r1']

# Worflow eval

In [6]:
def eval_workflows(pp_id, gt_wf_fp, pred_wf_fp):
    # print(gt_wf_fp)
    gt_ops_list = parse_recipe(pp_id, recipe=gt_wf_fp)
    pred_ops_list = parse_recipe(pp_id, recipe=pred_wf_fp)
    return {'pp_id': pp_id, 'gt_ops': gt_ops_list[pp_id], 'pred_ops': pred_ops_list[pp_id]}
    # print(gt_ops_list)
    # print(pred_ops_list)

answer_gt_path = '/projects/bces/lanl2/LLM4DC/evaluation/answer_1-154_gt.json'
answer_preds_llama = '/projects/bces/lanl2/LLM4DC/evaluation/answer_1-154_llama3.1.json'


# eval_answer_results = eval_answers(answer_gt_path, answer_preds_llama)
# model = models[0]
wf_gt_folder = '/projects/bces/lanl2/LLM4DC/datasets'

query_contents = pd.read_csv('/projects/bces/lanl2/LLM4DC/purposes/all_purposes.csv')
    
ops_result = {}
for model in models[:3]:
    ops_list = []

    wf_pred_folder = f'/projects/bces/lanl2/LLM4DC/CoT.response/{model}/recipes_llm'
    for query_id in range(155):
        row = query_contents[query_contents['ID'] == query_id]
        if len(row) == 0:
            continue
        # if model == 'llama3.1':
        if query_id >126:
            #TODO: what's the point to have the target_path here? 
            target_path = f'{wf_gt_folder}/hospital/clean_tables/hos_pp{query_id}.csv'
            wf_gt_fp = f"{wf_gt_folder}/hospital/workflows/hos_p{query_id}.json"
            wf_pred_fp = f"{wf_pred_folder}/{model}_hos_test_p{query_id}.json"
        elif query_id >= 111 and query_id <=126:
            target_path = f'{wf_gt_folder}/flights/cleaned_tables/flights_data_p{query_id}.csv'
            wf_gt_fp = f"{wf_gt_folder}/flights/workflows/flights_p{query_id}.json"
            wf_pred_fp = f"{wf_pred_folder}/{model}_flights_test_p{query_id}.json"
        elif query_id >= 92 and query_id <=110:
            target_path = f'{wf_gt_folder}/dish_datasets/cleaned_tables/dish_sample_p{query_id}.csv'
            wf_gt_fp = f"{wf_gt_folder}/dish_datasets/workflows/dish_sample_p{query_id}.json"
            wf_pred_fp = f"{wf_pred_folder}/{model}_dish_test_p{query_id}.json"
        elif query_id >= 62 and query_id <= 91:
            target_path = f'{wf_gt_folder}/ppp_datasets/cleaned_tables/ppp_sample_p{query_id}.csv'
            wf_gt_fp = f"{wf_gt_folder}/ppp_datasets/workflows/ppp_sample_p{query_id}.json"
            wf_pred_fp = f"{wf_pred_folder}/{model}_ppp_test_p{query_id}.json"
        elif query_id >= 31 and query_id <= 61:
            target_path = f'{wf_gt_folder}/CFI_datasets/cleaned_tables/chi_sample_p{query_id}.csv'
            wf_gt_fp = f"{wf_gt_folder}/CFI_datasets/workflows/chi_sample_p{query_id}.json"
            wf_pred_fp = f"{wf_pred_folder}/{model}_chi_test_p{query_id}.json"

        elif query_id <31:
            target_path = f'{wf_gt_folder}/menu_datasets/clean_tables/menu_sample_p{query_id}'
            wf_gt_fp = f"{wf_gt_folder}/menu_datasets/workflows/menu_sample_p{query_id}.json"
            wf_pred_fp = f"{wf_pred_folder}/{model}_menu_test_p{query_id}.json"
        if wf_gt_fp and wf_pred_fp:
            ops_list.append(eval_workflows(query_id, wf_gt_fp, wf_pred_fp))
    ops_result[model] = pd.DataFrame(ops_list)
# ops_df = pd.DataFrame(ops_list)

In [7]:
def parse_mean(df, col_name):
    total_wf = df.describe().loc['mean']
    # total_wf.columns = [col_name] #rename(columns={"mean": col_name})
    return total_wf

In [8]:
wf_length = []
total_wf = []
print(len(ops_result))
ppp_wf, dish_wf, menu_wf,chi_wf,hos_wf, flights_wf = [],[],[],[],[],[]
col_name = []
output_wf =  []
for key, value in ops_result.items():
    model = key
    ops_df = value
    ops_df['gt_ops_length'] = ops_df['gt_ops'].apply(len)
    ops_df['pred_ops_length'] = ops_df['pred_ops'].apply(len)
    ops_df['gt_ops_set_length'] = ops_df['gt_ops'].apply(lambda x: len(set(x)))
    ops_df['pred_ops_set_length'] = ops_df['pred_ops'].apply(lambda x: len(set(x)))

    ops_length_desc = ops_df.describe().loc['mean']
    ops_length_desc.columns = [model]
    wf_length.append(ops_length_desc)


    workflow_results = calculate_operation_metrics(ops_df['gt_ops'], ops_df['pred_ops'])
    workflow_results['pp_id'] = ops_df['pp_id']
    # print(workflow_results[workflow_results['pp_id'] == 127])
    workflow_results.set_index('pp_id', inplace=True)
    ops_df.set_index('pp_id', inplace=True)
    total_wf.append(parse_mean(workflow_results, f'total__{model}'))
    col_name.append(f'total__{model}')
    
    
    hos_results = workflow_results.loc[127:155]
       
    # hos_results = workflow_results[workflow_results['pp_id'] >= 127]
    total_wf.append(parse_mean(hos_results, f'hos__{model}'))
    hos_ops = ops_df.loc[127:155]
    wf_length.append(parse_mean(hos_ops, f'hos__{model}'))
    col_name.append(f'hos__{model}')


    # flights_results = workflow_results[workflow_results['pp_id'] >= 111][workflow_results['pp_id'] <=126]
    flights_results = workflow_results.loc[111:127]
    flights_ops = ops_df.loc[111:127]
    total_wf.append(parse_mean(flights_results, f'flights__{model}'))
    wf_length.append(parse_mean(flights_ops, f'flights_{model}'))
    col_name.append(f'flights__{model}')

    # ppp_results = workflow_results[workflow_results['pp_id'] >= 62][workflow_results['pp_id'] <=91]
    ppp_results = workflow_results.loc[62:91]
    ppp_ops = ops_df.loc[62:91] 
    wf_length.append(parse_mean(ppp_ops, f'ppp_{model}'))
    total_wf.append(parse_mean(ppp_results, f'ppp__{model}'))
    col_name.append(f'ppp__{model}')

    # dish_results = workflow_results[workflow_results['pp_id'] >= 92][workflow_results['pp_id'] <= 110]
    dish_results = workflow_results.loc[92:111]
    dish_ops = ops_df.loc[92:111] 
    wf_length.append(parse_mean(dish_ops, f'dish_{model}'))
    total_wf.append(parse_mean(dish_results, f'dish__{model}'))
    col_name.append(f'dish__{model}')

    # menu_results = workflow_results[workflow_results['pp_id'] < 31]
    menu_results = workflow_results.loc[:31]
    menu_ops = ops_df.loc[:31] 
    wf_length.append(parse_mean(menu_ops, f'menu_{model}'))
    total_wf.append(parse_mean(menu_results, f'menu__{model}'))
    col_name.append(f'menu__{model}')
    # chi_results = workflow_results[workflow_results['pp_id'] >= 31][workflow_results['pp_id'] <=61]
    chi_results = workflow_results.loc[31:62]
    chi_ops = ops_df.loc[92:111] 
    wf_length.append(parse_mean(chi_ops, f'chi_{model}'))
    total_wf.append(parse_mean(chi_results, f'chi__{model}'))
    col_name.append(f'chi__{model}')
wf_perf = pd.concat(total_wf, axis=1)
wf_perf.columns = col_name
# print(wf_perf)
wf_perf = wf_perf.transpose()
wf_length = pd.concat(wf_length, axis=1)
wf_length.columns = col_name
wf_length = wf_length.transpose()
wf_perf = wf_perf.reset_index()

3

In [9]:
wf_length

,pp_id,gt_ops_length,pred_ops_length,gt_ops_set_length,pred_ops_set_length
total__llama3.1,76.739437,7.492958,4.323944,3.563380,1.943662
hos__llama3.1,NaN,10.178571,4.714286,3.964286,1.785714
flights__llama3.1,NaN,8.647059,3.588235,3.882353,1.529412
ppp__llama3.1,NaN,6.090909,4.181818,3.500000,2.136364
dish__llama3.1,NaN,5.470588,3.882353,3.764706,2.294118
menu__llama3.1,NaN,6.903226,4.580645,2.870968,2.064516
chi__llama3.1,NaN,5.470588,3.882353,3.764706,2.294118
total__mistral,76.739437,7.492958,3.429577,3.563380,1.838028
hos__mistral,NaN,10.178571,4.321429,3.964286,1.964286
flights__mistral,NaN,8.647059,3.294118,3.882353,1.647059
ppp__mistral,NaN,6.090909,4.545455,3.500000,2.272727
dish__mistral,NaN,5.470588,3.823529,3.764706,2.235294
menu__mistral,NaN,6.903226,1.709677,2.870968,1.225806
chi__mistral,NaN,5.470588,3.823529,3.764706,2.235294
total__gemma2,76.739437,7.492958,4.640845,3.563380,2.197183
hos__gemma2,NaN,10.178571,6.500000,3.964286,2.535714
flights__gemma2,NaN,8.647059,3.588235,3.882353,1.470588
ppp__gemma2,NaN,6.090909,5.318182,3.500000,2.500000
dish__gemma2,NaN,5.470588,5.470588,3.764706,3.117647
menu__gemma2,NaN,6.903226,3.129032,2.870968,1.935484
chi__gemma2,NaN,5.470588,5.470588,3.764706,3.117647

In [10]:
wf_length.to_csv('workflow_length.csv')

In [11]:
wf_perf

                index  accuracy  precision    recall        f1
0     total__llama3.1  0.098592   0.933099  0.526526  0.644679
1       hos__llama3.1  0.000000   1.000000  0.458333  0.618707
2   flights__llama3.1  0.000000   0.970588  0.383333  0.534874
3       ppp__llama3.1  0.272727   0.958333  0.665152  0.755880
4      dish__llama3.1  0.117647   0.867647  0.514706  0.614426
5      menu__llama3.1  0.193548   0.870968  0.623118  0.701101
6       chi__llama3.1  0.064516   0.940860  0.512366  0.638249
7      total__mistral  0.049296   0.765610  0.409624  0.506539
8        hos__mistral  0.000000   0.922619  0.453571  0.591412
9    flights__mistral  0.000000   0.852941  0.357843  0.492717
10       ppp__mistral  0.181818   0.846970  0.586364  0.660390
11      dish__mistral  0.058824   0.759804  0.431373  0.517227
12      menu__mistral  0.064516   0.489247  0.252688  0.315361
13       chi__mistral  0.032258   0.795699  0.416129  0.509524
14      total__gemma2  0.077465   0.875939  0.551408  0.645607
15        hos__gemma2  0.035714   0.952381  0.611310  0.732313
16    flights__gemma2  0.000000   0.941176  0.343137  0.490756
17        ppp__gemma2  0.181818   0.859848  0.673485  0.728535
18       dish__gemma2  0.000000   0.674510  0.583333  0.599907
19       menu__gemma2  0.161290   0.817204  0.586559  0.656989
20        chi__gemma2  0.096774   0.935484  0.484409  0.611905

In [12]:
wf_perf.to_csv('workflow_results_llama_mistral_gemma2.csv')

# Dataset Eval

In [27]:
# def retrieve_tg_cols(tg_cols_fp="target_columns_list.csv"):
#     id_tg_cols = {}
#     tg_df = pd.read_csv(tg_cols_fp)
#     result_dict = tg_df.set_index('ID')['tg_columns'].to_dict()
#     return result_dict

In [15]:
result_dict = retrieve_tg_cols("/projects/bces/lanl2/LLM4DC/evaluation/target_column_list.csv")
print(result_dict)
# model = "llama3.1"
# model = "mistral"
# model = "gemma2"
# model = "dirty"
data_gt_folder = "/projects/bces/lanl2/LLM4DC/datasets"

for model in models[:3] + ["dirty"]:
    ratio_list = []
    for query_id in range(155):
        # print(query_id)
        tg_cols = result_dict.get(query_id)
        if tg_cols:
            if model=="dirty":
                if query_id >126:
                    target_path = f'{data_gt_folder}/hospital/clean_tables/hos_pp{query_id}.csv'
                    table_preds_path = f'/projects/bces/lanl2/LLM4DC/datasets/hospital/hos_data_p{query_id}.csv'
                elif query_id >= 111 and query_id <=126:
                    target_path = f'{data_gt_folder}/flights/cleaned_tables/flights_data_p{query_id}.csv'
                    table_preds_path = f'/projects/bces/lanl2/LLM4DC/datasets/flights/flights_data_p{query_id}.csv'
                    # target_path = None
                    # table_preds_path = None
                elif query_id >= 92 and query_id <=110:
                    target_path = f'{data_gt_folder}/dish_datasets/cleaned_tables/dish_sample_p{query_id}.csv'
                    table_preds_path = f'/projects/bces/lanl2/LLM4DC/datasets/dish_datasets/dish_data_p{query_id}.csv'
                elif query_id >= 62 and query_id <= 91:
                    target_path = f'{data_gt_folder}/ppp_datasets/cleaned_tables/ppp_sample_p{query_id}.csv'
                    table_preds_path =  f'/projects/bces/lanl2/LLM4DC/datasets/ppp_datasets/ppp_data_p{query_id}.csv'
                elif query_id >= 31 and query_id <= 61:
                    target_path = f'{data_gt_folder}/CFI_datasets/cleaned_tables/chi_sample_p{query_id}.csv'
                    table_preds_path = f'/projects/bces/lanl2/LLM4DC/datasets/CFI_datasets/chi_food_data_p{query_id}.csv'
                elif query_id <31:
                    target_path = f'{data_gt_folder}/menu_datasets/clean_tables/menu_sample_p{query_id}.csv'
                    table_preds_path = f'/projects/bces/lanl2/LLM4DC/datasets/menu_datasets/menu_p{query_id}.csv'
            else:
                llm_folder = f"CoT.response/{model}/datasets_llm"
                data_gt_folder = "/projects/bces/lanl2/LLM4DC/datasets"
                pred_fp = f'/projects/bces/lanl2/LLM4DC/{llm_folder}'
                if query_id >126:
                    target_path = f'{data_gt_folder}/hospital/clean_tables/hos_pp{query_id}.csv'
                    table_preds_path = f'{pred_fp}/{model}_hos_test_p{query_id}.csv'
                elif query_id >= 111 and query_id <=126:
                    target_path = f'{data_gt_folder}/flights/cleaned_tables/flights_data_p{query_id}.csv'
                    table_preds_path = f'{pred_fp}/{model}_flights_test_p{query_id}.csv'
                elif query_id >= 92 and query_id <=110:
                    target_path = f'{data_gt_folder}/dish_datasets/cleaned_tables/dish_sample_p{query_id}.csv'
                    table_preds_path = f'{pred_fp}/{model}_dish_test_p{query_id}.csv'
                elif query_id >= 62 and query_id <= 91:
                    target_path = f'{data_gt_folder}/ppp_datasets/cleaned_tables/ppp_sample_p{query_id}.csv'
                    table_preds_path = f'{pred_fp}/{model}_ppp_test_p{query_id}.csv'
                elif query_id >= 31 and query_id <= 61:
                    target_path = f'{data_gt_folder}/CFI_datasets/cleaned_tables/chi_sample_p{query_id}.csv'
                    table_preds_path = f'{pred_fp}/{model}_chi_test_p{query_id}.csv'
                elif query_id <31:
                    target_path = f'{data_gt_folder}/menu_datasets/clean_tables/menu_sample_p{query_id}.csv'
                    table_preds_path = f'{pred_fp}/{model}_menu_test_p{query_id}.csv'
            if target_path and table_preds_path:
                gt_df = pd.read_csv(target_path)
                preds_df = pd.read_csv(table_preds_path)
                # print(gt_df.head(5), preds_df.head(5))
                res = average_match_ratio(gt_df, preds_df, tg_cols)
                ratio_list.append({'pp_id': query_id, 'ratio': res})
    dt_result = pd.DataFrame(ratio_list)
    dt_result.to_csv(f'evaluation/{model}_table_result.csv')

{1: 'page_count', 2: 'page_count', 3: 'event', 4: 'event', 5: 'event', 6: 'venue', 7: 'occasion', 8: 'occasion', 9: 'page_count, dish_count', 10: 'dish_count', 11: 'page_count, dish_count', 12: 'page_count, location', 13: 'sponsor, currency', 14: 'sponsor, dish_count', 15: 'sponsor, event', 16: 'sponsor, event', 17: 'sponsor, event', 18: 'sponsor, event', 19: 'page_count, venue', 20: 'sponsor', 21: 'event', 22: 'occasion', 23: 'venue, dish_count', 24: 'status', 25: 'sponsor, currency', 26: 'date', 27: 'date, page_count, dish_count', 28: 'page_count, venue', 29: 'occasion', 30: 'currency', 31: 'Risk', 32: 'Results', 33: 'Facility Type', 34: 'Facility Type', 35: 'Inspection Type', 36: 'DBA Name, Results', 37: 'DBA Name, Results', 38: 'Facility Type, Risk', 39: 'Facility Type, Risk', 40: 'Facility Type, Risk', 41: 'Facility Type, Risk', 42: 'Facility Type, Risk', 43: 'Facility Type, Results', 44: 'Results', 45: 'Facility Type, Inspection ID', 46: 'Risk', 47: 'Facility Type, Results', 48: 'DBA Name, Inspection ID', 49: 'Facility Type, Risk, Results', 50: 'Inspection Type', 51: 'Facility Type,Results', 52: 'Address, Risk, Results', 53: 'Risk, Results', 54: 'Inspection Date', 55: 'DBA Name', 56: 'License #, Results', 57: 'DBA Name, Risk, Inspection Date', 58: 'Facility Type, Risk', 59: 'DBA Name, Inspection Date', 60: 'Facility Type, Inspection ID, Inspection Date', 62: 'LoanAmount', 63: 'LoanAmount', 64: 'LoanAmount', 65: 'NAICSCode, JobsReported', 66: 'JobsReported, LoanAmount', 67: 'City', 68: 'BusinessType, LoanAmount', 69: 'BusinessType, LoanAmount', 70: 'BusinessType, LoanAmount', 71: 'BusinessType, Zip', 72: 'Zip, LoanAmount', 73: 'Zip, LoanAmount', 74: 'Gender, LoanAmount', 75: 'Gender, LoanAmount', 76: 'City, LoanAmount', 77: 'City, LoanAmount', 78: 'Zip, LoanAmount', 79: 'Zip, LoanAmount', 80: 'RaceEthnicity, LoanAmount', 81: 'RaceEthnicity, LoanAmount', 87: 'City, LoanAmount, JobsReported', 89: 'City, LoanAmount, Zip', 92: 'times_appeared', 93: 'name, first_appeared, last_appeared', 94: 'name, first_appeared, last_appeared', 98: 'name, lowest_price', 99: 'name, highest_price', 100: 'name, first_appeared', 101: 'name, first_appeared', 102: 'name, menus_appeared', 103: 'name, menus_appeared', 104: 'name, times_appeared, highest_price', 105: 'name, times_appeared, lowest_price', 106: 'name, highest_price, lowest_price', 107: 'name, highest_price, lowest_price', 108: 'name,  highest_price, lowest_price', 109: 'name, menus_appeared, times_appeared', 110: 'name, times_appeared, highest_price, \nlowest_price', 111: 'sched_dep_time, act_dep_time', 112: 'sched_dep_time, sched_arr_time', 113: 'src, sched_dep_time, act_dep_time', 114: 'src', 115: 'flight', 116: 'sched_arr_time', 117: 'src, act_arr_time, sched_arr_time', 118: 'sched_dep_time, act_dep_time', 119: 'sched_arr_time', 120: 'src, sched_dep_time, act_dep_time', 121: 'act_dep_time, sched_dep_time', 122: 'act_dep_time, act_arr_time', 123: 'sched_dep_time, act_dep_time', 124: 'sched_arr_time, act_arr_time', 125: 'src, sched_dep_time, act_dep_time', 126: 'sched_arr_time, act_arr_time', 127: 'City', 128: 'City', 129: 'CountyName', 130: 'HospitalType, CountyName, EmergencyService', 131: 'HospitalOwner, City, ZipCode', 132: 'HospitalName, HospitalType, HospitalOwner', 133: 'EmergencyService, HospitalType', 134: 'HospitalType, HospitalOwner', 135: 'CountyName, EmergencyService', 136: 'City, HospitalOwner, EmergencyService', 137: 'CountyName, HospitalType', 138: 'HospitalType, HospitalOwner, City', 139: 'ZipCode, HospitalType, HospitalOwner', 140: 'City, HospitalType', 141: 'HospitalType, City, ZipCode', 142: 'EmergencyService, HospitalType', 143: 'CountyName, HospitalOwner, HospitalType', 144: 'HospitalOwner, EmergencyService', 145: 'City, EmergencyService', 146: 'HospitalType, ZipCode', 147: 'HospitalOwner, HospitalType', 148: 'EmergencyService, CountyName', 149: 'HospitalOwner, ZipCode, HospitalType', 150: 'HospitalType, EmergencyService', 151: 'City, HospitalOwner, HospitalType', 152: 'HospitalOwner, City', 153: 'ZipCode, EmergencyService', 154: 'City, HospitalOwner'}
30
match_ratio: 0.3 == match_count 30 / length 100
100
match_ratio: 1.0 == match_count 100 / length 100
String Mismatch: BANQUET <--> 11TH ANNUAL BANQUET
String Mismatch: LUNCHEON <--> Dinner
String Mismatch: DINNER <--> CHRISTMAS DINNER
String Mismatch: LUNCHEON <--> LUNCHEON TENDERED IMPERIAL COUNCIL
String Mismatch: BREAKFAST <--> Dinner
String Mismatch: BANQUET <--> Dinner
String Mismatch: 15NTH BURNS ANNIVERSARY <--> Dinner
String Mismatch: BREAKFAST <--> Dinner
String Mismatch: BREAKFAST <--> Dinner
String Mismatch: DINNER <--> DINNER (?)
String Mismatch: BANQUET <--> BANQUET AND RECEPTION COMMEMORATING 50 YEARS SINCE THE ADMISSION OF HONORABLE JAMES TYNDALE MITCHELL,LL.D. CHIEF JUSTICE OF THE SUPREME COURT OF PA TO THE BAR OF PHILADELPHIA
String Mismatch: TIFFIN <--> Dinner
String Mismatch: DINNER <--> DAILY MENU, DINNER
String Mismatch: BANQUET <--> THIRD ANNUAL BANQUET
String Mismatch: TIFFIN <--> Dinner
String Mismatch: LUNCHEON <--> Dinner
String Mismatch: BANQUET <--> Dinner
String Mismatch: BANQUET <--> ALL AMERICAN BANQUET IN HONOR OF EDWIN C. HALL
String Mismatch: BANQUET <--> Dinner
27
match_ratio: 0.5869565217391305 == match_count 27 / length 100
String Mismatch: 11TH ANNUAL BANQUET <--> Other
String Mismatch: BREAKFAST <--> Other
String Mismatch: FOURTH ANNUSL DINNER <--> DINNER
String Mismatch: BREAKFAST <--> Other
String Mismatch: PRIVATE BANQUET <--> Other
String Mismatch: BREAKFAST <--> Other
String Mismatch: MENU <--> DINNER
String Mismatch: BREAKFAST MENU <--> Other
String Mismatch: ZWEITES FRUHSTUCK <--> BREAKFAST
String Mismatch: DINNER <--> Other
String Mismatch: FRUHSTUCK <--> BREAKFAST
String Mismatch: LUNCH <--> Other
String Mismatch: TIFFIN <--> Other
String Mismatch: BREAKFAST <--> Other
String Mismatch: BREAKFAST <--> Other
String Mismatch: DAILY MENU, DINNER <--> DINNER
String Mismatch: THIRD ANNUAL BANQUET <--> BANQUET
String Mismatch: LUNCH <--> Other
String Mismatch: PERSONALLY CONDUCTED TOUR THROUGH MEXICO & CALIFORNIA <--> TOUR
String Mismatch: TIFFIN <--> Other
String Mismatch: FIRST ANNUAL BANQUET <--> BANQUET
String Mismatch: BREAKFAST <--> Other
String Mismatch: ANNUAL BANQUET <--> BANQUET
23
match_ratio: 0.5 == match_count 23 / length 100
String Mismatch: LUNCHEON <--> LUCHON
String Mismatch: CHRISTMAS DINNER <--> BANQUET
String Mismatch: ZWEITES FRUHSTUCK <--> DINNER
String Mismatch: DINNER <--> DINNER (?)
String Mismatch: DINNER <--> DINNER TO ABOVE
41
match_ratio: 0.8913043478260869 == match_count 41 / length 100
String Mismatch: PROF <--> Professional
String Mismatch: GOVT <--> Government
String Mismatch: PATR <--> PATR;
String Mismatch: POL <--> Government
String Mismatch: RAILROAD <--> Restaurant
String Mismatch: RAILROAD <--> Restaurant
String Mismatch: SOC <--> SOCIAL
String Mismatch: SOC <--> SOCIAL
String Mismatch: RAILROAD <--> Restaurant
String Mismatch: PROF <--> Professional
String Mismatch: SOC <--> SOC;
String Mismatch: GOVT <--> GOV;
String Mismatch: SOC <--> SOC;
String Mismatch: SOC <--> SOC;
String Mismatch: PATR <--> PATR;
String Mismatch: SOC <--> SOC;
String Mismatch: POL <--> Government
String Mismatch: EDUC <--> EDUC;
String Mismatch: SOC <--> SOC;
29
match_ratio: 0.6041666666666666 == match_count 29 / length 100
String Mismatch: DAILY <--> Other (Daily)
String Mismatch: DAILY <--> OTHER (DAILY);
String Mismatch: OTHER (ANNIV) <--> Other (Anniversary)
String Mismatch: OTHER, [SOC?] <--> Other (Anniversary)
21
match_ratio: 0.21 == match_count 21 / length 100
String Mismatch: DAILY <--> DAILY;
String Mismatch: RELIGIOUS HOLIDAY <--> HOLIDAY
String Mismatch: DAILY <--> DAILY;
String Mismatch: [SOC?] <--> OTHER
String Mismatch: DAILY <--> DAILY;
String Mismatch: ANNIVERSARY <--> ANNIVERSARY;
String Mismatch: SECULAR HOLIDAY <--> HOLIDAY
String Mismatch: DAILY <--> OTHER
String Mismatch: DAILY <--> OTHER
String Mismatch: SECULAR HOLIDAY <--> HOLIDAY
String Mismatch: ANNIVERSARY <--> ANNIVERSARY;
String Mismatch: OTHER (ANNIV) <--> OTHER
String Mismatch: OTHER, [SOC?] <--> OTHER, [SOC?];
14
match_ratio: 0.14 == match_count 14 / length 100
100
match_ratio: 1.0 == match_count 100 / length 100
100
match_ratio: 1.0 == match_count 100 / length 100
35
match_ratio: 0.35 == match_count 35 / length 100
37
match_ratio: 0.37 == match_count 37 / length 100
35
match_ratio: 0.35 == match_count 35 / length 100
100
match_ratio: 1.0 == match_count 100 / length 100
String Mismatch: BATTERY PARK HOTEL <--> UNKNOWN
String Mismatch: SOUTHERN PACIFIC <--> UNKNOWN
String Mismatch: SPILKER'S RESTAURANT AND GRILL ROOM <--> UNKNOWN
String Mismatch: ADAM'S RESTAURANT <--> UNKNOWN
String Mismatch: S.S. NIEUW AMSTERDAM <--> UNKNOWN
String Mismatch: UNKNOWN <--> ?
String Mismatch: SPRINGFIELD CALEDONIANS <--> UNKNOWN
String Mismatch: NIPPON YUSEN KAISHA <--> UNKNOWN
String Mismatch: UNKNOWN <--> [Restaurant name and/or location not given]
String Mismatch: THE MOUQUIN RESTAURANT AND WINE CO. <--> UNKNOWN
String Mismatch: DETROIT BOARD OF COMMERCE <--> UNKNOWN
String Mismatch: HOTEL BELVEDERE <--> UNKNOWN
String Mismatch: UNKNOWN <--> [Restaurant name and/or location not given]
String Mismatch: THE PORTLAND <--> UNKNOWN
String Mismatch: SOUTHERN PACIFIC <--> UNKNOWN
String Mismatch: COLONIAL HOTEL <--> UNKNOWN
String Mismatch: THE COMMODORE HOTEL <--> UNKNOWN
String Mismatch: NIPPON YUSEN KAISHA <--> UNKNOWN
String Mismatch: YE OLDE DUTCH TAVERN <--> UNKNOWN
String Mismatch: TOYO KISEN KAISHA <--> UNKNOWN
String Mismatch: NORDDEUTSCHER LLOYD BREMEN <--> Norddeutscherrr Lloyd Bremen
String Mismatch: TOOTS SHOR <--> UNKNOWN
String Mismatch: FRATERNAL UNION OF ANOINTED HIGH PRIESTS OF THE STATE OF NEW YORK <--> UNKNOWN
String Mismatch: THE BILTMORE <--> UNKNOWN
String Mismatch: WALDORF ASTORIA <--> UNKNOWN
String Mismatch: NIPPON YUSEN KAISHA <--> UNKNOWN
String Mismatch: UNKNOWN <--> [Restaurant And/Or Location Not Given]
String Mismatch: NIPPON YUSEN KAISHA <--> UNKNOWN
String Mismatch: WALDORF ASTORIA <--> UNKNOWN
String Mismatch: S.S. NIEUW AMSTERDAM <--> UNKNOWN
String Mismatch: NOVIOMAGUS <--> UNKNOWN
String Mismatch: HOTEL MARIE ANTOINETTE <--> UNKNOWN
String Mismatch: STATLER'S HOTEL AND RESTAURANT <--> UNKNOWN
String Mismatch: AMEN CORNER AXE <--> UNKNOWN
String Mismatch: THE BILTMORE <--> UNKNOWN
String Mismatch: COFFEE HOUSE <--> UNKNOWN
String Mismatch: KAISERHOF <--> UNKNOWN
String Mismatch: FREINDS OF WILLIAM CLAUSS <--> UNKNOWN
62
match_ratio: 0.62 == match_count 62 / length 100
String Mismatch: ADAM'S RESTAURANT <--> ADAMS' RESTAURANT
String Mismatch: NORDDEUTSCHER LLOYD BREMEN <--> NORDDEUTSCHERRR LLOYD BREMEN
92
match_ratio: 0.9787234042553191 == match_count 92 / length 100
String Mismatch: DOLLARS <--> DOLARS$
String Mismatch: DOLLARS <--> dolars
String Mismatch: DOLLARS <--> DOLARS$
String Mismatch: DOLLARS <--> Dolar
String Mismatch: DOLLARS <--> Dolar
String Mismatch: DOLLARS <--> Dolar
String Mismatch: DOLLARS <--> dolr
String Mismatch: DOLLARS <--> dolr
String Mismatch: DOLLARS <--> dolar
String Mismatch: DOLLARS <--> DOLARS$
String Mismatch: DOLLARS <--> Dolars
String Mismatch: DOLLARS <--> Dolars
String Mismatch: DOLLARS <--> dolars$
String Mismatch: DOLLARS <--> Dolar
String Mismatch: DOLLARS <--> dolr
String Mismatch: DOLLARS <--> dolars$
String Mismatch: DOLLARS <--> DOLR
String Mismatch: DOLLARS <--> DOLR
String Mismatch: DOLLARS <--> dolar
String Mismatch: DOLLARS <--> Dolars
String Mismatch: DOLLARS <--> dolars
String Mismatch: DOLLARS <--> dolars
String Mismatch: DOLLARS <--> dolar
String Mismatch: DOLLARS <--> Dolar
18
match_ratio: 0.42857142857142855 == match_count 18 / length 100
String Mismatch: ADAM'S RESTAURANT <--> Adams' Restaurant
String Mismatch: WIEHL & WIDMAN <--> Wiehl and Widman
String Mismatch: [RESTAURANT AND/OR LOCATION NOT GIVEN] <--> [Restaurant name and/or location not given]
String Mismatch: [RESTAURANT AND/OR LOCATION NOT GIVEN] <--> [Restaurant name and/or location not given]
93
match_ratio: 0.9587628865979382 == match_count 93 / length 100
100
match_ratio: 1.0 == match_count 100 / length 100
String Mismatch: Spilker's Restaurant and Grill Room <--> Wiehl and Widman
String Mismatch: Adam's Restaurant <--> Adams' Restaurant
String Mismatch: S.S. Nieuw Amsterdam <--> SS Nieuw Amsterdam
String Mismatch: Wiehl & Widman <--> Wiehl and Widman
String Mismatch: University Of Richmond <--> Springfield Caledonians
String Mismatch: The Mouquin Restaurant and Wine Co. <--> Four Seasons
String Mismatch: The Brass Rail <--> Four Seasons
String Mismatch: THE PENNSYLVANIA BAR ASSOCIATION ON BEHALF OF THE BAR OF THE COMMONWEALTH <--> Pennsylvania Bar Association
String Mismatch: NORDDEUTSCHER LLOYD BREMEN <--> NORDDEUTSCHERRR LLOYD BREMEN
String Mismatch: Gardner & Smith <--> Gardner and Smith
String Mismatch: TOYO KISEN KAISHA - HING KONG MARU <--> Toyo Kisen Kaisha - Hong Kong Maru
String Mismatch: S.S. Nieuw Amsterdam <--> SS Nieuw Amsterdam
String Mismatch: The Four Seasons <--> Four Seasons
String Mismatch: COEUR DE LION CAMMANDERY NUMBER TWENTY-THREE KNIGHTS TEMPLAR <--> Coeur de Lion Commandery Number Twenty-Three Knights Templar
80
match_ratio: 0.851063829787234 == match_count 80 / length 100
String Mismatch: 11TH ANNUAL BANQUET <--> BANQUET
String Mismatch: FOURTH ANNUSL DINNER <--> FOURTH ANNUAL DINNER
String Mismatch: LUNCHEON TENDERED IMPERIAL COUNCIL <--> LUNCH/DINNER
String Mismatch: BREAKFAST <--> BREKFAST
String Mismatch: 15NTH BURNS ANNIVERSARY <--> 15TH BURNS ANNIVERSARY
String Mismatch: SECOND ANNUAL DINNER <--> ANNUAL DINNER
String Mismatch: MENU <--> DINNER
String Mismatch: BREAKFAST <--> BREAKFAST MENU
String Mismatch: ZWEITES FRUHSTUCK <--> SECOND BREAKFAST
String Mismatch: TIFFIN <--> BREAKFAST
String Mismatch: DAILY MENU, DINNER <--> LUNCH/DINNER
String Mismatch: THIRD ANNUAL BANQUET <--> BANQUET
String Mismatch: PERSONALLY CONDUCTED TOUR THROUGH MEXICO & CALIFORNIA <--> TOUR
String Mismatch: TIFFIN <--> BREAKFAST
String Mismatch: FIRST ANNUAL BANQUET <--> BANQUET
String Mismatch: ALL AMERICAN BANQUET IN HONOR OF EDWIN C. HALL <--> BANQUET
String Mismatch: DINNER TO ABOVE <--> LUNCH/DINNER
29
match_ratio: 0.6304347826086957 == match_count 29 / length 100
String Mismatch: Adam's Restaurant <--> ADAMS' RESTAURANT
String Mismatch: NORDDEUTSCHER LLOYD BREMEN <--> NORDDEUTSCHERRR LLOYD BREMEN
92
match_ratio: 0.9787234042553191 == match_count 92 / length 100
String Mismatch: FOURTH ANNUSL DINNER <--> BREAKFAST
String Mismatch: LUNCHEON TENDERED IMPERIAL COUNCIL <--> LUNCH
String Mismatch: LUNCH AND DINNER <--> LUNCH
String Mismatch: 15NTH BURNS ANNIVERSARY <--> LUNCH
String Mismatch: MENU <--> LUNCH
String Mismatch: DINNER TO QUEEN ALEXANDRE & PRINCESS VICTORIA OF RUSSIA <--> Dinner
String Mismatch: THIRD ANNUAL BANQUET <--> Annual Banquet
String Mismatch: LUNCH <--> Lunh
String Mismatch: ALL AMERICAN BANQUET IN HONOR OF EDWIN C. HALL <--> LUNCH
String Mismatch: ANNUAL BANQUET <--> LUNCH
String Mismatch: DINNER TO ABOVE <--> Dinner
35
match_ratio: 0.7608695652173914 == match_count 35 / length 100
String Mismatch: Adam's Restaurant <--> Adams' Restaurant
String Mismatch: NORDDEUTSCHER LLOYD BREMEN <--> NORDDEUTSCHERRR LLOYD BREMEN
String Mismatch: FRATERNAL UNION OF ANOINTED HIGH PRIESTS OF THE STATE OF NEW YORK <--> Fraterna Union of Anointed High Priests of the State of New York
String Mismatch: T.N. "Conte Di Savoia""" <--> T.N. Conte di Savoia
90
match_ratio: 0.9574468085106383 == match_count 90 / length 100
String Mismatch: DINNER <--> Dinnr
String Mismatch: BREAKFAST <--> breakfast menu
String Mismatch: DINNER <--> dinner (?)
String Mismatch: DINNER <--> DNNER
String Mismatch: DINNER <--> dinnr
String Mismatch: DINNER <--> Dnner
String Mismatch: DINNER <--> DINR
String Mismatch: DINNER <--> dinr
String Mismatch: DINNER <--> dinner to above
37
match_ratio: 0.8043478260869565 == match_count 37 / length 100
String Mismatch: AMY'S <--> Amys
String Mismatch: S.S. NIEUW AMSTERDAM <--> SS Nieuw Amsterdam
String Mismatch: SEABOARD RAILWAY <--> Seaboard  Railway
String Mismatch: HOTEL ST. REGIS <--> Hotel _St. _Regis
String Mismatch: THE NEW MILLS HOTEL <--> The  New  Mills  Hotel
String Mismatch: LOUIS SHERRY <--> Louis _Sherry
String Mismatch: DETROIT BOARD OF COMMERCE <--> DETROIT _BOARD _OF _COMMERCE
String Mismatch: HOTEL BELVEDERE <--> Hotel  Belvedere
String Mismatch: SOUTHERN PACIFIC <--> Southern  Pacific
String Mismatch: HAMBURG AMERIKA LINIE <--> Hamburg America Line
String Mismatch: HEALY'S FORTY SECOND STREET RESTAURANT <--> Healy's Forty-Second Street Restaurant
String Mismatch: THE COMMODORE HOTEL <--> The  Commodore  Hotel
String Mismatch: HAMBURG AMERIKA LINIE <--> Hamburg America Line
String Mismatch: THE PENNSYLVANIA BAR ASSOCIATION ON BEHALF OF THE BAR OF THE COMMONWEALTH <--> Pennsylvania Railroad
String Mismatch: THE MAPLEWOOD <--> Maplewood
String Mismatch: TOYO KISEN KAISHA HING KONG MARU <--> TOYO  KISEN  KAISHA  -  HING  KONG  MARU
String Mismatch: NORWEGIAN GOVERNMENT <--> NORWEGIAN _GOVERNMENT
String Mismatch: HAMBURG AMERIKA LINIE <--> Hamburg America Line
String Mismatch: FRATERNAL UNION OF ANOINTED HIGH PRIESTS OF THE STATE OF NEW YORK <--> Fraternals Union Of Anointed High Priests Of The State Of New York
String Mismatch: HAMBURG AMERIKA LINIE <--> Hamburg America Line
String Mismatch: R.M.S. PARTHIA <--> RMS Parthia
String Mismatch: HOTEL IMPERIAL <--> Hotel  Imperial
String Mismatch: HEALY'S FORTY SECOND STREET RESTAURANT <--> Healy's _Forty-second _Street _restaurant
String Mismatch: S.S. NIEUW AMSTERDAM <--> SS Nieuw Amsterdam
String Mismatch: T.N. "CONTE DI SAVOIA""" <--> TN Conte Di Savoia
String Mismatch: HOTEL MARIE ANTOINETTE <--> Hotel Marie-Antoinette
String Mismatch: COEUR DE LION CAMMANDERY NUMBER TWENTY THREE KNIGHTS TEMPLAR <--> Coeur de Lion Commandery No. 23 Knights Templar
61
match_ratio: 0.648936170212766 == match_count 61 / length 100
String Mismatch: LUNCH <--> luncheon
String Mismatch: LUNCH AND DINNER <--> lunch
String Mismatch: BREAKFAST <--> breakfast menu
String Mismatch: BANQUET AND RECEPTION COMMEMORATING 50 YEARS SINCE THE ADMISSION OF HONORABLE JAMES TYNDALE MITCHELL,LL.D. CHIEF JUSTICE OF THE SUPREME COURT OF PA TO THE BAR OF PHILADELPHIA <--> banquet and reception commemorating 50 years since the admission of honorable james tyndale mitchelllld chief justice of the supreme court of pa to the bar of philadelphia
String Mismatch: DINNER TO QUEEN ALEXANDRE & PRINCESS VICTORIA OF RUSSIA <--> dinner to queen alexandre  princess victoria of russia
String Mismatch: DAILY MENU, DINNER <--> daily menu dinner
String Mismatch: PERSONALLY CONDUCTED TOUR THROUGH MEXICO & CALIFORNIA <--> personally conducted tour through mexico  california
String Mismatch: LUNCH <--> luncheon
String Mismatch: ALL AMERICAN BANQUET IN HONOR OF EDWIN C. HALL <--> all american banquet in honor of edwin c hall
String Mismatch: DINNER <--> dinner to above
36
match_ratio: 0.782608695652174 == match_count 36 / length 100
37
match_ratio: 0.37 == match_count 37 / length 100
String Mismatch: PROFESSIONAL <--> PROF;.?
String Mismatch: GOVERNMENT <--> Airport
String Mismatch: PATRONAGE <--> Restaurant
String Mismatch: POLITICAL <--> Restaurant
String Mismatch: RAILROAD <--> Commercial
String Mismatch: RAILROAD <--> Commercial
String Mismatch: SOCIAL <--> SOCIAL.?
String Mismatch: RAILROAD <--> Commercial
String Mismatch: SS <--> SS; FOR
String Mismatch: PROFESSIONAL <--> Airport
String Mismatch: SOCIAL <--> Airport
String Mismatch: SOCIAL <--> Airport
String Mismatch: PATRONAGE <--> PATR;
String Mismatch: SOCIAL <--> Airport
String Mismatch: POLITICAL <--> Restaurant
String Mismatch: EDUCATION <--> EDUC;
32
match_ratio: 0.6666666666666666 == match_count 32 / length 100
String Mismatch: BATTERY PARK HOTEL <--> [BATTERY PARK HOTEL]
String Mismatch: USMS <--> [USMS]
String Mismatch: SOUTHERN PACIFIC <--> [SOUTHERN PACIFIC]

In [16]:
dt_result

     pp_id     ratio
0        1  0.300000
1        2  1.000000
2        3  0.565217
3        4  0.869565
4        5  0.152174
..     ...       ...
137    150  0.450000
138    151  0.450000
139    152  0.300000
140    153  0.775000
141    154  0.500000

[142 rows x 2 columns]

In [17]:
total_tab = []
col_name = []
for model in models[:3] + ["dirty"]:
    print(model)
    
    table_results = pd.read_csv(f'evaluation/{model}_table_result.csv')
    table_results.set_index('pp_id', inplace=True)

    total_tab.append(parse_mean(table_results, f'total__{model}'))
    col_name.append(f'total__{model}')
    
    
    hos_results = table_results.loc[127:155]
    hos_results.reset_index()
    # hos_results = workflow_results[workflow_results['pp_id'] >= 127]
    total_tab.append(parse_mean(hos_results, f'hos__{model}'))
    
    col_name.append(f'hos__{model}')


    # flights_results = workflow_results[workflow_results['pp_id'] >= 111][workflow_results['pp_id'] <=126]
    flights_results = table_results.loc[111:127]
    flights_results.reset_index()
    total_tab.append(parse_mean(flights_results, f'flights__{model}'))
    col_name.append(f'flights__{model}')

    # ppp_results = workflow_results[workflow_results['pp_id'] >= 62][workflow_results['pp_id'] <=91]
    ppp_results = table_results.loc[62:91]
    ppp_results.reset_index()
    total_tab.append(parse_mean(ppp_results, f'ppp__{model}'))
    col_name.append(f'ppp__{model}')

    # dish_results = workflow_results[workflow_results['pp_id'] >= 92][workflow_results['pp_id'] <= 110]
    dish_results = table_results.loc[92:111]
    dish_results.reset_index()
    total_tab.append(parse_mean(dish_results, f'dish__{model}'))
    col_name.append(f'dish__{model}')

    # menu_results = workflow_results[workflow_results['pp_id'] < 31]
    menu_results = table_results.loc[:31]
    menu_results = menu_results.reset_index()
    total_tab.append(parse_mean(menu_results, f'menu__{model}'))
    col_name.append(f'menu__{model}')
    # chi_results = workflow_results[workflow_results['pp_id'] >= 31][workflow_results['pp_id'] <=61]
    chi_results = table_results.loc[31:62]
    chi_results = chi_results.reset_index()
    total_tab.append(parse_mean(chi_results, f'chi__{model}'))
    col_name.append(f'chi__{model}')
tab_perf = pd.concat(total_tab, axis=1)
tab_perf.columns = col_name
# print(wf_perf)
tab_perf = tab_perf.transpose()
tab_perf.to_csv('table_column_ratio_results_llama_mistral_gemma2.csv')

llama3.1
mistral
gemma2
dirty

In [120]:
dt_result.head()

   pp_id  ratio
0      1   0.30
1      2   1.00
2      3   0.26
3      4   0.40
4      5   0.07

In [18]:
stat = dt_result['ratio'].describe()
for idx in ['mean', 'std',	'min',	'max',	'25%',	'50%',	'75%']:
    print(stat.loc[idx])

0.42616081449511906
0.285582545474569
0.0
1.0
0.2
0.4557692307692308
0.5958333333333333

In [122]:
hos_dt_results = dt_result[dt_result['pp_id'] >= 127]
stat = hos_dt_results['ratio'].describe()
for idx in ['mean', 'std',	'min',	'max',	'25%',	'50%',	'75%']:
    print(stat.loc[idx])

0.4532738095238095
0.13935734489692167
0.21666666666666665
0.775
0.35625
0.45
0.5270833333333333

In [123]:
flights_dt_results = dt_result[dt_result['pp_id'] >= 111][dt_result['pp_id'] <=126]
stat = flights_dt_results['ratio'].describe()
for idx in ['mean', 'std',	'min',	'max',	'25%',	'50%',	'75%']:
    print(stat.loc[idx])

0.04666666666666667
0.08944271909999159
0.0
0.34
0.0
0.0
0.06833333333333333

/tmp/ipykernel_4172012/1502436861.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  flights_dt_results = dt_result[dt_result['pp_id'] >= 111][dt_result['pp_id'] <=126]

In [ ]:
ppp_dt_results = dt_result[dt_result['pp_id'] >= 62][dt_result['pp_id'] <=91]
stat = ppp_dt_results['ratio'].describe()
for idx in ['mean', 'std',	'min',	'max',	'25%',	'50%',	'75%']:
    print(stat.loc[idx])

In [ ]:
dish_dt_result =dt_result[dt_result['pp_id'] >= 92][dt_result['pp_id'] <=110]
stat = dish_dt_result['ratio'].describe()
for idx in ['mean', 'std',	'min',	'max',	'25%',	'50%',	'75%']:
    print(stat.loc[idx])

In [ ]:
chi_dt_result =dt_result[dt_result['pp_id'] >= 31][dt_result['pp_id'] <=61]
stat = chi_dt_result['ratio'].describe()
for idx in ['mean', 'std',	'min',	'max',	'25%',	'50%',	'75%']:
    print(stat.loc[idx])

In [ ]:
menu_dt_result =dt_result[dt_result['pp_id'] < 31]

stat = menu_dt_result['ratio'].describe()
for idx in ['mean', 'std',	'min',	'max',	'25%',	'50%',	'75%']:
    print(stat.loc[idx])

## table eval ttest

# answer eval

In [19]:
par_folder = '/projects/bces/lanl2/LLM4DC'
datafile_path = f'{par_folder}/evaluation/answer_1-154_gt.json'
data = []
with open(datafile_path, 'r') as f:
    for l in f:
        data.append(json.loads(l))

In [20]:
from bert_score import score

/projects/bces/lanl2/autodc/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [21]:
import json
from typing import Union, List, Dict, Any
from difflib import SequenceMatcher
from math import isclose

# Define a utility to convert JSON strings to Python objects
def parse_input(answer: Union[str, float, List, Dict]) -> Any:
    if isinstance(answer, str):
        try:
            # Try to parse JSON strings into Python objects
            return json.loads(answer)
        except json.JSONDecodeError:
            return answer.lower().strip()  # Normalize strings for comparison
    elif isinstance(answer, float):
        return round(answer, 2)  # Round floats to two decimal places if needed
    return answer  # If already in desired format

# Calculate exact match accuracy
def accuracy_metric(gt: Any, pred: Any) -> float:
    return 1.0 if gt == pred else 0.0

# Calculate precision, recall, and F1 for lists (assuming items are unique)
def precision_recall_f1(gt: List, pred: List) -> Dict[str, float]:
    gt_set, pred_set = set(gt), set(pred)
    true_positives = len(gt_set & pred_set)
    precision = true_positives / len(pred_set) if pred_set else 0
    recall = true_positives / len(gt_set) if gt_set else 0
    f1_score = 2 * precision * recall / (precision + recall) if precision + recall > 0 else 0
    return {"precision": precision, "recall": recall, "f1": f1_score}

# Calculate semantic distance for string answers using sequence matching
def semantic_similarity(gt: str, pred: str) -> float:
    return SequenceMatcher(None, gt, pred).ratio()  # Returns a ratio between 0 and 1

# Evaluate an answer based on the ground truth
def calculate_answer_metrics(gt: Any, pred: Any) -> Dict[str, float]:
    # Parse inputs
    gt, pred = parse_input(gt), parse_input(pred)
    
    # Initialize results
    results = {"accuracy": 0, "semantic_similarity": 0, "precision": 0, "recall":0, "f1":0}
    
    # Check type and apply appropriate metrics
    if isinstance(gt, float) and isinstance(pred, float):
        results["accuracy"] = 1.0 if isclose(gt, pred, rel_tol=1e-2) else 0.0  # Accuracy for floats with tolerance
        precision, recall = results["accuracy"], results["accuracy"]
        results.update({"precision": precision, "recall": recall, "f1": 2 * precision * recall / (precision + recall) if precision + recall > 0 else 0})
        # results['bertscore'] = score([f"{pred}"], [f"{gt}"], lang='en', verbose=True)
        results["semantic_similarity"] = semantic_similarity(str(gt), str(pred))
    elif isinstance(gt, int) and isinstance(pred, int):
        results["accuracy"] = 1.0 if isclose(gt, pred, rel_tol=1e-2) else 0.0  # Accuracy for floats with tolerance
        precision, recall = results["accuracy"], results["accuracy"]
        results.update({"precision": precision, "recall": recall, "f1": 2 * precision * recall / (precision + recall) if precision + recall > 0 else 0})
        # results['bertscore'] = score([f"{pred}"], [f"{gt}"], lang='en', verbose=True)
        results["semantic_similarity"] = semantic_similarity(str(gt), str(pred))


    elif isinstance(gt, str) and isinstance(pred, str):
        results["accuracy"] = accuracy_metric(gt.lower(), pred.lower())
        precision, recall = results["accuracy"], results["accuracy"]
        results.update({"precision": precision, "recall": recall, "f1": 2 * precision * recall / (precision + recall) if precision + recall > 0 else 0})
        # results['bertscore'] = score([pred], [gt], lang='en', verbose=True)
        results["semantic_similarity"] = semantic_similarity(gt, pred)

    
    elif isinstance(gt, list) and isinstance(pred, list):
        if type(gt[0]) == str:
            gt = [x.lower() for x in gt]
            if len(pred) > 0:
                if type(pred[0]) == str:
                    pred = [x.lower() for x in pred]
        metrics = precision_recall_f1(gt, pred)
        results.update(metrics)
        results["accuracy"] = accuracy_metric(gt, pred)
        # results['bertscore'] = score([f"{pred}"], [f"{gt}"], lang='en', verbose=True)
        similarity = semantic_similarity(f"{gt}", f"{pred}")
        results["semantic_similarity"] = similarity

    
    elif isinstance(gt, dict) and isinstance(pred, dict):
        gt = {key.lower(): value for key, value in gt.items()}
        pred = {key.lower(): value for key, value in pred.items()}
        gt_keys, pred_keys = list(gt.keys()), list(pred.keys())
        if type(gt[gt_keys[0]]) == dict:
            precision_recall_f1_results = []
            for k in gt_keys:
                if k in pred.keys():
                    pred_input = pred[k].values()
                else:
                    pred_input = []
                precision_recall_f1_results.append(precision_recall_f1(gt[k].values(), pred_input))
            precision = sum([x['precision'] for x in precision_recall_f1_results])/len([x['precision'] for x in precision_recall_f1_results])
            recall = sum([x['recall'] for x in precision_recall_f1_results])/len([x['recall'] for x in precision_recall_f1_results])
            f1 =sum([x['f1'] for x in precision_recall_f1_results])/len([x['f1'] for x in precision_recall_f1_results])
            results.update({'precision': precision, 'recall':recall, 'f1': f1})  # Precision/Recall on keys

        elif type(gt[gt_keys[0]]) == list:
            precision_recall_f1_results = []
            for k in gt_keys:
                if k in pred:
                    pred_input = pred[k]
                else: 
                    pred_input = []
                if type(gt[k][0]) ==str:
                    gt_input = [x.lower() for x in gt[k]]
                    if len(pred_input) > 0:
                        if type(pred_input[0]) == str:
                            pred_input = [x.lower() for x in pred_input]    
                else:
                    gt_input = gt[k]
                precision_recall_f1_results.append(precision_recall_f1(gt[k], pred_input)) 
            precision = sum([x['precision'] for x in precision_recall_f1_results])/len([x['precision'] for x in precision_recall_f1_results])
            recall = sum([x['recall'] for x in precision_recall_f1_results])/len([x['recall'] for x in precision_recall_f1_results])
            f1 =sum([x['f1'] for x in precision_recall_f1_results])/len([x['f1'] for x in precision_recall_f1_results])
            results.update({'precision': precision, 'recall':recall, 'f1': f1})  # Precision/Recall on keys
        

        results["accuracy"] = accuracy_metric(gt, pred)
        # Check semantic similarity for each key-value pair
        similarity = [semantic_similarity(str(gt[k]), str(pred.get(k, ""))) for k in gt_keys]
        results["semantic_similarity"] = sum(similarity) / len(similarity) if similarity else 0
        
        # results['bertscore'] = score([f"{pred}"], [f"{gt}"], lang='en', verbose=True)
    p, r, f1 = score([f"{pred}"], [f"{gt}"], lang='en', verbose=True)
    results.update({'bertscore_p': p.detach().cpu().tolist(),
    'bertscore_r': r.detach().cpu().tolist(),
    'bertscore_f1': f1.detach().cpu().tolist()})
    # print(results)


    return results

In [42]:
test_json = "{\"Zip\":{\"0\":96701,\"1\":96704,\"2\":96707,\"3\":96708,\"4\":96749,\"5\":96750,\"6\":96754,\"7\":96791,\"8\":96813,\"9\":96814,\"10\":96815,\"11\":96816,\"12\":96817,\"13\":96821,\"14\":96825,\"15\":96826},\"LoanCount\":{\"0\":1,\"1\":1,\"2\":4,\"3\":1,\"4\":1,\"5\":1,\"6\":1,\"7\":1,\"8\":1,\"9\":1,\"10\":1,\"11\":2,\"12\":1,\"13\":1,\"14\":1,\"15\":1}}"

In [43]:
test_json = parse_input(test_json)

In [ ]:
test_json.keys()
test_json.get('Zip').values()

In [22]:
# LLM-based history update solution
import importlib.util
import inspect
from typing import List
import requests
import json
import re
import difflib
from collections import Counter
# from spellchecker import SpellChecker
from datetime import datetime
import pandas as pd
import ast
import random
import logging 
# from history_update_problem.call_or import export_rows
from call_or import *

# from evaluation.data_compare import calculate_answer_metrics


def load_answer_dataset(datafile_path):
    """
    load json file, each line is a json dictionary

    datafile_path: str
    return: data:  list_of_dictionary
    """
    data = []
    with open(datafile_path, 'r') as f:
        for l in f:
            data.append(json.loads(l))
    return data

def eval_answers(answer_gt_path, answer_preds_llama):
    answer_gt = load_answer_dataset(answer_gt_path)
    answer_gt = pd.DataFrame(answer_gt)
    answer_preds_llama = load_answer_dataset(answer_preds_llama)
    answer_preds_llama = pd.DataFrame(answer_preds_llama)
    answer_compare = answer_gt.merge(answer_preds_llama[['pp_id', 'answer']], on='pp_id', how='left', suffixes=('_gt', '_preds'))

    results = []
    for i, row in answer_compare.iterrows():
        
        gt = row['answer_gt']
        preds = row['answer_preds']
        
        single_result = calculate_answer_metrics(gt, preds)
        
        single_result['pp_id'] = row['pp_id']
        results.append(single_result)
        # break
    return pd.DataFrame(results)

In [23]:
# @title single eexample
answer_gt_path = 'evaluation/answer_1-154_gt.json'
answer_gt = load_answer_dataset(answer_gt_path)
answer_gt = pd.DataFrame(answer_gt)
answer_dirty = 'evaluation/answer_1-154_dirty.json'
answer_dirty = load_answer_dataset(answer_dirty)
answer_dirty = pd.DataFrame(answer_dirty)
answer_preds_llama = 'evaluation/answer_1-154_llama3.1.json'
answer_preds_llama = load_answer_dataset(answer_preds_llama)
answer_preds_llama = pd.DataFrame(answer_preds_llama)
answer_compare = answer_gt.merge(answer_preds_llama[['pp_id', 'answer']], on='pp_id', how='left', suffixes=('_gt', '_preds'))
# answer_compare = answer_gt.merge(answer_dirty[['pp_id', 'answer']], on='pp_id', how='left', suffixes=('_gt', '_preds'))

results = []
for i, row in answer_compare.iterrows():
    gt = row['answer_gt']
    preds = row['answer_preds']
    single_result = calculate_answer_metrics(gt, preds)
    single_result['pp_id'] = row['pp_id']
    print(gt, type(gt))
    print(preds, type(preds))
    results.append(single_result)
    break

pd.DataFrame(results)

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:09<00:00,  9.47s/it]

computing greedy matching.

100%|██████████| 1/1 [00:02<00:00,  2.73s/it]

done in 12.44 seconds, 0.08 sentences/sec
22 <class 'int'>
22 <class 'int'>

,accuracy,semantic_similarity,precision,recall,f1,bertscore_p,bertscore_r,bertscore_f1,pp_id
0,1.0,1.0,1.0,1.0,1.0,[1.0000004768371582],[1.0000004768371582],[1.0000004768371582],1

In [24]:
# 'dirty', 
models = ['llama3.1',  'mistral', 'gemma2','deepseek-r1']
for model in models[0:3] + ['dirty']: #['mistral', 'gemma2', 'llama3.1']:
    print(model)
    answer_gt_path = '/projects/bces/lanl2/LLM4DC/evaluation/answer_1-154_gt.json'
    # answer_preds_llama = '/projects/bces/lanl2/LLM4DC/evaluation/answer_1-154_llama3.1.json'
    # model = 'gemma2'
    # model = 'dirty'
    # model = 'llama3.1'
    # model = 'mistral'
    answer_preds = f'/projects/bces/lanl2/LLM4DC/evaluation/answer_1-154_{model}.json'
    # answer_preds = f'/projects/bces/lanl2/LLM4DC/evaluation/answer_1-110_dirty.json'
    eval_answer_results = eval_answers(answer_gt_path, answer_preds)
    eval_answer_results['bertscore_p'] = eval_answer_results['bertscore_p'].apply(lambda x: sum(x)/len(x) if len(x) > 0 else None)
    eval_answer_results['bertscore_r'] = eval_answer_results['bertscore_r'].apply(lambda x: sum(x)/len(x) if len(x) > 0 else None)
    eval_answer_results['bertscore_f1'] = eval_answer_results['bertscore_f1'].apply(lambda x: sum(x)/len(x) if len(x) > 0 else None)
    eval_answer_results.to_csv(f'/projects/bces/lanl2/LLM4DC/evaluation/{model}_answer_result.csv')

llama3.1

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.45it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 681.23it/s]

done in 0.02 seconds, 48.27 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.34it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 896.22it/s]

done in 0.02 seconds, 47.40 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00,  4.16it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 49.38it/s]

done in 0.27 seconds, 3.68 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.10it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 915.99it/s]

done in 0.02 seconds, 48.38 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 79.41it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 682.89it/s]

done in 0.03 seconds, 31.11 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 76.91it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 868.93it/s]

done in 0.02 seconds, 45.81 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.59it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 897.37it/s]

done in 0.02 seconds, 48.37 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 80.23it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 851.46it/s]

done in 0.02 seconds, 43.11 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.90it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 895.84it/s]

done in 0.02 seconds, 40.69 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.19it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 910.22it/s]

done in 0.02 seconds, 46.93 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.40it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 924.06it/s]

done in 0.02 seconds, 53.25 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 79.71it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 894.69it/s]

done in 0.02 seconds, 46.68 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 41.57it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 696.15it/s]

done in 0.04 seconds, 28.42 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 75.15it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 906.68it/s]

done in 0.02 seconds, 44.86 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 70.66it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 801.82it/s]

done in 0.02 seconds, 43.87 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 65.71it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 860.55it/s]

done in 0.03 seconds, 39.06 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 67.06it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 853.54it/s]

done in 0.02 seconds, 40.23 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 81.35it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 880.42it/s]

done in 0.02 seconds, 47.82 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 70.38it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 857.56it/s]

done in 0.02 seconds, 44.53 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 18.42it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 650.38it/s]

done in 0.06 seconds, 16.02 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.11it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 890.89it/s]

done in 0.02 seconds, 54.56 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.63it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 928.77it/s]

done in 0.02 seconds, 52.87 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 31.24it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 854.76it/s]

done in 0.05 seconds, 19.47 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 46.07it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 861.78it/s]

done in 0.03 seconds, 33.79 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 81.01it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 896.79it/s]

done in 0.02 seconds, 49.38 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 39.30it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 702.33it/s]

done in 0.03 seconds, 29.26 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.61it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 938.11it/s]

done in 0.02 seconds, 51.78 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.17it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 782.96it/s]

done in 0.02 seconds, 48.09 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 84.81it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 867.67it/s]

done in 0.02 seconds, 51.23 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.93it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 897.75it/s]

done in 0.02 seconds, 51.69 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.04it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 921.83it/s]

done in 0.02 seconds, 53.85 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.93it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 900.65it/s]

done in 0.02 seconds, 49.05 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 99.61it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 922.84it/s]

done in 0.02 seconds, 56.62 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.18it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 883.20it/s]

done in 0.02 seconds, 50.02 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 101.65it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 906.29it/s]

done in 0.02 seconds, 57.91 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.35it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 907.86it/s]

done in 0.02 seconds, 49.34 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.39it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 787.37it/s]

done in 0.02 seconds, 50.64 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.72it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 907.27it/s]

done in 0.02 seconds, 55.65 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.35it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 914.99it/s]

done in 0.02 seconds, 58.78 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 56.94it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 839.53it/s]

done in 0.02 seconds, 41.49 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.17it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 921.42it/s]

done in 0.02 seconds, 57.02 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.80it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 940.22it/s]

done in 0.02 seconds, 59.81 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 58.42it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 832.86it/s]

done in 0.02 seconds, 42.04 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 100.02it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 916.99it/s]

done in 0.02 seconds, 60.13 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 100.20it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 934.56it/s]

done in 0.02 seconds, 60.50 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.63it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 884.31it/s]

done in 0.02 seconds, 44.14 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 101.53it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 941.69it/s]

done in 0.02 seconds, 61.39 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 99.04it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 926.10it/s]

done in 0.02 seconds, 60.09 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.03it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 912.20it/s]

done in 0.02 seconds, 59.36 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.81it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 802.43it/s]

done in 0.02 seconds, 59.00 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 84.87it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 726.79it/s]

done in 0.02 seconds, 50.02 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.60it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 869.47it/s]

done in 0.02 seconds, 59.29 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.14it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 883.57it/s]

done in 0.02 seconds, 54.90 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 19.26it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 819.04it/s]

done in 0.06 seconds, 17.46 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.82it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 763.99it/s]

done in 0.02 seconds, 53.78 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00,  5.36it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 13.63it/s]

done in 0.28 seconds, 3.54 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 79.81it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 757.23it/s]

done in 0.02 seconds, 52.58 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.55it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 916.99it/s]

done in 0.02 seconds, 55.54 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.63it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 916.79it/s]

done in 0.02 seconds, 55.64 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 99.30it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 936.65it/s]

done in 0.02 seconds, 60.11 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 99.63it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 925.49it/s]

done in 0.02 seconds, 59.75 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.77it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 934.35it/s]

done in 0.02 seconds, 56.53 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 100.72it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 941.91it/s]

done in 0.02 seconds, 59.43 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.49it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 882.27it/s]

done in 0.02 seconds, 54.85 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.93it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 863.74it/s]

done in 0.03 seconds, 30.56 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.66it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 943.39it/s]

done in 0.02 seconds, 60.24 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.88it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 907.27it/s]

done in 0.02 seconds, 54.32 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.96it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 952.60it/s]

done in 0.02 seconds, 55.95 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.86it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 940.85it/s]

done in 0.02 seconds, 56.51 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 104.92it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 941.27it/s]

done in 0.02 seconds, 59.98 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 59.18it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 782.08it/s]

done in 0.03 seconds, 36.04 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 39.90it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 802.43it/s]

done in 0.04 seconds, 28.43 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.96it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 931.45it/s]

done in 0.02 seconds, 59.60 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.81it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 910.82it/s]

done in 0.02 seconds, 54.80 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.86it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 946.80it/s]

done in 0.02 seconds, 53.58 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.06it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 943.39it/s]

done in 0.02 seconds, 57.77 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 100.26it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 947.44it/s]

done in 0.02 seconds, 60.44 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.30it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 919.80it/s]

done in 0.03 seconds, 31.91 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.46it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 941.91it/s]

done in 0.02 seconds, 57.36 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.29it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 942.75it/s]

done in 0.02 seconds, 50.54 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 32.39it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 790.19it/s]

done in 0.04 seconds, 26.00 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.81it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 937.69it/s]

done in 0.02 seconds, 43.67 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.59it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 947.01it/s]

done in 0.02 seconds, 60.74 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 24.30it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 746.85it/s]

done in 0.05 seconds, 20.92 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.85it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 948.51it/s]

done in 0.02 seconds, 56.38 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 99.67it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 937.69it/s]

done in 0.02 seconds, 59.71 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.40it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 936.86it/s]

done in 0.02 seconds, 59.87 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 71.42it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 892.60it/s]

done in 0.02 seconds, 48.35 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.14it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 921.62it/s]

done in 0.02 seconds, 56.75 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.14it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 931.24it/s]

done in 0.02 seconds, 56.16 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.57it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 935.60it/s]

done in 0.02 seconds, 56.51 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 44.90it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 805.20it/s]

done in 0.03 seconds, 34.65 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 29.72it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 750.73it/s]

done in 0.04 seconds, 24.46 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.53it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 892.41it/s]

done in 0.02 seconds, 55.25 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.37it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 870.55it/s]

done in 0.03 seconds, 38.12 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.34it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 933.52it/s]

done in 0.02 seconds, 56.53 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 80.74it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 883.01it/s]

done in 0.02 seconds, 53.08 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 34.74it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 764.13it/s]

done in 0.04 seconds, 24.78 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 29.38it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 835.85it/s]

done in 0.04 seconds, 24.70 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.58it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 951.09it/s]

done in 0.02 seconds, 59.65 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 99.36it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 941.27it/s]

done in 0.02 seconds, 60.11 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 51.26it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 811.43it/s]

done in 0.03 seconds, 36.73 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 35.18it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 692.02it/s]

done in 0.04 seconds, 28.54 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 56.92it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 864.45it/s]

done in 0.02 seconds, 41.91 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.77it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 921.62it/s]

done in 0.02 seconds, 55.92 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.67it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 917.99it/s]

done in 0.02 seconds, 56.34 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 28.87it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 759.56it/s]

done in 0.04 seconds, 24.22 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 68.93it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 901.03it/s]

done in 0.02 seconds, 47.83 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 59.15it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 868.93it/s]

done in 0.02 seconds, 43.05 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 72.80it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 897.37it/s]

done in 0.02 seconds, 50.06 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 58.17it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 845.28it/s]

done in 0.02 seconds, 42.44 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.16it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 926.51it/s]

done in 0.02 seconds, 56.63 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 50.75it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 825.65it/s]

done in 0.03 seconds, 38.73 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.43it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 888.25it/s]

done in 0.02 seconds, 59.84 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.48it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 944.03it/s]

done in 0.02 seconds, 59.34 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 70.89it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 858.08it/s]

done in 0.02 seconds, 48.47 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 70.31it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 865.70it/s]

done in 0.02 seconds, 44.38 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.98it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 898.33it/s]

done in 0.02 seconds, 59.34 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 58.79it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 838.02it/s]

done in 0.03 seconds, 38.99 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 104.05it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 944.45it/s]

done in 0.02 seconds, 62.18 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 100.36it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 909.24it/s]

done in 0.02 seconds, 60.86 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.55it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 906.09it/s]

done in 0.02 seconds, 58.98 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 103.73it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 941.69it/s]

done in 0.02 seconds, 61.97 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 104.46it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 939.58it/s]

done in 0.02 seconds, 62.34 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.55it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 942.12it/s]

done in 0.02 seconds, 60.34 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.73it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 902.19it/s]

done in 0.02 seconds, 56.27 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 72.54it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 838.69it/s]

done in 0.02 seconds, 49.17 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.03it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 918.39it/s]

done in 0.02 seconds, 55.45 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 33.91it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 775.43it/s]

done in 0.04 seconds, 24.34 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 99.20it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 943.39it/s]

done in 0.02 seconds, 60.26 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 44.87it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 908.84it/s]

done in 0.03 seconds, 29.44 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 101.30it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 944.24it/s]

done in 0.02 seconds, 61.70 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.66it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 954.12it/s]

done in 0.02 seconds, 60.04 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.64it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 903.36it/s]

done in 0.02 seconds, 43.18 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 104.29it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 933.31it/s]

done in 0.02 seconds, 63.18 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.45it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 929.79it/s]

done in 0.02 seconds, 59.05 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 103.99it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 949.15it/s]

done in 0.02 seconds, 57.06 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.27it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 946.58it/s]

done in 0.02 seconds, 59.94 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.61it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 903.94it/s]

done in 0.02 seconds, 55.37 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.19it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 914.59it/s]

done in 0.02 seconds, 55.47 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.13it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 840.04it/s]

done in 0.03 seconds, 29.91 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.02it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 877.65it/s]

done in 0.02 seconds, 53.99 sentences/sec
mistral

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 102.14it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 934.56it/s]

done in 0.02 seconds, 61.06 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.67it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 946.58it/s]

done in 0.02 seconds, 60.36 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 34.95it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 824.84it/s]

done in 0.04 seconds, 24.61 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.85it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 954.77it/s]

done in 0.02 seconds, 60.07 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.91it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 948.72it/s]

done in 0.02 seconds, 60.52 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.33it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 885.43it/s]

done in 0.02 seconds, 53.51 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.31it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 942.75it/s]

done in 0.02 seconds, 53.49 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 71.78it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 864.98it/s]

done in 0.02 seconds, 49.54 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.38it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 896.41it/s]

done in 0.02 seconds, 48.28 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.62it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 951.52it/s]

done in 0.02 seconds, 60.70 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 99.69it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 942.96it/s]

done in 0.02 seconds, 56.28 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.97it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 874.00it/s]

done in 0.02 seconds, 57.26 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 42.64it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 843.58it/s]

done in 0.03 seconds, 33.64 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.91it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 945.73it/s]

done in 0.02 seconds, 60.53 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 80.91it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 892.98it/s]

done in 0.02 seconds, 53.33 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 38.66it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 883.01it/s]

done in 0.04 seconds, 24.24 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 69.26it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 899.49it/s]

done in 0.02 seconds, 48.38 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.80it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 903.94it/s]

done in 0.02 seconds, 55.41 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 69.59it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 838.02it/s]

done in 0.02 seconds, 47.66 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 18.31it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 667.46it/s]

done in 0.07 seconds, 14.31 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 99.07it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 943.18it/s]

done in 0.02 seconds, 59.92 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.77it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 951.31it/s]

done in 0.02 seconds, 60.86 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.82it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 936.86it/s]

done in 0.02 seconds, 56.15 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.68it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 904.92it/s]

done in 0.02 seconds, 56.69 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.77it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 908.05it/s]

done in 0.02 seconds, 55.82 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 40.73it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 849.22it/s]

done in 0.03 seconds, 32.59 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.97it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 943.81it/s]

done in 0.02 seconds, 61.05 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.91it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 945.94it/s]

done in 0.02 seconds, 56.46 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.90it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 921.42it/s]

done in 0.02 seconds, 56.92 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 81.86it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 877.84it/s]

done in 0.02 seconds, 53.63 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 103.58it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 932.69it/s]

done in 0.02 seconds, 62.86 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.80it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 943.60it/s]

done in 0.02 seconds, 60.37 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 103.41it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 947.01it/s]

done in 0.02 seconds, 62.51 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 84.32it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 915.59it/s]

done in 0.02 seconds, 55.01 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.66it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 947.65it/s]

done in 0.02 seconds, 59.83 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.15it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 933.52it/s]

done in 0.02 seconds, 56.01 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.09it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 837.02it/s]

done in 0.02 seconds, 57.09 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.59it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 930.41it/s]

done in 0.02 seconds, 56.86 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.85it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 926.51it/s]

done in 0.02 seconds, 50.20 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 53.35it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 830.39it/s]

done in 0.03 seconds, 38.90 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.24it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 923.45it/s]

done in 0.02 seconds, 53.73 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.98it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 846.82it/s]

done in 0.04 seconds, 23.65 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 52.16it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 822.09it/s]

done in 0.03 seconds, 39.16 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.38it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 936.44it/s]

done in 0.02 seconds, 59.69 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.81it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 940.85it/s]

done in 0.02 seconds, 59.61 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.26it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 875.45it/s]

done in 0.02 seconds, 54.36 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.38it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 943.18it/s]

done in 0.02 seconds, 55.84 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.93it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 940.43it/s]

done in 0.02 seconds, 57.08 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.44it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 941.91it/s]

done in 0.02 seconds, 59.73 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.25it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 953.03it/s]

done in 0.02 seconds, 60.27 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.90it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 937.27it/s]

done in 0.02 seconds, 56.53 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.16it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 906.09it/s]

done in 0.02 seconds, 56.93 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.57it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 931.45it/s]

done in 0.02 seconds, 55.99 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 103.82it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 917.19it/s]

done in 0.02 seconds, 63.13 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.23it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 926.92it/s]

done in 0.02 seconds, 56.64 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.30it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 906.48it/s]

done in 0.02 seconds, 56.72 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.89it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 908.05it/s]

done in 0.02 seconds, 56.03 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.22it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 911.81it/s]

done in 0.02 seconds, 56.89 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.80it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 941.27it/s]

done in 0.02 seconds, 56.61 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 99.50it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 944.88it/s]

done in 0.02 seconds, 60.38 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 100.14it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 933.52it/s]

done in 0.02 seconds, 60.78 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 67.59it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 932.07it/s]

done in 0.02 seconds, 49.47 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 100.27it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 938.11it/s]

done in 0.02 seconds, 53.95 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.64it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 918.80it/s]

done in 0.02 seconds, 56.28 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.15it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 948.72it/s]

done in 0.02 seconds, 60.76 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.68it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 931.65it/s]

done in 0.02 seconds, 59.18 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 84.05it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 913.59it/s]

done in 0.02 seconds, 54.59 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.64it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 930.41it/s]

done in 0.02 seconds, 52.13 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.96it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 922.84it/s]

done in 0.02 seconds, 55.67 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.50it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 935.60it/s]

done in 0.02 seconds, 59.75 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 34.12it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 764.69it/s]

done in 0.04 seconds, 22.70 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 32.08it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 730.71it/s]

done in 0.05 seconds, 20.70 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.64it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 919.40it/s]

done in 0.02 seconds, 57.92 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.96it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 941.06it/s]

done in 0.02 seconds, 59.95 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.54it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 931.45it/s]

done in 0.02 seconds, 56.35 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.90it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 957.82it/s]

done in 0.02 seconds, 57.56 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.07it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 828.26it/s]

done in 0.02 seconds, 46.84 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.48it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 942.96it/s]

done in 0.02 seconds, 60.33 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.26it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 954.12it/s]

done in 0.02 seconds, 56.85 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.47it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 948.94it/s]

done in 0.02 seconds, 49.11 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 32.33it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 781.64it/s]

done in 0.05 seconds, 20.78 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.51it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 937.07it/s]

done in 0.02 seconds, 56.81 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 100.15it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 947.22it/s]

done in 0.02 seconds, 61.29 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 23.54it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 334.02it/s]

done in 0.05 seconds, 19.78 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.40it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 930.21it/s]

done in 0.02 seconds, 55.81 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.65it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 933.73it/s]

done in 0.02 seconds, 56.70 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.44it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 899.87it/s]

done in 0.02 seconds, 56.34 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.24it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 918.80it/s]

done in 0.02 seconds, 56.04 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.02it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 934.35it/s]

done in 0.02 seconds, 56.23 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.94it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 935.18it/s]

done in 0.02 seconds, 58.53 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.09it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 950.87it/s]

done in 0.02 seconds, 56.53 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 46.84it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 843.58it/s]

done in 0.03 seconds, 31.62 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 32.62it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 796.49it/s]

done in 0.05 seconds, 21.62 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.59it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 955.64it/s]

done in 0.02 seconds, 57.80 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.68it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 928.97it/s]

done in 0.02 seconds, 53.87 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.34it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 945.51it/s]

done in 0.02 seconds, 57.97 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 81.25it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 883.01it/s]

done in 0.02 seconds, 53.26 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 34.55it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 794.53it/s]

done in 0.04 seconds, 27.99 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 32.76it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 774.86it/s]

done in 0.04 seconds, 27.15 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.31it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 941.48it/s]

done in 0.02 seconds, 60.79 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.24it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 939.58it/s]

done in 0.02 seconds, 61.99 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 45.32it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 819.52it/s]

done in 0.03 seconds, 35.58 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 17.49it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 638.11it/s]

done in 0.06 seconds, 15.63 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 57.69it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 873.09it/s]

done in 0.02 seconds, 44.68 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.30it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 923.45it/s]

done in 0.02 seconds, 56.81 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.43it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 912.80it/s]

done in 0.02 seconds, 56.94 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 32.79it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 773.57it/s]

done in 0.05 seconds, 21.54 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 70.02it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 909.83it/s]

done in 0.02 seconds, 48.98 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 60.54it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 903.36it/s]

done in 0.02 seconds, 44.18 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 73.37it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 864.45it/s]

done in 0.02 seconds, 50.07 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 59.88it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 914.59it/s]

done in 0.02 seconds, 44.14 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.92it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 935.60it/s]

done in 0.02 seconds, 57.75 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 55.19it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 888.62it/s]

done in 0.02 seconds, 41.59 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.07it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 901.03it/s]

done in 0.02 seconds, 56.82 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.26it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 945.73it/s]

done in 0.02 seconds, 60.36 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 68.89it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 809.40it/s]

done in 0.02 seconds, 48.02 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 73.64it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 852.50it/s]

done in 0.02 seconds, 50.54 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.52it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 906.48it/s]

done in 0.02 seconds, 59.15 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 57.09it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 836.02it/s]

done in 0.02 seconds, 41.96 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.97it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 951.52it/s]

done in 0.02 seconds, 61.21 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.83it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 944.88it/s]

done in 0.02 seconds, 51.29 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.75it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 913.00it/s]

done in 0.02 seconds, 56.50 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.10it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 942.96it/s]

done in 0.03 seconds, 31.85 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 103.75it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 945.94it/s]

done in 0.02 seconds, 63.23 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.42it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 942.96it/s]

done in 0.02 seconds, 60.67 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.33it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 924.26it/s]

done in 0.02 seconds, 56.17 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 72.62it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 849.22it/s]

done in 0.02 seconds, 48.94 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.33it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 902.39it/s]

done in 0.02 seconds, 56.61 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 31.86it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 750.99it/s]

done in 0.05 seconds, 21.01 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 99.50it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 936.44it/s]

done in 0.02 seconds, 61.15 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.24it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 914.59it/s]

done in 0.02 seconds, 60.27 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 99.01it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 941.48it/s]

done in 0.02 seconds, 61.66 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.64it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 951.52it/s]

done in 0.02 seconds, 60.76 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.28it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 866.59it/s]

done in 0.02 seconds, 46.73 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 99.31it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 944.45it/s]

done in 0.02 seconds, 61.36 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.46it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 944.03it/s]

done in 0.02 seconds, 57.03 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.95it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 949.37it/s]

done in 0.02 seconds, 61.30 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.86it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 945.09it/s]

done in 0.02 seconds, 61.29 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.88it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 928.97it/s]

done in 0.02 seconds, 57.35 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.29it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 909.83it/s]

done in 0.02 seconds, 57.18 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.80it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 893.55it/s]

done in 0.02 seconds, 56.46 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 51.99it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 857.56it/s]

done in 0.03 seconds, 39.75 sentences/sec
gemma2

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 104.05it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 943.18it/s]

done in 0.02 seconds, 63.27 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 102.42it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 951.52it/s]

done in 0.02 seconds, 62.96 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 38.55it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 816.49it/s]

done in 0.03 seconds, 31.20 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 103.39it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 935.60it/s]

done in 0.02 seconds, 62.42 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.70it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 936.86it/s]

done in 0.02 seconds, 57.87 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.45it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 904.33it/s]

done in 0.02 seconds, 58.10 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 101.24it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 942.75it/s]

done in 0.02 seconds, 63.14 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 81.58it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 886.93it/s]

done in 0.02 seconds, 54.15 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.90it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 944.66it/s]

done in 0.02 seconds, 60.49 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.81it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 948.72it/s]

done in 0.02 seconds, 60.44 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 100.18it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 942.75it/s]

done in 0.02 seconds, 61.81 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.63it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 904.33it/s]

done in 0.02 seconds, 59.04 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 41.73it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 800.90it/s]

done in 0.03 seconds, 32.89 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.24it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 943.60it/s]

done in 0.02 seconds, 61.08 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 80.40it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 869.65it/s]

done in 0.02 seconds, 53.04 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.61it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 905.90it/s]

done in 0.02 seconds, 56.37 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 68.65it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 855.63it/s]

done in 0.02 seconds, 48.42 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.42it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 893.93it/s]

done in 0.02 seconds, 56.78 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 70.48it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 849.05it/s]

done in 0.02 seconds, 48.72 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 18.66it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 660.21it/s]

done in 0.06 seconds, 16.56 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.82it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 916.19it/s]

done in 0.02 seconds, 43.07 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.69it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 949.15it/s]

done in 0.02 seconds, 61.17 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.84it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 924.67it/s]

done in 0.02 seconds, 56.92 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.20it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 919.80it/s]

done in 0.02 seconds, 55.75 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.09it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 924.47it/s]

done in 0.02 seconds, 57.46 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 39.48it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 793.62it/s]

done in 0.03 seconds, 31.72 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.82it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 947.01it/s]

done in 0.02 seconds, 61.02 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.66it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 950.87it/s]

done in 0.02 seconds, 56.99 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.93it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 931.86it/s]

done in 0.02 seconds, 56.62 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.18it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 907.86it/s]

done in 0.02 seconds, 59.89 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 102.62it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 944.66it/s]

done in 0.02 seconds, 62.44 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.76it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 880.97it/s]

done in 0.02 seconds, 60.14 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 103.29it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 947.44it/s]

done in 0.03 seconds, 35.58 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.52it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 916.79it/s]

done in 0.02 seconds, 55.96 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 104.93it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 948.51it/s]

done in 0.02 seconds, 63.71 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.25it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 933.31it/s]

done in 0.02 seconds, 61.95 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.52it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 943.60it/s]

done in 0.02 seconds, 61.54 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.14it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 918.39it/s]

done in 0.02 seconds, 56.83 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.23it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 934.77it/s]

done in 0.02 seconds, 57.70 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 53.30it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 834.52it/s]

done in 0.03 seconds, 39.95 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.40it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 905.51it/s]

done in 0.02 seconds, 57.24 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.88it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 947.87it/s]

done in 0.02 seconds, 61.25 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 56.87it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 851.12it/s]

done in 0.02 seconds, 41.86 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 99.95it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 934.35it/s]

done in 0.02 seconds, 61.91 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 100.14it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 942.96it/s]

done in 0.02 seconds, 61.50 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.22it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 911.81it/s]

done in 0.02 seconds, 60.67 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 99.17it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 891.08it/s]

done in 0.02 seconds, 60.27 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.67it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 949.80it/s]

done in 0.02 seconds, 61.07 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.11it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 948.08it/s]

done in 0.02 seconds, 61.02 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 103.26it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 949.58it/s]

done in 0.02 seconds, 62.69 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.49it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 938.11it/s]

done in 0.02 seconds, 57.01 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.62it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 913.39it/s]

done in 0.02 seconds, 60.90 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.79it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 945.51it/s]

done in 0.02 seconds, 57.01 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 102.00it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 943.18it/s]

done in 0.02 seconds, 62.77 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.70it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 943.18it/s]

done in 0.02 seconds, 56.85 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.04it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 906.68it/s]

done in 0.02 seconds, 56.45 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.85it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 895.26it/s]

done in 0.02 seconds, 59.38 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.26it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 939.79it/s]

done in 0.02 seconds, 57.69 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.91it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 944.66it/s]

done in 0.02 seconds, 56.67 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 99.26it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 942.33it/s]

done in 0.02 seconds, 61.52 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 99.85it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 934.56it/s]

done in 0.02 seconds, 61.05 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.84it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 942.75it/s]

done in 0.02 seconds, 61.12 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 100.81it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 944.45it/s]

done in 0.02 seconds, 61.87 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.51it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 881.53it/s]

done in 0.02 seconds, 56.36 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 99.61it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 932.90it/s]

done in 0.02 seconds, 55.11 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.37it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 941.91it/s]

done in 0.02 seconds, 60.21 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.41it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 879.49it/s]

done in 0.02 seconds, 54.23 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.55it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 937.48it/s]

done in 0.02 seconds, 52.47 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.09it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 909.24it/s]

done in 0.02 seconds, 56.86 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 104.27it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 944.88it/s]

done in 0.02 seconds, 63.34 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 58.55it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 798.92it/s]

done in 0.02 seconds, 40.38 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 57.50it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 770.87it/s]

done in 0.02 seconds, 42.02 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.73it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 933.94it/s]

done in 0.02 seconds, 60.32 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.17it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 930.00it/s]

done in 0.02 seconds, 57.65 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 100.49it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 942.96it/s]

done in 0.02 seconds, 55.84 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 99.29it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 916.59it/s]

done in 0.02 seconds, 40.97 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.54it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 943.81it/s]

done in 0.02 seconds, 61.46 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 100.36it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 927.53it/s]

done in 0.02 seconds, 62.09 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.52it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 948.94it/s]

done in 0.02 seconds, 57.28 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 102.84it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 938.74it/s]

done in 0.02 seconds, 62.31 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 35.98it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 776.72it/s]

done in 0.03 seconds, 29.42 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.02it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 911.21it/s]

done in 0.02 seconds, 60.35 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 99.36it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 941.48it/s]

done in 0.02 seconds, 61.17 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 24.76it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 737.14it/s]

done in 0.06 seconds, 16.48 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.88it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 944.24it/s]

done in 0.02 seconds, 56.21 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.80it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 944.24it/s]

done in 0.02 seconds, 60.64 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.47it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 935.39it/s]

done in 0.02 seconds, 59.93 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.62it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 934.56it/s]

done in 0.02 seconds, 57.16 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.40it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 911.21it/s]

done in 0.02 seconds, 60.73 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 99.10it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 940.64it/s]

done in 0.02 seconds, 61.80 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.99it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 915.59it/s]

done in 0.02 seconds, 57.69 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 46.36it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 810.65it/s]

done in 0.03 seconds, 35.88 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 22.89it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 757.50it/s]

done in 0.05 seconds, 20.29 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.68it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 937.69it/s]

done in 0.02 seconds, 60.77 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.82it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 925.89it/s]

done in 0.02 seconds, 59.90 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.16it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 941.06it/s]

done in 0.02 seconds, 59.77 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.22it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 919.80it/s]

done in 0.02 seconds, 55.40 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 34.79it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 792.87it/s]

done in 0.04 seconds, 24.16 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 32.77it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 798.46it/s]

done in 0.04 seconds, 27.38 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.88it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 936.65it/s]

done in 0.02 seconds, 60.28 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.50it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 931.86it/s]

done in 0.02 seconds, 61.09 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 51.96it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 846.14it/s]

done in 0.03 seconds, 39.49 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 35.47it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 704.93it/s]

done in 0.03 seconds, 28.79 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 56.74it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 833.36it/s]

done in 0.03 seconds, 34.81 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.13it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 917.99it/s]

done in 0.02 seconds, 56.56 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.39it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 931.24it/s]

done in 0.02 seconds, 57.80 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 32.78it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 780.34it/s]

done in 0.04 seconds, 26.79 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 59.82it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 905.90it/s]

done in 0.02 seconds, 43.68 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 59.44it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 885.62it/s]

done in 0.02 seconds, 43.54 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 73.24it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 895.64it/s]

done in 0.02 seconds, 50.38 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 58.69it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 856.50it/s]

done in 0.02 seconds, 43.35 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.87it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 929.38it/s]

done in 0.02 seconds, 56.44 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 53.94it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 853.02it/s]

done in 0.02 seconds, 40.52 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 69.02it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 832.86it/s]

done in 0.02 seconds, 47.94 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.85it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 943.81it/s]

done in 0.02 seconds, 60.67 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.51it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 858.08it/s]

done in 0.02 seconds, 55.14 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.03it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 869.83it/s]

done in 0.02 seconds, 59.49 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.32it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 914.99it/s]

done in 0.02 seconds, 59.12 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 59.13it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 807.22it/s]

done in 0.02 seconds, 43.24 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 103.62it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 947.87it/s]

done in 0.02 seconds, 62.94 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 99.41it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 923.65it/s]

done in 0.02 seconds, 61.40 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.44it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 929.79it/s]

done in 0.04 seconds, 27.75 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.82it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 947.22it/s]

done in 0.02 seconds, 60.62 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 102.31it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 940.85it/s]

done in 0.02 seconds, 63.15 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.38it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 947.65it/s]

done in 0.02 seconds, 60.97 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.04it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 908.05it/s]

done in 0.02 seconds, 60.93 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 71.49it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 869.83it/s]

done in 0.02 seconds, 49.87 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.37it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 908.25it/s]

done in 0.02 seconds, 56.51 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 40.02it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 766.50it/s]

done in 0.03 seconds, 31.87 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.83it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 948.08it/s]

done in 0.02 seconds, 61.22 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 101.91it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 351.43it/s]

done in 0.02 seconds, 54.75 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.78it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 857.73it/s]

done in 0.05 seconds, 20.78 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 104.26it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 946.58it/s]

done in 0.02 seconds, 62.94 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.87it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 943.81it/s]

done in 0.02 seconds, 60.02 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 104.28it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 951.74it/s]

done in 0.02 seconds, 63.25 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.23it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 951.09it/s]

done in 0.02 seconds, 61.70 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.27it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 948.72it/s]

done in 0.02 seconds, 60.22 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 103.47it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 937.48it/s]

done in 0.02 seconds, 46.69 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.01it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 935.18it/s]

done in 0.02 seconds, 56.34 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.17it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 892.41it/s]

done in 0.02 seconds, 55.86 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.59it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 919.60it/s]

done in 0.02 seconds, 56.36 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.59it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 883.94it/s]

done in 0.02 seconds, 59.19 sentences/sec
dirty

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 102.90it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 946.37it/s]

done in 0.02 seconds, 62.02 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 103.58it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 933.73it/s]

done in 0.02 seconds, 63.05 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 35.02it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 843.25it/s]

done in 0.03 seconds, 28.80 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.57it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 946.15it/s]

done in 0.02 seconds, 60.57 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.05it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 945.51it/s]

done in 0.02 seconds, 60.79 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.22it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 905.31it/s]

done in 0.02 seconds, 55.52 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.04it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 946.58it/s]

done in 0.02 seconds, 61.01 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 73.56it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 882.45it/s]

done in 0.02 seconds, 50.61 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 100.20it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 950.01it/s]

done in 0.02 seconds, 61.87 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.81it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 901.81it/s]

done in 0.02 seconds, 60.30 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.53it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 935.81it/s]

done in 0.02 seconds, 60.95 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.12it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 909.04it/s]

done in 0.02 seconds, 59.77 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 42.89it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 828.75it/s]

done in 0.03 seconds, 33.99 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.07it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 928.56it/s]

done in 0.02 seconds, 60.44 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 81.61it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 913.79it/s]

done in 0.02 seconds, 54.44 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.04it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 925.89it/s]

done in 0.02 seconds, 56.96 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 70.09it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 891.27it/s]

done in 0.02 seconds, 48.95 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.33it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 930.21it/s]

done in 0.02 seconds, 56.54 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 70.34it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 871.82it/s]

done in 0.02 seconds, 48.93 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 17.55it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 654.24it/s]

done in 0.06 seconds, 15.80 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.25it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 942.33it/s]

done in 0.02 seconds, 60.97 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.97it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 947.87it/s]

done in 0.02 seconds, 60.93 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.43it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 908.25it/s]

done in 0.03 seconds, 35.31 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 84.17it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 909.83it/s]

done in 0.02 seconds, 55.20 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.48it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 918.59it/s]

done in 0.02 seconds, 58.24 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 39.91it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 799.68it/s]

done in 0.03 seconds, 32.02 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.87it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 947.87it/s]

done in 0.02 seconds, 60.66 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.20it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 949.37it/s]

done in 0.02 seconds, 56.77 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.73it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 928.35it/s]

done in 0.02 seconds, 57.57 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.21it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 890.32it/s]

done in 0.02 seconds, 56.73 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.80it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 938.74it/s]

done in 0.02 seconds, 60.69 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.81it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 942.75it/s]

done in 0.02 seconds, 60.35 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 102.12it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 942.12it/s]

done in 0.02 seconds, 62.65 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.08it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 885.25it/s]

done in 0.02 seconds, 54.18 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.46it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 946.58it/s]

done in 0.02 seconds, 61.22 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.12it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 953.03it/s]

done in 0.02 seconds, 57.25 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.44it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 940.01it/s]

done in 0.02 seconds, 59.78 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.70it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 942.54it/s]

done in 0.02 seconds, 56.75 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.53it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 912.00it/s]

done in 0.02 seconds, 60.41 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 39.79it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 803.51it/s]

done in 0.03 seconds, 32.00 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.13it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 900.26it/s]

done in 0.02 seconds, 54.59 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.47it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 946.15it/s]

done in 0.02 seconds, 60.69 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 36.79it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 813.01it/s]

done in 0.04 seconds, 24.67 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.74it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 941.69it/s]

done in 0.02 seconds, 60.68 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.79it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 942.75it/s]

done in 0.02 seconds, 60.40 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 71.91it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 878.39it/s]

done in 0.02 seconds, 50.27 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.56it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 953.68it/s]

done in 0.02 seconds, 57.62 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 99.60it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 933.52it/s]

done in 0.02 seconds, 51.49 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.30it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 948.08it/s]

done in 0.02 seconds, 61.35 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.56it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 920.01it/s]

done in 0.02 seconds, 61.15 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.37it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 918.80it/s]

done in 0.02 seconds, 59.25 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.27it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 913.39it/s]

done in 0.02 seconds, 51.72 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.57it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 925.69it/s]

done in 0.02 seconds, 56.79 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 103.55it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 945.09it/s]

done in 0.02 seconds, 63.17 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 72.49it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 892.03it/s]

done in 0.02 seconds, 50.17 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.23it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 917.19it/s]

done in 0.02 seconds, 56.76 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.69it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 909.24it/s]

done in 0.02 seconds, 56.51 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.65it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 920.81it/s]

done in 0.02 seconds, 56.82 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.67it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 930.00it/s]

done in 0.02 seconds, 57.41 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.93it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 935.39it/s]

done in 0.02 seconds, 59.72 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.79it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 941.69it/s]

done in 0.02 seconds, 61.25 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 99.28it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 940.85it/s]

done in 0.02 seconds, 61.47 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 100.16it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 942.33it/s]

done in 0.02 seconds, 61.70 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.86it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 925.28it/s]

done in 0.02 seconds, 57.15 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.35it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 932.90it/s]

done in 0.02 seconds, 60.98 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.59it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 944.03it/s]

done in 0.02 seconds, 61.25 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 56.37it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 868.39it/s]

done in 0.02 seconds, 42.32 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.54it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 940.43it/s]

done in 0.02 seconds, 57.28 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.41it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 881.90it/s]

done in 0.02 seconds, 55.11 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.99it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 943.39it/s]

done in 0.02 seconds, 61.53 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 32.61it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 768.75it/s]

done in 0.04 seconds, 22.89 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 32.02it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 763.85it/s]

done in 0.04 seconds, 26.76 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.26it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 946.37it/s]

done in 0.02 seconds, 59.59 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.41it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 918.80it/s]

done in 0.02 seconds, 57.01 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.67it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 957.60it/s]

done in 0.02 seconds, 57.77 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.10it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 950.44it/s]

done in 0.02 seconds, 57.17 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.33it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 959.36it/s]

done in 0.02 seconds, 57.71 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.84it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 945.30it/s]

done in 0.02 seconds, 59.44 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.17it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 941.69it/s]

done in 0.02 seconds, 57.58 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.67it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 960.67it/s]

done in 0.02 seconds, 58.12 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 27.07it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 763.02it/s]

done in 0.06 seconds, 17.34 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.98it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 947.44it/s]

done in 0.02 seconds, 57.34 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.77it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 936.23it/s]

done in 0.02 seconds, 61.78 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 25.16it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 773.14it/s]

done in 0.06 seconds, 16.55 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.30it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 929.38it/s]

done in 0.02 seconds, 57.39 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.46it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 952.17it/s]

done in 0.02 seconds, 56.99 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.11it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 939.79it/s]

done in 0.02 seconds, 57.47 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.58it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 777.59it/s]

done in 0.03 seconds, 36.50 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.87it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 922.84it/s]

done in 0.02 seconds, 46.66 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.72it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 946.15it/s]

done in 0.02 seconds, 52.43 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.42it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 942.96it/s]

done in 0.02 seconds, 52.77 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 44.61it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 814.59it/s]

done in 0.03 seconds, 33.26 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 30.72it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 734.30it/s]

done in 0.06 seconds, 17.48 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.82it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 934.35it/s]

done in 0.02 seconds, 53.12 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.81it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 902.00it/s]

done in 0.02 seconds, 49.76 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.49it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 940.85it/s]

done in 0.02 seconds, 50.87 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 75.51it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 848.71it/s]

done in 0.03 seconds, 31.73 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 34.08it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 767.06it/s]

done in 0.04 seconds, 26.22 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 33.25it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 836.02it/s]

done in 0.04 seconds, 26.13 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.19it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 930.83it/s]

done in 0.02 seconds, 47.82 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 81.70it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 920.21it/s]

done in 0.02 seconds, 42.84 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 30.55it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 757.09it/s]

done in 0.04 seconds, 23.91 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 15.20it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 60.22it/s]

done in 0.10 seconds, 10.38 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 57.36it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 839.20it/s]

done in 0.03 seconds, 36.40 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.63it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 915.59it/s]

done in 0.02 seconds, 49.11 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 72.11it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 911.41it/s]

done in 0.02 seconds, 43.92 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 32.13it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 775.14it/s]

done in 0.04 seconds, 26.06 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 66.87it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 911.41it/s]

done in 0.02 seconds, 43.69 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 60.46it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 903.17it/s]

done in 0.02 seconds, 40.60 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 20.80it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 654.13it/s]

done in 0.10 seconds, 10.26 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 58.62it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 879.31it/s]

done in 0.03 seconds, 35.83 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 54.25it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 897.75it/s]

done in 0.03 seconds, 35.52 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 51.61it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 788.40it/s]

done in 0.03 seconds, 29.66 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.50it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 880.97it/s]

done in 0.02 seconds, 46.05 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.88it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 687.82it/s]

done in 0.02 seconds, 49.05 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 56.33it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 843.58it/s]

done in 0.03 seconds, 29.80 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 57.54it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 834.02it/s]

done in 0.03 seconds, 39.28 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 80.00it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 909.63it/s]

done in 0.02 seconds, 46.83 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 52.12it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 830.72it/s]

done in 0.03 seconds, 35.81 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.49it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 936.23it/s]

done in 0.02 seconds, 52.48 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.76it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 938.11it/s]

done in 0.02 seconds, 51.42 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 74.07it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 824.35it/s]

done in 0.06 seconds, 17.65 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.57it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 933.52it/s]

done in 0.02 seconds, 56.13 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.59it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 949.80it/s]

done in 0.02 seconds, 60.93 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.38it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 944.03it/s]

done in 0.02 seconds, 60.90 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.04it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 905.90it/s]

done in 0.02 seconds, 56.86 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 72.53it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 869.47it/s]

done in 0.02 seconds, 50.10 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.84it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 916.79it/s]

done in 0.02 seconds, 59.96 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 31.55it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 748.58it/s]

done in 0.04 seconds, 26.36 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.30it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 945.30it/s]

done in 0.02 seconds, 58.09 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.18it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 949.37it/s]

done in 0.02 seconds, 61.13 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.86it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 935.18it/s]

done in 0.02 seconds, 60.89 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.33it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 939.16it/s]

done in 0.02 seconds, 61.70 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.43it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 912.80it/s]

done in 0.02 seconds, 56.43 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.13it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 949.58it/s]

done in 0.02 seconds, 61.22 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.20it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 946.15it/s]

done in 0.02 seconds, 60.59 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.33it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 938.32it/s]

done in 0.02 seconds, 61.76 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.41it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 950.44it/s]

done in 0.02 seconds, 59.92 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.00it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 928.97it/s]

done in 0.02 seconds, 57.63 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.07it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 898.91it/s]

done in 0.02 seconds, 56.57 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.15it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 904.72it/s]

done in 0.02 seconds, 56.88 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 52.48it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 849.22it/s]

done in 0.03 seconds, 39.88 sentences/sec

In [25]:
def calculate_eval_stats(eval_answer_results_text):

    total_stat_table = eval_answer_results_text.describe().loc['mean']
    eval_answer_results_text.set_index('pp_id', inplace=True)

    hos_results = eval_answer_results_text.loc[127:155]
    hos_stat_table = hos_results.describe().loc['mean']
    # print('hos', hos_stat_table)

    flights_results = eval_answer_results_text.loc[111:127]
    flights_stat_table = flights_results.describe().loc['mean']

    ppp_results = eval_answer_results_text.loc[62:92] #[eval_answer_results_text['pp_id'] >= 62][eval_answer_results_text['pp_id'] <=91]
    ppp_stat_table = ppp_results.describe().loc['mean']

    dish_results = eval_answer_results_text.loc[92:111] #[eval_answer_results_text['pp_id'] >= 92]
    dish_stat_table = dish_results.describe().loc['mean']
    
    menu_results = eval_answer_results_text.loc[:31] #[eval_answer_results_text['pp_id'] < 31]
    menu_stat_table = menu_results.describe().loc['mean']

    chi_results = eval_answer_results_text.loc[31:62] #[eval_answer_results_text['pp_id'] >= 31][eval_answer_results_text['pp_id'] <=61]
    chi_stat_table = chi_results.describe().loc['mean']


    final_result = pd.concat([total_stat_table, menu_stat_table, dish_stat_table, chi_stat_table, ppp_stat_table, hos_stat_table, flights_stat_table], axis=1)
    final_result = final_result.transpose()
    final_result['data'] = ['Total', 'Menu', 'Dish', 'CFI','PPP', 'Hospital', 'Flights' ]
    return final_result

In [26]:
total_stat_df = []
for model in models[:3] + ['dirty']: #, 'llama3.1', 'mistral', 'gemma2']:
    eval_answer_results = pd.read_csv(f'/projects/bces/lanl2/LLM4DC/evaluation/{model}_answer_result.csv')
    # evaL_answer_results_flag = eval_answer_results.merge(numeric_pp_tag, on='pp_id', how='left', suffixes=('', '_numeric'))
    # eval_answer_results_text = evaL_answer_results_flag[evaL_answer_results_flag['flag'] == 0]
    final_stat = calculate_eval_stats(eval_answer_results)
    final_stat['model'] = [model] * 7
    total_stat_df.append(final_stat)
total_stat_df = pd.concat(total_stat_df, axis=0)
total_stat_df = total_stat_df.reset_index()
total_stat_df.iloc[:,2:]

,accuracy,semantic_similarity,precision,recall,f1,bertscore_p,bertscore_r,bertscore_f1,pp_id,data,model
0,0.330986,0.686776,0.541453,0.518520,0.518067,0.951160,0.947990,0.949086,76.739437,Total,llama3.1
1,0.161290,0.562231,0.468789,0.464576,0.440761,0.957313,0.953228,0.954823,NaN,Menu,llama3.1
2,0.176471,0.677873,0.326891,0.299241,0.307843,0.888416,0.891969,0.889020,NaN,Dish,llama3.1
3,0.483871,0.770539,0.644355,0.668011,0.648361,0.975466,0.973030,0.974068,NaN,CFI,llama3.1
4,0.434783,0.713796,0.581239,0.533191,0.544857,0.933808,0.942958,0.937943,NaN,PPP,llama3.1
5,0.464286,0.784934,0.575893,0.553231,0.562249,0.986844,0.987402,0.987100,NaN,Hospital,llama3.1
6,0.176471,0.516881,0.548722,0.451691,0.487928,0.925927,0.883383,0.902786,NaN,Flights,llama3.1
7,0.140845,0.520791,0.363483,0.332002,0.331993,0.928183,0.920597,0.923596,76.739437,Total,mistral
8,0.225806,0.543752,0.500047,0.494348,0.463196,0.949282,0.938244,0.942889,NaN,Menu,mistral
9,0.058824,0.548205,0.205882,0.171123,0.181214,0.863060,0.845170,0.852869,NaN,Dish,mistral
10,0.193548,0.571991,0.388441,0.344086,0.349644,0.940342,0.936550,0.937746,NaN,CFI,mistral
11,0.260870,0.538659,0.318150,0.322464,0.319089,0.902713,0.907679,0.904471,NaN,PPP,mistral
12,0.071429,0.475023,0.263355,0.265578,0.260621,0.961681,0.968095,0.964646,NaN,Hospital,mistral
13,0.058824,0.488468,0.581176,0.399997,0.459328,0.930888,0.893962,0.911280,NaN,Flights,mistral
14,0.450704,0.756679,0.659033,0.623376,0.625631,0.968139,0.962304,0.964921,76.739437,Total,gemma2
15,0.322581,0.684945,0.661992,0.621326,0.616747,0.968793,0.961424,0.964616,NaN,Menu,gemma2
16,0.411765,0.777351,0.664706,0.597688,0.617816,0.957211,0.935868,0.945996,NaN,Dish,gemma2
17,0.548387,0.799194,0.691052,0.736559,0.702568,0.969999,0.973017,0.971341,NaN,CFI,gemma2
18,0.652174,0.864741,0.737319,0.725932,0.727295,0.971398,0.969477,0.970361,NaN,PPP,gemma2
19,0.571429,0.825780,0.575000,0.572253,0.573571,0.987669,0.991792,0.989626,NaN,Hospital,gemma2
20,0.117647,0.539011,0.663529,0.409047,0.484164,0.945104,0.920229,0.932169,NaN,Flights,gemma2
21,0.112676,0.467803,0.234462,0.237455,0.220112,0.910315,0.916395,0.912394,76.739437,Total,dirty
22,0.193548,0.497306,0.417171,0.435327,0.385137,0.944113,0.940563,0.941702,NaN,Menu,dirty
23,0.058824,0.677156,0.147059,0.147059,0.147059,0.867803,0.878188,0.871375,NaN,Dish,dirty
24,0.161290,0.496739,0.251075,0.255376,0.231797,0.913808,0.929999,0.920975,NaN,CFI,dirty
25,0.260870,0.533461,0.331815,0.333204,0.330923,0.896283,0.916411,0.905723,NaN,PPP,dirty
26,0.000000,0.349840,0.104480,0.114181,0.105621,0.943071,0.959725,0.951070,NaN,Hospital,dirty
27,0.000000,0.266811,0.089461,0.055651,0.062489,0.864748,0.816328,0.837632,NaN,Flights,dirty

In [27]:
total_stat_df.to_csv('answer_performance_table_llama_gemma_mistral.csv', header=True, index=False)

## numeric tags

In [28]:
numeric_pp_tag = pd.read_csv('/projects/bces/lanl2/LLM4DC/evaluation/purposes_category.csv')
numeric_pp_tag.columns = ['pp_id', 'purposes', 'flag']

In [29]:
evaL_answer_results_flag = eval_answer_results.merge(numeric_pp_tag, on='pp_id', how='left', suffixes=('', '_numeric'))

In [30]:
eval_answer_results_text = evaL_answer_results_flag[evaL_answer_results_flag['flag'] == 0]

In [31]:
def eval_answers_numeric(answer_gt_path, answer_preds_llama):
    answer_gt = load_answer_dataset(answer_gt_path)
    answer_gt = pd.DataFrame(answer_gt)
    answer_preds_llama = load_answer_dataset(answer_preds_llama)
    answer_preds_llama = pd.DataFrame(answer_preds_llama)
    answer_compare = answer_gt.merge(answer_preds_llama[['pp_id', 'answer']], on='pp_id', how='left', suffixes=('_gt', '_preds'))
    answer_compare = answer_compare.merge(numeric_pp_tag, on='pp_id', how='left', suffixes=('', '_numeric'))
    answer_compare = answer_compare[answer_compare['flag'] == 1]
    answer_compare['answer_preds'] = pd.to_numeric(answer_compare['answer_preds'], errors='coerce')
    answer_compare['answer_gt'] = pd.to_numeric(answer_compare['answer_gt'], errors='coerce')
    answer_compare['difference'] = (answer_compare['answer_preds'] - answer_compare['answer_gt']).abs()/answer_compare['answer_gt']
    return answer_compare

In [32]:
total_stat_df = []
for model in ['dirty', 'mistral', 'gemma2', 'llama3.1']:
    answer_gt_path = '/projects/bces/lanl2/LLM4DC/evaluation/answer_1-154_gt.json'
    # answer_preds_llama = '/projects/bces/lanl2/LLM4DC/evaluation/answer_1-110_llama3.1.json'
    # model = 'gemma2'
    # model = 'dirty'
    # model = 'llama3.1'
    # model = 'mistral'
    answer_preds = f'/projects/bces/lanl2/LLM4DC/evaluation/answer_1-154_{model}.json'
    # answer_preds = f'/projects/bces/lanl2/LLM4DC/evaluation/answer_1-110_dirty.json'
    eval_answer_results = eval_answers_numeric(answer_gt_path, answer_preds)
    # eval_answer_results.to_csv(f'evaluation/numeric_answer_diff_{model}.csv')
    final_stat = calculate_eval_stats(eval_answer_results[['difference', 'pp_id']])
    final_stat['model'] = [model] * 7
    total_stat_df.append(final_stat)

In [33]:
total_stat_df = pd.concat(total_stat_df, axis=0)

In [34]:
total_stat_df.to_csv('numeric_answer_stats_llamma_mistral_gemma.csv')

In [37]:
dish_results = eval_answer_results_text[eval_answer_results_text['pp_id'] >= 92]
dish_stat_table = dish_results.describe().loc['mean']

In [ ]:
dish_stat_table

In [35]:
eval_answer_results.describe()

            pp_id      answer_gt   answer_preds  flag  difference
count   43.000000      42.000000      42.000000  43.0   42.000000
mean    72.930233    8952.837674    8950.704340   1.0    0.177162
std     52.827840   29816.599232   29817.489095   0.0    0.300400
min      1.000000       0.700000       0.000000   1.0    0.000000
25%     29.000000       3.000000       2.000000   1.0    0.000000
50%     63.000000       9.000000      10.500000   1.0    0.000000
75%    132.500000      75.200000      43.000000   1.0    0.229167
max    150.000000  140400.000000  140400.000000   1.0    1.000000

In [ ]:
ppp_results = eval_answer_results[eval_answer_results['pp_id'] >= 62][eval_answer_results['pp_id'] <=91]

In [38]:
dish_results = eval_answer_results[eval_answer_results['pp_id'] >= 92]

In [ ]:
chi_results = eval_answer_results[eval_answer_results['pp_id'] >= 31][eval_answer_results['pp_id'] <=61]

In [66]:
menu_results = eval_answer_results[eval_answer_results['pp_id'] < 31]

In [ ]:
ppp_results.describe()

In [ ]:
dish_results.describe()

In [ ]:
menu_results.describe()

In [ ]:
chi_results.describe()

In [34]:
eval_answer_results = pd.DataFrame(eval_answer_results)

In [142]:
eval_answer_results['accuracy'].sum()

KeyError: 'accuracy'

In [36]:
eval_answer_results.describe()

            pp_id      answer_gt   answer_preds  flag  difference
count   43.000000      42.000000      42.000000  43.0   42.000000
mean    72.930233    8952.837674    8950.704340   1.0    0.177162
std     52.827840   29816.599232   29817.489095   0.0    0.300400
min      1.000000       0.700000       0.000000   1.0    0.000000
25%     29.000000       3.000000       2.000000   1.0    0.000000
50%     63.000000       9.000000      10.500000   1.0    0.000000
75%    132.500000      75.200000      43.000000   1.0    0.229167
max    150.000000  140400.000000  140400.000000   1.0    1.000000

## answer eval ttest

In [37]:
from scipy import stats

In [38]:
dirty_answer_result = pd.read_csv('/projects/bces/lanl2/LLM4DC/evaluation/dirty_answer_result.csv')
dirty_answer_result = dirty_answer_result.iloc[:,1:]
gemma2_answer_result = pd.read_csv('/projects/bces/lanl2/LLM4DC/evaluation/gemma2_answer_result.csv')
gemma2_answer_result = gemma2_answer_result.iloc[:, 1:]
llama_answer_result = pd.read_csv('/projects/bces/lanl2/LLM4DC/evaluation/llama3.1_answer_result.csv')
llama_answer_result = llama_answer_result.iloc[:,1:]
mistral_answer_result = pd.read_csv('/projects/bces/lanl2/LLM4DC/evaluation/mistral_answer_result.csv')
mistral_answer_result = mistral_answer_result.iloc[:,1:]

In [39]:
answer_result = llama_answer_result.merge(gemma2_answer_result, on='pp_id', how='left', suffixes=('_llama3.1', '_gemma2')).merge(mistral_answer_result, on='pp_id', how='left', suffixes=('', '_mistral'))

In [40]:
answer_result = answer_result.merge(dirty_answer_result, on='pp_id', how='left', suffixes=('', '_dirty'))

In [41]:
answer_result.columns

Index(['accuracy_llama3.1', 'semantic_similarity_llama3.1',
       'precision_llama3.1', 'recall_llama3.1', 'f1_llama3.1',
       'bertscore_p_llama3.1', 'bertscore_r_llama3.1', 'bertscore_f1_llama3.1',
       'pp_id', 'accuracy_gemma2', 'semantic_similarity_gemma2',
       'precision_gemma2', 'recall_gemma2', 'f1_gemma2', 'bertscore_p_gemma2',
       'bertscore_r_gemma2', 'bertscore_f1_gemma2', 'accuracy',
       'semantic_similarity', 'precision', 'recall', 'f1', 'bertscore_p',
       'bertscore_r', 'bertscore_f1', 'accuracy_dirty',
       'semantic_similarity_dirty', 'precision_dirty', 'recall_dirty',
       'f1_dirty', 'bertscore_p_dirty', 'bertscore_r_dirty',
       'bertscore_f1_dirty'],
      dtype='object')

In [42]:
metric_names = ['accuracy','semantic_similarity', 'precision', 'recall', 'f1', 'bertscore_p', 'bertscore_r','bertscore_f1']

In [43]:
ttest_result = []
for m in metric_names:
    model_list = models[:3] + ['dirty'] #['llama', 'gemma2', 'mistral', 'dirty']
    llama_result = stats.ttest_rel(answer_result[f'{m}_dirty'].values, answer_result[f'{m}_llama3.1'].values)
    gemma_result = stats.ttest_rel(answer_result[f'{m}_dirty'].values, answer_result[f'{m}_gemma2'].values)
    # print(answer_result[f'{m}_llama'].values)
    mistral_result = stats.ttest_ind(answer_result[f'{m}_dirty'].values, answer_result[f'{m}'].values)
    ttest_result.append({f'{m}':[llama_result.pvalue.item(), gemma_result.pvalue.item(), mistral_result.pvalue.item()]})
    # print(gemma_result)
    # print(mistral_result)
    # break

In [44]:
def ttest_answer(answer_result):
    ttest_result = []
    for m in metric_names:
        model_list = ['llama', 'gemma2', 'mistral', 'dirty']
        llama_result = stats.ttest_rel(answer_result[f'{m}_dirty'].values, answer_result[f'{m}_llama'].values)
        gemma_result = stats.ttest_rel(answer_result[f'{m}_dirty'].values, answer_result[f'{m}_gemma2'].values)
        # print(answer_result[f'{m}_llama'].values)
        mistral_result = stats.ttest_ind(answer_result[f'{m}_dirty'].values, answer_result[f'{m}'].values)
        ttest_result.append({f'{m}':[llama_result.pvalue.item(), gemma_result.pvalue.item(), mistral_result.pvalue.item()]})
    combined_data = {k: v for d in ttest_result for k, v in d.items()}

    ttest_result = pd.DataFrame(combined_data)
    return ttest_result

In [45]:
combined_data = {k: v for d in ttest_result for k, v in d.items()}

ttest_result = pd.DataFrame(combined_data)

In [46]:
ttest_result['model'] = ['llama3.1', 'gemma2', 'mistral']

In [47]:
ttest_result

,accuracy,semantic_similarity,precision,recall,f1,bertscore_p,bertscore_r,bertscore_f1,model
0,1.356337e-08,8.436960e-11,2.096717e-14,1.066235e-12,8.282881e-15,1.852748e-12,4.726115e-07,1.473374e-10,llama3.1
1,2.663852e-14,4.927548e-16,2.242967e-21,1.817695e-19,6.084980e-22,8.232651e-17,2.417069e-10,1.056240e-14,gemma2
2,4.773402e-01,2.192182e-01,7.251551e-03,3.912747e-02,1.107158e-02,4.154803e-02,6.919708e-01,2.298471e-01,mistral

In [155]:
ppp_results = answer_result[answer_result['pp_id'] >= 62][answer_result['pp_id'] <=91]
ppp_ttest = ttest_answer(ppp_results)

/tmp/ipykernel_4172012/3278763139.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ppp_results = answer_result[answer_result['pp_id'] >= 62][answer_result['pp_id'] <=91]

KeyError: 'accuracy_llama'

In [ ]:
ppp_ttest

In [ ]:
dish_result= answer_result[answer_result['pp_id'] >= 92]
dish_ttest = ttest_answer(dish_result)
dish_ttest

In [ ]:
menu_results = answer_result[answer_result['pp_id'] < 31]
menu_ttest = ttest_answer(menu_results)
menu_ttest

In [ ]:
chi_results = answer_result[answer_result['pp_id'] >= 31][answer_result['pp_id'] <=61]
chi_ttest = ttest_answer(chi_results)
chi_ttest

In [ ]:
ppp_results = answer_result[answer_result['pp_id'] >= 62][answer_result['pp_id'] <=91]
ppp_ttest = ttest_answer(ppp_results)
ppp_ttest