In [45]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [2]:
# models generation directory: LLM4DC/CoT.response
# predicted dataset by model:  LLM4DC/CoT.response/{model}/datasets_llm
# predicted workflow by model:  LLM4DC/CoT.response/{model}/recipes_llm
# predicted operations by model:  LLM4DC/CoT.response/{model}/operation
# logging:  LLM4DC/CoT.response/logging

# all the sample tables are under: LLM4DC/datasets
# query: 1-30 [menu]: LLM4DC/datasets/menu_datasets
# clean table (ground truth) LLM4DC/datasets/menu_datasets/clean_tables/
# clean workflow (silver ground truth):  LLM4DC/datasets/menu_datasets/workflows

# query: 31-61 [chicago]: LLM4DC/datasets/CFI_datasets
# clean table (ground truth): LLM4DC/datasets/CFI_datasets/cleaned_tables/
# clean workflow (silver ground truth):  LLM4DC/datasets/CFI_datasets/workflows

# query: 62-91 [ppp]:LLM4DC/datasets/ppp_datasets
# clean table (ground truth): LLM4DC/datasets/ppp_datasets/cleaned_tables/
# clean workflow (silver ground truth):  LLM4DC/datasets/ppp_datasets/workflows

# query: 92-110 [dish]: LLM4DC/datasets/dish_datasets
# clean table (ground truth): LLM4DC/datasets/dish_datasets/cleaned_tables/
# clean workflow (silver ground truth):  LLM4DC/datasets/dish_datasets/workflows

# query: 111-126 [flights]: LLM4DC/datasets/flights
# clean table (ground truth): LLM4DC/datasets/flights/cleaned_tables/flights_data_p{query_id}.csv
# clean workflow (silver ground truth):  LLM4DC/datasets/flights/workflows/flights_p{query_id}.json

# query: 127- 154 [hospital]: LLM4DC/datasets/hospital
# clean table (ground truth): LLM4DC/datasets/hospital/clean_tables/
# clean workflow (silver ground truth):  LLM4DC/datasets/hospital/workflows

In [46]:
import re

In [47]:
import json

In [48]:
import ast
# LLM-based history update solution
import importlib.util
import inspect
from typing import List
import requests
import json
import re
import difflib
from collections import Counter
# from spellchecker import SpellChecker
from datetime import datetime
import pandas as pd
import ast
import random
import logging 
# from history_update_problem.call_or import export_rows
from call_or import *
from evaluation import *

In [49]:
models = ['llama3.1',  'mistral', 'gemma2','deepseek-r1']

# Worflow eval

In [50]:
def eval_workflows(pp_id, gt_wf_fp, pred_wf_fp):
    # print(gt_wf_fp)
    gt_ops_list = parse_recipe(pp_id, recipe=gt_wf_fp)
    pred_ops_list = parse_recipe(pp_id, recipe=pred_wf_fp)
    return {'pp_id': pp_id, 'gt_ops': gt_ops_list[pp_id], 'pred_ops': pred_ops_list[pp_id]}
    # print(gt_ops_list)
    # print(pred_ops_list)

answer_gt_path = '/projects/bces/lanl2/LLM4DC/evaluation/answer_1-154_gt.json'
answer_preds_llama = '/projects/bces/lanl2/LLM4DC/evaluation/answer_1-154_llama3.1.json'


# eval_answer_results = eval_answers(answer_gt_path, answer_preds_llama)
# model = models[0]
wf_gt_folder = '/projects/bces/lanl2/LLM4DC/datasets'

query_contents = pd.read_csv('/projects/bces/lanl2/LLM4DC/purposes/all_purposes.csv')
    
ops_result = {}
for model in models[:3]:
    ops_list = []

    wf_pred_folder = f'/projects/bces/lanl2/LLM4DC/CoT.response/{model}/recipes_llm'
    for query_id in range(155):
        row = query_contents[query_contents['ID'] == query_id]
        if len(row) == 0:
            continue
        # if model == 'llama3.1':
        if query_id >126:
            #TODO: what's the point to have the target_path here? 
            target_path = f'{wf_gt_folder}/hospital/clean_tables/hos_pp{query_id}.csv'
            wf_gt_fp = f"{wf_gt_folder}/hospital/workflows/hos_p{query_id}.json"
            wf_pred_fp = f"{wf_pred_folder}/{model}_hos_test_p{query_id}.json"
        elif query_id >= 111 and query_id <=126:
            target_path = f'{wf_gt_folder}/flights/cleaned_tables/flights_data_p{query_id}.csv'
            wf_gt_fp = f"{wf_gt_folder}/flights/workflows/flights_p{query_id}.json"
            wf_pred_fp = f"{wf_pred_folder}/{model}_flights_test_p{query_id}.json"
        elif query_id >= 92 and query_id <=110:
            target_path = f'{wf_gt_folder}/dish_datasets/cleaned_tables/dish_sample_p{query_id}.csv'
            wf_gt_fp = f"{wf_gt_folder}/dish_datasets/workflows/dish_sample_p{query_id}.json"
            wf_pred_fp = f"{wf_pred_folder}/{model}_dish_test_p{query_id}.json"
        elif query_id >= 62 and query_id <= 91:
            target_path = f'{wf_gt_folder}/ppp_datasets/cleaned_tables/ppp_sample_p{query_id}.csv'
            wf_gt_fp = f"{wf_gt_folder}/ppp_datasets/workflows/ppp_sample_p{query_id}.json"
            wf_pred_fp = f"{wf_pred_folder}/{model}_ppp_test_p{query_id}.json"
        elif query_id >= 31 and query_id <= 61:
            target_path = f'{wf_gt_folder}/CFI_datasets/cleaned_tables/chi_sample_p{query_id}.csv'
            wf_gt_fp = f"{wf_gt_folder}/CFI_datasets/workflows/chi_sample_p{query_id}.json"
            wf_pred_fp = f"{wf_pred_folder}/{model}_chi_test_p{query_id}.json"

        elif query_id <31:
            target_path = f'{wf_gt_folder}/menu_datasets/clean_tables/menu_sample_p{query_id}'
            wf_gt_fp = f"{wf_gt_folder}/menu_datasets/workflows/menu_sample_p{query_id}.json"
            wf_pred_fp = f"{wf_pred_folder}/{model}_menu_test_p{query_id}.json"
        if wf_gt_fp and wf_pred_fp:
            ops_list.append(eval_workflows(query_id, wf_gt_fp, wf_pred_fp))
    ops_result[model] = pd.DataFrame(ops_list)
# ops_df = pd.DataFrame(ops_list)

In [51]:
def parse_mean(df, col_name):
    total_wf = df.describe().loc['mean']
    # total_wf.columns = [col_name] #rename(columns={"mean": col_name})
    return total_wf

In [52]:
wf_length = []
total_wf = []
print(len(ops_result))
ppp_wf, dish_wf, menu_wf,chi_wf,hos_wf, flights_wf = [],[],[],[],[],[]
col_name = []
output_wf =  []
for key, value in ops_result.items():
    model = key
    ops_df = value
    ops_df['gt_ops_length'] = ops_df['gt_ops'].apply(len)
    ops_df['pred_ops_length'] = ops_df['pred_ops'].apply(len)
    ops_df['gt_ops_set_length'] = ops_df['gt_ops'].apply(lambda x: len(set(x)))
    ops_df['pred_ops_set_length'] = ops_df['pred_ops'].apply(lambda x: len(set(x)))

    ops_length_desc = ops_df.describe().loc['mean']
    ops_length_desc.columns = [model]
    wf_length.append(ops_length_desc)


    workflow_results = calculate_operation_metrics(ops_df['gt_ops'], ops_df['pred_ops'])
    workflow_results['pp_id'] = ops_df['pp_id']
    # print(workflow_results[workflow_results['pp_id'] == 127])
    workflow_results.set_index('pp_id', inplace=True)
    ops_df.set_index('pp_id', inplace=True)
    total_wf.append(parse_mean(workflow_results, f'total__{model}'))
    col_name.append(f'total__{model}')
    
    
    hos_results = workflow_results.loc[127:155]
       
    # hos_results = workflow_results[workflow_results['pp_id'] >= 127]
    total_wf.append(parse_mean(hos_results, f'hos__{model}'))
    hos_ops = ops_df.loc[127:155]
    wf_length.append(parse_mean(hos_ops, f'hos__{model}'))
    col_name.append(f'hos__{model}')


    # flights_results = workflow_results[workflow_results['pp_id'] >= 111][workflow_results['pp_id'] <=126]
    flights_results = workflow_results.loc[111:127]
    flights_ops = ops_df.loc[111:127]
    total_wf.append(parse_mean(flights_results, f'flights__{model}'))
    wf_length.append(parse_mean(flights_ops, f'flights_{model}'))
    col_name.append(f'flights__{model}')

    # ppp_results = workflow_results[workflow_results['pp_id'] >= 62][workflow_results['pp_id'] <=91]
    ppp_results = workflow_results.loc[62:91]
    ppp_ops = ops_df.loc[62:91] 
    wf_length.append(parse_mean(ppp_ops, f'ppp_{model}'))
    total_wf.append(parse_mean(ppp_results, f'ppp__{model}'))
    col_name.append(f'ppp__{model}')

    # dish_results = workflow_results[workflow_results['pp_id'] >= 92][workflow_results['pp_id'] <= 110]
    dish_results = workflow_results.loc[92:111]
    dish_ops = ops_df.loc[92:111] 
    wf_length.append(parse_mean(dish_ops, f'dish_{model}'))
    total_wf.append(parse_mean(dish_results, f'dish__{model}'))
    col_name.append(f'dish__{model}')

    # menu_results = workflow_results[workflow_results['pp_id'] < 31]
    menu_results = workflow_results.loc[:31]
    menu_ops = ops_df.loc[:31] 
    wf_length.append(parse_mean(menu_ops, f'menu_{model}'))
    total_wf.append(parse_mean(menu_results, f'menu__{model}'))
    col_name.append(f'menu__{model}')
    # chi_results = workflow_results[workflow_results['pp_id'] >= 31][workflow_results['pp_id'] <=61]
    chi_results = workflow_results.loc[31:62]
    chi_ops = ops_df.loc[92:111] 
    wf_length.append(parse_mean(chi_ops, f'chi_{model}'))
    total_wf.append(parse_mean(chi_results, f'chi__{model}'))
    col_name.append(f'chi__{model}')
wf_perf = pd.concat(total_wf, axis=1)
wf_perf.columns = col_name
# print(wf_perf)
wf_perf = wf_perf.transpose()
wf_length = pd.concat(wf_length, axis=1)
wf_length.columns = col_name
wf_length = wf_length.transpose()
wf_perf = wf_perf.reset_index()

3

In [53]:
wf_length

,pp_id,gt_ops_length,pred_ops_length,gt_ops_set_length,pred_ops_set_length
total__llama3.1,76.739437,7.492958,4.246479,3.563380,1.957746
hos__llama3.1,NaN,10.178571,4.714286,3.964286,1.785714
flights__llama3.1,NaN,8.647059,2.941176,3.882353,1.647059
ppp__llama3.1,NaN,6.090909,4.181818,3.500000,2.136364
dish__llama3.1,NaN,5.470588,3.764706,3.764706,2.235294
menu__llama3.1,NaN,6.903226,4.580645,2.870968,2.064516
chi__llama3.1,NaN,5.470588,3.764706,3.764706,2.235294
total__mistral,76.739437,7.492958,3.464789,3.563380,1.859155
hos__mistral,NaN,10.178571,4.321429,3.964286,1.964286
flights__mistral,NaN,8.647059,3.588235,3.882353,1.823529
ppp__mistral,NaN,6.090909,4.545455,3.500000,2.272727
dish__mistral,NaN,5.470588,3.705882,3.764706,2.235294
menu__mistral,NaN,6.903226,1.709677,2.870968,1.225806
chi__mistral,NaN,5.470588,3.705882,3.764706,2.235294
total__gemma2,76.739437,7.492958,4.647887,3.563380,2.232394
hos__gemma2,NaN,10.178571,6.500000,3.964286,2.535714
flights__gemma2,NaN,8.647059,3.647059,3.882353,1.764706
ppp__gemma2,NaN,6.090909,5.318182,3.500000,2.500000
dish__gemma2,NaN,5.470588,5.352941,3.764706,3.058824
menu__gemma2,NaN,6.903226,3.129032,2.870968,1.935484
chi__gemma2,NaN,5.470588,5.352941,3.764706,3.058824

In [54]:
wf_length.to_csv('workflow_length.csv')

In [55]:
wf_perf

                index  accuracy  precision    recall        f1
0     total__llama3.1  0.098592   0.934272  0.529577  0.647150
1       hos__llama3.1  0.000000   1.000000  0.458333  0.618707
2   flights__llama3.1  0.000000   0.980392  0.408824  0.555509
3       ppp__llama3.1  0.272727   0.958333  0.665152  0.755880
4      dish__llama3.1  0.117647   0.867647  0.500000  0.598739
5      menu__llama3.1  0.193548   0.870968  0.623118  0.701101
6       chi__llama3.1  0.064516   0.940860  0.512366  0.638249
7      total__mistral  0.049296   0.739202  0.399178  0.491348
8        hos__mistral  0.000000   0.922619  0.453571  0.591412
9    flights__mistral  0.000000   0.632353  0.270588  0.365826
10       ppp__mistral  0.181818   0.846970  0.586364  0.660390
11      dish__mistral  0.058824   0.759804  0.431373  0.517227
12      menu__mistral  0.064516   0.489247  0.252688  0.315361
13       chi__mistral  0.032258   0.795699  0.416129  0.509524
14      total__gemma2  0.077465   0.861854  0.553052  0.644321
15        hos__gemma2  0.035714   0.952381  0.611310  0.732313
16    flights__gemma2  0.000000   0.823529  0.356863  0.480019
17        ppp__gemma2  0.181818   0.859848  0.673485  0.728535
18       dish__gemma2  0.000000   0.703922  0.583333  0.603828
19       menu__gemma2  0.161290   0.817204  0.586559  0.656989
20        chi__gemma2  0.096774   0.935484  0.484409  0.611905

In [56]:
wf_perf.to_csv('workflow_results_llama_mistral_gemma2.csv')

# Dataset Eval

In [27]:
# def retrieve_tg_cols(tg_cols_fp="target_columns_list.csv"):
#     id_tg_cols = {}
#     tg_df = pd.read_csv(tg_cols_fp)
#     result_dict = tg_df.set_index('ID')['tg_columns'].to_dict()
#     return result_dict

In [57]:
result_dict = retrieve_tg_cols("/projects/bces/lanl2/LLM4DC/evaluation/target_column_list.csv")
print(result_dict)
# model = "llama3.1"
# model = "mistral"
# model = "gemma2"
# model = "dirty"
data_gt_folder = "/projects/bces/lanl2/LLM4DC/datasets"

for model in models[:3] + ["dirty"]:
    ratio_list = []
    for query_id in range(155):
        # print(query_id)
        tg_cols = result_dict.get(query_id)
        if tg_cols:
            if model=="dirty":
                if query_id >126:
                    target_path = f'{data_gt_folder}/hospital/clean_tables/hos_pp{query_id}.csv'
                    table_preds_path = f'/projects/bces/lanl2/LLM4DC/datasets/hospital/hos_data_p{query_id}.csv'
                elif query_id >= 111 and query_id <=126:
                    target_path = f'{data_gt_folder}/flights/cleaned_tables/flights_data_p{query_id}.csv'
                    table_preds_path = f'/projects/bces/lanl2/LLM4DC/datasets/flights/flights_data_p{query_id}.csv'
                    # target_path = None
                    # table_preds_path = None
                elif query_id >= 92 and query_id <=110:
                    target_path = f'{data_gt_folder}/dish_datasets/cleaned_tables/dish_sample_p{query_id}.csv'
                    table_preds_path = f'/projects/bces/lanl2/LLM4DC/datasets/dish_datasets/dish_data_p{query_id}.csv'
                elif query_id >= 62 and query_id <= 91:
                    target_path = f'{data_gt_folder}/ppp_datasets/cleaned_tables/ppp_sample_p{query_id}.csv'
                    table_preds_path =  f'/projects/bces/lanl2/LLM4DC/datasets/ppp_datasets/ppp_data_p{query_id}.csv'
                elif query_id >= 31 and query_id <= 61:
                    target_path = f'{data_gt_folder}/CFI_datasets/cleaned_tables/chi_sample_p{query_id}.csv'
                    table_preds_path = f'/projects/bces/lanl2/LLM4DC/datasets/CFI_datasets/chi_food_data_p{query_id}.csv'
                elif query_id <31:
                    target_path = f'{data_gt_folder}/menu_datasets/clean_tables/menu_sample_p{query_id}.csv'
                    table_preds_path = f'/projects/bces/lanl2/LLM4DC/datasets/menu_datasets/menu_p{query_id}.csv'
            else:
                llm_folder = f"CoT.response/{model}/datasets_llm"
                data_gt_folder = "/projects/bces/lanl2/LLM4DC/datasets"
                pred_fp = f'/projects/bces/lanl2/LLM4DC/{llm_folder}'
                if query_id >126:
                    target_path = f'{data_gt_folder}/hospital/clean_tables/hos_pp{query_id}.csv'
                    table_preds_path = f'{pred_fp}/{model}_hos_test_p{query_id}.csv'
                elif query_id >= 111 and query_id <=126:
                    target_path = f'{data_gt_folder}/flights/cleaned_tables/flights_data_p{query_id}.csv'
                    table_preds_path = f'{pred_fp}/{model}_flights_test_p{query_id}.csv'
                elif query_id >= 92 and query_id <=110:
                    target_path = f'{data_gt_folder}/dish_datasets/cleaned_tables/dish_sample_p{query_id}.csv'
                    table_preds_path = f'{pred_fp}/{model}_dish_test_p{query_id}.csv'
                elif query_id >= 62 and query_id <= 91:
                    target_path = f'{data_gt_folder}/ppp_datasets/cleaned_tables/ppp_sample_p{query_id}.csv'
                    table_preds_path = f'{pred_fp}/{model}_ppp_test_p{query_id}.csv'
                elif query_id >= 31 and query_id <= 61:
                    target_path = f'{data_gt_folder}/CFI_datasets/cleaned_tables/chi_sample_p{query_id}.csv'
                    table_preds_path = f'{pred_fp}/{model}_chi_test_p{query_id}.csv'
                elif query_id <31:
                    target_path = f'{data_gt_folder}/menu_datasets/clean_tables/menu_sample_p{query_id}.csv'
                    table_preds_path = f'{pred_fp}/{model}_menu_test_p{query_id}.csv'
            if target_path and table_preds_path:
                gt_df = pd.read_csv(target_path)
                preds_df = pd.read_csv(table_preds_path)
                # print(gt_df.head(5), preds_df.head(5))
                res = average_match_ratio(gt_df, preds_df, tg_cols)
                ratio_list.append({'pp_id': query_id, 'ratio': res})
    dt_result = pd.DataFrame(ratio_list)
    dt_result.to_csv(f'evaluation/{model}_table_result.csv')

{1: 'page_count', 2: 'page_count', 3: 'event', 4: 'event', 5: 'event', 6: 'venue', 7: 'occasion', 8: 'occasion', 9: 'page_count, dish_count', 10: 'dish_count', 11: 'page_count, dish_count', 12: 'page_count, location', 13: 'sponsor, currency', 14: 'sponsor, dish_count', 15: 'sponsor, event', 16: 'sponsor, event', 17: 'sponsor, event', 18: 'sponsor, event', 19: 'page_count, venue', 20: 'sponsor', 21: 'event', 22: 'occasion', 23: 'venue, dish_count', 24: 'status', 25: 'sponsor, currency', 26: 'date', 27: 'date, page_count, dish_count', 28: 'page_count, venue', 29: 'occasion', 30: 'currency', 31: 'Risk', 32: 'Results', 33: 'Facility Type', 34: 'Facility Type', 35: 'Inspection Type', 36: 'DBA Name, Results', 37: 'DBA Name, Results', 38: 'Facility Type, Risk', 39: 'Facility Type, Risk', 40: 'Facility Type, Risk', 41: 'Facility Type, Risk', 42: 'Facility Type, Risk', 43: 'Facility Type, Results', 44: 'Results', 45: 'Facility Type, Inspection ID', 46: 'Risk', 47: 'Facility Type, Results', 48: 'DBA Name, Inspection ID', 49: 'Facility Type, Risk, Results', 50: 'Inspection Type', 51: 'Facility Type,Results', 52: 'Address, Risk, Results', 53: 'Risk, Results', 54: 'Inspection Date', 55: 'DBA Name', 56: 'License #, Results', 57: 'DBA Name, Risk, Inspection Date', 58: 'Facility Type, Risk', 59: 'DBA Name, Inspection Date', 60: 'Facility Type, Inspection ID, Inspection Date', 62: 'LoanAmount', 63: 'LoanAmount', 64: 'LoanAmount', 65: 'NAICSCode, JobsReported', 66: 'JobsReported, LoanAmount', 67: 'City', 68: 'BusinessType, LoanAmount', 69: 'BusinessType, LoanAmount', 70: 'BusinessType, LoanAmount', 71: 'BusinessType, Zip', 72: 'Zip, LoanAmount', 73: 'Zip, LoanAmount', 74: 'Gender, LoanAmount', 75: 'Gender, LoanAmount', 76: 'City, LoanAmount', 77: 'City, LoanAmount', 78: 'Zip, LoanAmount', 79: 'Zip, LoanAmount', 80: 'RaceEthnicity, LoanAmount', 81: 'RaceEthnicity, LoanAmount', 87: 'City, LoanAmount, JobsReported', 89: 'City, LoanAmount, Zip', 92: 'times_appeared', 93: 'name, first_appeared, last_appeared', 94: 'name, first_appeared, last_appeared', 98: 'name, lowest_price', 99: 'name, highest_price', 100: 'name, first_appeared', 101: 'name, first_appeared', 102: 'name, menus_appeared', 103: 'name, menus_appeared', 104: 'name, times_appeared, highest_price', 105: 'name, times_appeared, lowest_price', 106: 'name, highest_price, lowest_price', 107: 'name, highest_price, lowest_price', 108: 'name,  highest_price, lowest_price', 109: 'name, menus_appeared, times_appeared', 110: 'name, times_appeared, highest_price, \nlowest_price', 111: 'sched_dep_time, act_dep_time', 112: 'sched_dep_time, sched_arr_time', 113: 'src, sched_dep_time, act_dep_time', 114: 'src', 115: 'flight', 116: 'sched_arr_time', 117: 'src, act_arr_time, sched_arr_time', 118: 'sched_dep_time, act_dep_time', 119: 'sched_arr_time', 120: 'src, sched_dep_time, act_dep_time', 121: 'act_dep_time, sched_dep_time', 122: 'act_dep_time, act_arr_time', 123: 'sched_dep_time, act_dep_time', 124: 'sched_arr_time, act_arr_time', 125: 'src, sched_dep_time, act_dep_time', 126: 'sched_arr_time, act_arr_time', 127: 'City', 128: 'City', 129: 'CountyName', 130: 'HospitalType, CountyName, EmergencyService', 131: 'HospitalOwner, City, ZipCode', 132: 'HospitalName, HospitalType, HospitalOwner', 133: 'EmergencyService, HospitalType', 134: 'HospitalType, HospitalOwner', 135: 'CountyName, EmergencyService', 136: 'City, HospitalOwner, EmergencyService', 137: 'CountyName, HospitalType', 138: 'HospitalType, HospitalOwner, City', 139: 'ZipCode, HospitalType, HospitalOwner', 140: 'City, HospitalType', 141: 'HospitalType, City, ZipCode', 142: 'EmergencyService, HospitalType', 143: 'CountyName, HospitalOwner, HospitalType', 144: 'HospitalOwner, EmergencyService', 145: 'City, EmergencyService', 146: 'HospitalType, ZipCode', 147: 'HospitalOwner, HospitalType', 148: 'EmergencyService, CountyName', 149: 'HospitalOwner, ZipCode, HospitalType', 150: 'HospitalType, EmergencyService', 151: 'City, HospitalOwner, HospitalType', 152: 'HospitalOwner, City', 153: 'ZipCode, EmergencyService', 154: 'City, HospitalOwner'}
String Mismatch: BANQUET <--> 11TH ANNUAL BANQUET
String Mismatch: LUNCHEON <--> Dinner
String Mismatch: DINNER <--> CHRISTMAS DINNER
String Mismatch: LUNCHEON <--> LUNCHEON TENDERED IMPERIAL COUNCIL
String Mismatch: BREAKFAST <--> Dinner
String Mismatch: BANQUET <--> Dinner
String Mismatch: 15NTH BURNS ANNIVERSARY <--> Dinner
String Mismatch: BREAKFAST <--> Dinner
String Mismatch: BREAKFAST <--> Dinner
String Mismatch: DINNER <--> DINNER (?)
String Mismatch: BANQUET <--> BANQUET AND RECEPTION COMMEMORATING 50 YEARS SINCE THE ADMISSION OF HONORABLE JAMES TYNDALE MITCHELL,LL.D. CHIEF JUSTICE OF THE SUPREME COURT OF PA TO THE BAR OF PHILADELPHIA
String Mismatch: TIFFIN <--> Dinner
String Mismatch: DINNER <--> DAILY MENU, DINNER
String Mismatch: BANQUET <--> THIRD ANNUAL BANQUET
String Mismatch: TIFFIN <--> Dinner
String Mismatch: LUNCHEON <--> Dinner
String Mismatch: BANQUET <--> Dinner
String Mismatch: BANQUET <--> ALL AMERICAN BANQUET IN HONOR OF EDWIN C. HALL
String Mismatch: BANQUET <--> Dinner
String Mismatch: 11TH ANNUAL BANQUET <--> Other
String Mismatch: BREAKFAST <--> Other
String Mismatch: FOURTH ANNUSL DINNER <--> DINNER
String Mismatch: BREAKFAST <--> Other
String Mismatch: PRIVATE BANQUET <--> Other
String Mismatch: BREAKFAST <--> Other
String Mismatch: MENU <--> DINNER
String Mismatch: BREAKFAST MENU <--> Other
String Mismatch: ZWEITES FRUHSTUCK <--> BREAKFAST
String Mismatch: DINNER <--> Other
String Mismatch: FRUHSTUCK <--> BREAKFAST
String Mismatch: LUNCH <--> Other
String Mismatch: TIFFIN <--> Other
String Mismatch: BREAKFAST <--> Other
String Mismatch: BREAKFAST <--> Other
String Mismatch: DAILY MENU, DINNER <--> DINNER
String Mismatch: THIRD ANNUAL BANQUET <--> BANQUET
String Mismatch: LUNCH <--> Other
String Mismatch: PERSONALLY CONDUCTED TOUR THROUGH MEXICO & CALIFORNIA <--> TOUR
String Mismatch: TIFFIN <--> Other
String Mismatch: FIRST ANNUAL BANQUET <--> BANQUET
String Mismatch: BREAKFAST <--> Other
String Mismatch: ANNUAL BANQUET <--> BANQUET
String Mismatch: LUNCHEON <--> LUCHON
String Mismatch: CHRISTMAS DINNER <--> BANQUET
String Mismatch: ZWEITES FRUHSTUCK <--> DINNER
String Mismatch: DINNER <--> DINNER (?)
String Mismatch: DINNER <--> DINNER TO ABOVE
String Mismatch: PROF <--> Professional
String Mismatch: GOVT <--> Government
String Mismatch: PATR <--> PATR;
String Mismatch: POL <--> Government
String Mismatch: RAILROAD <--> Restaurant
String Mismatch: RAILROAD <--> Restaurant
String Mismatch: SOC <--> SOCIAL
String Mismatch: SOC <--> SOCIAL
String Mismatch: RAILROAD <--> Restaurant
String Mismatch: PROF <--> Professional
String Mismatch: SOC <--> SOC;
String Mismatch: GOVT <--> GOV;
String Mismatch: SOC <--> SOC;
String Mismatch: SOC <--> SOC;
String Mismatch: PATR <--> PATR;
String Mismatch: SOC <--> SOC;
String Mismatch: POL <--> Government
String Mismatch: EDUC <--> EDUC;
String Mismatch: SOC <--> SOC;
String Mismatch: DAILY <--> Other (Daily)
String Mismatch: DAILY <--> OTHER (DAILY);
String Mismatch: OTHER (ANNIV) <--> Other (Anniversary)
String Mismatch: OTHER, [SOC?] <--> Other (Anniversary)
String Mismatch: DAILY <--> DAILY;
String Mismatch: RELIGIOUS HOLIDAY <--> HOLIDAY
String Mismatch: DAILY <--> DAILY;
String Mismatch: [SOC?] <--> OTHER
String Mismatch: DAILY <--> DAILY;
String Mismatch: ANNIVERSARY <--> ANNIVERSARY;
String Mismatch: SECULAR HOLIDAY <--> HOLIDAY
String Mismatch: DAILY <--> OTHER
String Mismatch: DAILY <--> OTHER
String Mismatch: SECULAR HOLIDAY <--> HOLIDAY
String Mismatch: ANNIVERSARY <--> ANNIVERSARY;
String Mismatch: OTHER (ANNIV) <--> OTHER
String Mismatch: OTHER, [SOC?] <--> OTHER, [SOC?];
String Mismatch: BATTERY PARK HOTEL <--> UNKNOWN
String Mismatch: SOUTHERN PACIFIC <--> UNKNOWN
String Mismatch: SPILKER'S RESTAURANT AND GRILL ROOM <--> UNKNOWN
String Mismatch: ADAM'S RESTAURANT <--> UNKNOWN
String Mismatch: S.S. NIEUW AMSTERDAM <--> UNKNOWN
String Mismatch: UNKNOWN <--> ?
String Mismatch: SPRINGFIELD CALEDONIANS <--> UNKNOWN
String Mismatch: NIPPON YUSEN KAISHA <--> UNKNOWN
String Mismatch: UNKNOWN <--> [Restaurant name and/or location not given]
String Mismatch: THE MOUQUIN RESTAURANT AND WINE CO. <--> UNKNOWN
String Mismatch: DETROIT BOARD OF COMMERCE <--> UNKNOWN
String Mismatch: HOTEL BELVEDERE <--> UNKNOWN
String Mismatch: UNKNOWN <--> [Restaurant name and/or location not given]
String Mismatch: THE PORTLAND <--> UNKNOWN
String Mismatch: SOUTHERN PACIFIC <--> UNKNOWN
String Mismatch: COLONIAL HOTEL <--> UNKNOWN
String Mismatch: THE COMMODORE HOTEL <--> UNKNOWN
String Mismatch: NIPPON YUSEN KAISHA <--> UNKNOWN
String Mismatch: YE OLDE DUTCH TAVERN <--> UNKNOWN
String Mismatch: TOYO KISEN KAISHA <--> UNKNOWN
String Mismatch: NORDDEUTSCHER LLOYD BREMEN <--> Norddeutscherrr Lloyd Bremen
String Mismatch: TOOTS SHOR <--> UNKNOWN
String Mismatch: FRATERNAL UNION OF ANOINTED HIGH PRIESTS OF THE STATE OF NEW YORK <--> UNKNOWN
String Mismatch: THE BILTMORE <--> UNKNOWN
String Mismatch: WALDORF ASTORIA <--> UNKNOWN
String Mismatch: NIPPON YUSEN KAISHA <--> UNKNOWN
String Mismatch: UNKNOWN <--> [Restaurant And/Or Location Not Given]
String Mismatch: NIPPON YUSEN KAISHA <--> UNKNOWN
String Mismatch: WALDORF ASTORIA <--> UNKNOWN
String Mismatch: S.S. NIEUW AMSTERDAM <--> UNKNOWN
String Mismatch: NOVIOMAGUS <--> UNKNOWN
String Mismatch: HOTEL MARIE ANTOINETTE <--> UNKNOWN
String Mismatch: STATLER'S HOTEL AND RESTAURANT <--> UNKNOWN
String Mismatch: AMEN CORNER AXE <--> UNKNOWN
String Mismatch: THE BILTMORE <--> UNKNOWN
String Mismatch: COFFEE HOUSE <--> UNKNOWN
String Mismatch: KAISERHOF <--> UNKNOWN
String Mismatch: FREINDS OF WILLIAM CLAUSS <--> UNKNOWN
String Mismatch: ADAM'S RESTAURANT <--> ADAMS' RESTAURANT
String Mismatch: NORDDEUTSCHER LLOYD BREMEN <--> NORDDEUTSCHERRR LLOYD BREMEN
String Mismatch: DOLLARS <--> DOLARS$
String Mismatch: DOLLARS <--> dolars
String Mismatch: DOLLARS <--> DOLARS$
String Mismatch: DOLLARS <--> Dolar
String Mismatch: DOLLARS <--> Dolar
String Mismatch: DOLLARS <--> Dolar
String Mismatch: DOLLARS <--> dolr
String Mismatch: DOLLARS <--> dolr
String Mismatch: DOLLARS <--> dolar
String Mismatch: DOLLARS <--> DOLARS$
String Mismatch: DOLLARS <--> Dolars
String Mismatch: DOLLARS <--> Dolars
String Mismatch: DOLLARS <--> dolars$
String Mismatch: DOLLARS <--> Dolar
String Mismatch: DOLLARS <--> dolr
String Mismatch: DOLLARS <--> dolars$
String Mismatch: DOLLARS <--> DOLR
String Mismatch: DOLLARS <--> DOLR
String Mismatch: DOLLARS <--> dolar
String Mismatch: DOLLARS <--> Dolars
String Mismatch: DOLLARS <--> dolars
String Mismatch: DOLLARS <--> dolars
String Mismatch: DOLLARS <--> dolar
String Mismatch: DOLLARS <--> Dolar
String Mismatch: ADAM'S RESTAURANT <--> Adams' Restaurant
String Mismatch: WIEHL & WIDMAN <--> Wiehl and Widman
String Mismatch: [RESTAURANT AND/OR LOCATION NOT GIVEN] <--> [Restaurant name and/or location not given]
String Mismatch: [RESTAURANT AND/OR LOCATION NOT GIVEN] <--> [Restaurant name and/or location not given]
String Mismatch: Spilker's Restaurant and Grill Room <--> Wiehl and Widman
String Mismatch: Adam's Restaurant <--> Adams' Restaurant
String Mismatch: S.S. Nieuw Amsterdam <--> SS Nieuw Amsterdam
String Mismatch: Wiehl & Widman <--> Wiehl and Widman
String Mismatch: University Of Richmond <--> Springfield Caledonians
String Mismatch: The Mouquin Restaurant and Wine Co. <--> Four Seasons
String Mismatch: The Brass Rail <--> Four Seasons
String Mismatch: THE PENNSYLVANIA BAR ASSOCIATION ON BEHALF OF THE BAR OF THE COMMONWEALTH <--> Pennsylvania Bar Association
String Mismatch: NORDDEUTSCHER LLOYD BREMEN <--> NORDDEUTSCHERRR LLOYD BREMEN
String Mismatch: Gardner & Smith <--> Gardner and Smith
String Mismatch: TOYO KISEN KAISHA - HING KONG MARU <--> Toyo Kisen Kaisha - Hong Kong Maru
String Mismatch: S.S. Nieuw Amsterdam <--> SS Nieuw Amsterdam
String Mismatch: The Four Seasons <--> Four Seasons
String Mismatch: COEUR DE LION CAMMANDERY NUMBER TWENTY-THREE KNIGHTS TEMPLAR <--> Coeur de Lion Commandery Number Twenty-Three Knights Templar
String Mismatch: 11TH ANNUAL BANQUET <--> BANQUET
String Mismatch: FOURTH ANNUSL DINNER <--> FOURTH ANNUAL DINNER
String Mismatch: LUNCHEON TENDERED IMPERIAL COUNCIL <--> LUNCH/DINNER
String Mismatch: BREAKFAST <--> BREKFAST
String Mismatch: 15NTH BURNS ANNIVERSARY <--> 15TH BURNS ANNIVERSARY
String Mismatch: SECOND ANNUAL DINNER <--> ANNUAL DINNER
String Mismatch: MENU <--> DINNER
String Mismatch: BREAKFAST <--> BREAKFAST MENU
String Mismatch: ZWEITES FRUHSTUCK <--> SECOND BREAKFAST
String Mismatch: TIFFIN <--> BREAKFAST
String Mismatch: DAILY MENU, DINNER <--> LUNCH/DINNER
String Mismatch: THIRD ANNUAL BANQUET <--> BANQUET
String Mismatch: PERSONALLY CONDUCTED TOUR THROUGH MEXICO & CALIFORNIA <--> TOUR
String Mismatch: TIFFIN <--> BREAKFAST
String Mismatch: FIRST ANNUAL BANQUET <--> BANQUET
String Mismatch: ALL AMERICAN BANQUET IN HONOR OF EDWIN C. HALL <--> BANQUET
String Mismatch: DINNER TO ABOVE <--> LUNCH/DINNER
String Mismatch: Adam's Restaurant <--> ADAMS' RESTAURANT
String Mismatch: NORDDEUTSCHER LLOYD BREMEN <--> NORDDEUTSCHERRR LLOYD BREMEN
String Mismatch: FOURTH ANNUSL DINNER <--> BREAKFAST
String Mismatch: LUNCHEON TENDERED IMPERIAL COUNCIL <--> LUNCH
String Mismatch: LUNCH AND DINNER <--> LUNCH
String Mismatch: 15NTH BURNS ANNIVERSARY <--> LUNCH
String Mismatch: MENU <--> LUNCH
String Mismatch: DINNER TO QUEEN ALEXANDRE & PRINCESS VICTORIA OF RUSSIA <--> Dinner
String Mismatch: THIRD ANNUAL BANQUET <--> Annual Banquet
String Mismatch: LUNCH <--> Lunh
String Mismatch: ALL AMERICAN BANQUET IN HONOR OF EDWIN C. HALL <--> LUNCH
String Mismatch: ANNUAL BANQUET <--> LUNCH
String Mismatch: DINNER TO ABOVE <--> Dinner
String Mismatch: Adam's Restaurant <--> Adams' Restaurant
String Mismatch: NORDDEUTSCHER LLOYD BREMEN <--> NORDDEUTSCHERRR LLOYD BREMEN
String Mismatch: FRATERNAL UNION OF ANOINTED HIGH PRIESTS OF THE STATE OF NEW YORK <--> Fraterna Union of Anointed High Priests of the State of New York
String Mismatch: T.N. "Conte Di Savoia""" <--> T.N. Conte di Savoia
String Mismatch: DINNER <--> Dinnr
String Mismatch: BREAKFAST <--> breakfast menu
String Mismatch: DINNER <--> dinner (?)
String Mismatch: DINNER <--> DNNER
String Mismatch: DINNER <--> dinnr
String Mismatch: DINNER <--> Dnner
String Mismatch: DINNER <--> DINR
String Mismatch: DINNER <--> dinr
String Mismatch: DINNER <--> dinner to above
String Mismatch: AMY'S <--> Amys
String Mismatch: S.S. NIEUW AMSTERDAM <--> SS Nieuw Amsterdam
String Mismatch: SEABOARD RAILWAY <--> Seaboard  Railway
String Mismatch: HOTEL ST. REGIS <--> Hotel _St. _Regis
String Mismatch: THE NEW MILLS HOTEL <--> The  New  Mills  Hotel
String Mismatch: LOUIS SHERRY <--> Louis _Sherry
String Mismatch: DETROIT BOARD OF COMMERCE <--> DETROIT _BOARD _OF _COMMERCE
String Mismatch: HOTEL BELVEDERE <--> Hotel  Belvedere
String Mismatch: SOUTHERN PACIFIC <--> Southern  Pacific
String Mismatch: HAMBURG AMERIKA LINIE <--> Hamburg America Line
String Mismatch: HEALY'S FORTY SECOND STREET RESTAURANT <--> Healy's Forty-Second Street Restaurant
String Mismatch: THE COMMODORE HOTEL <--> The  Commodore  Hotel
String Mismatch: HAMBURG AMERIKA LINIE <--> Hamburg America Line
String Mismatch: THE PENNSYLVANIA BAR ASSOCIATION ON BEHALF OF THE BAR OF THE COMMONWEALTH <--> Pennsylvania Railroad
String Mismatch: THE MAPLEWOOD <--> Maplewood
String Mismatch: TOYO KISEN KAISHA HING KONG MARU <--> TOYO  KISEN  KAISHA  -  HING  KONG  MARU
String Mismatch: NORWEGIAN GOVERNMENT <--> NORWEGIAN _GOVERNMENT
String Mismatch: HAMBURG AMERIKA LINIE <--> Hamburg America Line
String Mismatch: FRATERNAL UNION OF ANOINTED HIGH PRIESTS OF THE STATE OF NEW YORK <--> Fraternals Union Of Anointed High Priests Of The State Of New York
String Mismatch: HAMBURG AMERIKA LINIE <--> Hamburg America Line
String Mismatch: R.M.S. PARTHIA <--> RMS Parthia
String Mismatch: HOTEL IMPERIAL <--> Hotel  Imperial
String Mismatch: HEALY'S FORTY SECOND STREET RESTAURANT <--> Healy's _Forty-second _Street _restaurant
String Mismatch: S.S. NIEUW AMSTERDAM <--> SS Nieuw Amsterdam
String Mismatch: T.N. "CONTE DI SAVOIA""" <--> TN Conte Di Savoia
String Mismatch: HOTEL MARIE ANTOINETTE <--> Hotel Marie-Antoinette
String Mismatch: COEUR DE LION CAMMANDERY NUMBER TWENTY THREE KNIGHTS TEMPLAR <--> Coeur de Lion Commandery No. 23 Knights Templar
String Mismatch: LUNCH <--> luncheon
String Mismatch: LUNCH AND DINNER <--> lunch
String Mismatch: BREAKFAST <--> breakfast menu
String Mismatch: BANQUET AND RECEPTION COMMEMORATING 50 YEARS SINCE THE ADMISSION OF HONORABLE JAMES TYNDALE MITCHELL,LL.D. CHIEF JUSTICE OF THE SUPREME COURT OF PA TO THE BAR OF PHILADELPHIA <--> banquet and reception commemorating 50 years since the admission of honorable james tyndale mitchelllld chief justice of the supreme court of pa to the bar of philadelphia
String Mismatch: DINNER TO QUEEN ALEXANDRE & PRINCESS VICTORIA OF RUSSIA <--> dinner to queen alexandre  princess victoria of russia
String Mismatch: DAILY MENU, DINNER <--> daily menu dinner
String Mismatch: PERSONALLY CONDUCTED TOUR THROUGH MEXICO & CALIFORNIA <--> personally conducted tour through mexico  california
String Mismatch: LUNCH <--> luncheon
String Mismatch: ALL AMERICAN BANQUET IN HONOR OF EDWIN C. HALL <--> all american banquet in honor of edwin c hall
String Mismatch: DINNER <--> dinner to above
String Mismatch: PROFESSIONAL <--> PROF;.?
String Mismatch: GOVERNMENT <--> Airport
String Mismatch: PATRONAGE <--> Restaurant
String Mismatch: POLITICAL <--> Restaurant
String Mismatch: RAILROAD <--> Commercial
String Mismatch: RAILROAD <--> Commercial
String Mismatch: SOCIAL <--> SOCIAL.?
String Mismatch: RAILROAD <--> Commercial
String Mismatch: SS <--> SS; FOR
String Mismatch: PROFESSIONAL <--> Airport
String Mismatch: SOCIAL <--> Airport
String Mismatch: SOCIAL <--> Airport
String Mismatch: PATRONAGE <--> PATR;
String Mismatch: SOCIAL <--> Airport
String Mismatch: POLITICAL <--> Restaurant
String Mismatch: EDUCATION <--> EDUC;
String Mismatch: BATTERY PARK HOTEL <--> [BATTERY PARK HOTEL]
String Mismatch: USMS <--> [USMS]
String Mismatch: SOUTHERN PACIFIC <--> [SOUTHERN PACIFIC]
String Mismatch: SPILKER'S RESTAURANT AND GRILL ROOM <--> [SPILKER'S RESTAURANT AND GRILL ROOM]
String Mismatch: ADAM'S RESTAURANT <--> [ADAMS' RESTAURANT]
String Mismatch: S.S. NIEUW AMSTERDAM <--> [S.S. NIEUW AMSTERDAM]
String Mismatch: ISMALIA TEMPLE <--> [ISMALIA TEMPLE]
String Mismatch: CASINA DELLE ROSE & LUCCIOLA <--> [CASINA DELLE ROSE & LUCCIOLA]
String Mismatch: HOTEL ST. REGIS <--> [HOTEL ST. REGIS]
String Mismatch: LOUIS SHERRY <--> [LOUIS SHERRY]
String Mismatch: HOTEL BELVEDERE <--> [HOTEL BELVEDERE]
String Mismatch: THE PORTLAND <--> [THE PORTLAND]
String Mismatch: THE MAYFLOWER HOTEL <--> [THE MAYFLOWER HOTEL]
String Mismatch: COLONIAL HOTEL <--> [COLONIAL HOTEL]
String Mismatch: WOODSTOCK INN <--> [WOODSTOCK INN]
String Mismatch: YAMATO <--> [YAMATO]
String Mismatch: THE COMMODORE HOTEL <--> [THE COMMODORE HOTEL]
String Mismatch: THE PENNSYLVANIA BAR ASSOCIATION ON BEHALF OF THE BAR OF THE COMMONWEALTH <--> [THE PENNSYLVANIA BAR ASSOCIATION ON BEHALF OF THE BAR OF THE COMMONWEALTH]
String Mismatch: TOPSIDE <--> [TOPSIDE]
String Mismatch: THE MAPLEWOOD <--> [THE MAPLEWOOD]
String Mismatch: ADAM'S RESTAURANT <--> [ADAM'S RESTAURANT]
String Mismatch: NORDDEUTSCHER LLOYD BREMEN <--> [NORDDEUTSCHERRR LLOYD BREMEN]
String Mismatch: GARDNER & SMITH <--> [GARDNER & SMITH]
String Mismatch: FIFTH AVENUE RESTAURANT <--> [FIFTH AVENUE RESTAURANT]
String Mismatch: NORWEGIAN GOVERNMENT <--> [NORWEGIAN GOVERNMENT]
String Mismatch: TWENTIETH CENTURY ALDERMANIR ASSOCIATION <--> [TWENTIETH CENTURY ALDERMANIR ASSOCIATION]
String Mismatch: JOHN WANAMAKER <--> [JOHN WANAMAKER]
String Mismatch: RESTAURANT KONIGHOF <--> [RESTAURANT KONIGHOF]
String Mismatch: HAMBURG-AMERIKA LINIE <--> [HAMBURG-AMERIKA LINIE]
String Mismatch: PARK LANE <--> [PARK LANE]

In [58]:
dt_result

     pp_id  ratio
0        1  0.300
1        2  1.000
2        3  0.260
3        4  0.400
4        5  0.070
..     ...    ...
137    150  0.450
138    151  0.450
139    152  0.300
140    153  0.775
141    154  0.500

[142 rows x 2 columns]

In [59]:
total_tab = []
col_name = []
for model in models[:3] + ["dirty"]:
    print(model)
    
    table_results = pd.read_csv(f'evaluation/{model}_table_result.csv')
    table_results.set_index('pp_id', inplace=True)

    total_tab.append(parse_mean(table_results, f'total__{model}'))
    col_name.append(f'total__{model}')
    
    
    hos_results = table_results.loc[127:155]
    hos_results.reset_index()
    # hos_results = workflow_results[workflow_results['pp_id'] >= 127]
    total_tab.append(parse_mean(hos_results, f'hos__{model}'))
    
    col_name.append(f'hos__{model}')


    # flights_results = workflow_results[workflow_results['pp_id'] >= 111][workflow_results['pp_id'] <=126]
    flights_results = table_results.loc[111:127]
    flights_results.reset_index()
    total_tab.append(parse_mean(flights_results, f'flights__{model}'))
    col_name.append(f'flights__{model}')

    # ppp_results = workflow_results[workflow_results['pp_id'] >= 62][workflow_results['pp_id'] <=91]
    ppp_results = table_results.loc[62:91]
    ppp_results.reset_index()
    total_tab.append(parse_mean(ppp_results, f'ppp__{model}'))
    col_name.append(f'ppp__{model}')

    # dish_results = workflow_results[workflow_results['pp_id'] >= 92][workflow_results['pp_id'] <= 110]
    dish_results = table_results.loc[92:111]
    dish_results.reset_index()
    total_tab.append(parse_mean(dish_results, f'dish__{model}'))
    col_name.append(f'dish__{model}')

    # menu_results = workflow_results[workflow_results['pp_id'] < 31]
    menu_results = table_results.loc[:31]
    menu_results = menu_results.reset_index()
    total_tab.append(parse_mean(menu_results, f'menu__{model}'))
    col_name.append(f'menu__{model}')
    # chi_results = workflow_results[workflow_results['pp_id'] >= 31][workflow_results['pp_id'] <=61]
    chi_results = table_results.loc[31:62]
    chi_results = chi_results.reset_index()
    total_tab.append(parse_mean(chi_results, f'chi__{model}'))
    col_name.append(f'chi__{model}')
tab_perf = pd.concat(total_tab, axis=1)
tab_perf.columns = col_name
# print(wf_perf)
tab_perf = tab_perf.transpose()
tab_perf.to_csv('table_column_ratio_results_llama_mistral_gemma2.csv')

llama3.1
mistral
gemma2
dirty

In [60]:
dt_result.head()

   pp_id  ratio
0      1   0.30
1      2   1.00
2      3   0.26
3      4   0.40
4      5   0.07

In [61]:
stat = dt_result['ratio'].describe()
for idx in ['mean', 'std',	'min',	'max',	'25%',	'50%',	'75%']:
    print(stat.loc[idx])

0.39452944942381557
0.2798829350091044
0.0
1.0
0.15416666666666667
0.4
0.565

In [ ]:
hos_dt_results = dt_result[dt_result['pp_id'] >= 127]
stat = hos_dt_results['ratio'].describe()
for idx in ['mean', 'std',	'min',	'max',	'25%',	'50%',	'75%']:
    print(stat.loc[idx])

In [ ]:
flights_dt_results = dt_result[dt_result['pp_id'] >= 111][dt_result['pp_id'] <=126]
stat = flights_dt_results['ratio'].describe()
for idx in ['mean', 'std',	'min',	'max',	'25%',	'50%',	'75%']:
    print(stat.loc[idx])

In [ ]:
ppp_dt_results = dt_result[dt_result['pp_id'] >= 62][dt_result['pp_id'] <=91]
stat = ppp_dt_results['ratio'].describe()
for idx in ['mean', 'std',	'min',	'max',	'25%',	'50%',	'75%']:
    print(stat.loc[idx])

In [ ]:
dish_dt_result =dt_result[dt_result['pp_id'] >= 92][dt_result['pp_id'] <=110]
stat = dish_dt_result['ratio'].describe()
for idx in ['mean', 'std',	'min',	'max',	'25%',	'50%',	'75%']:
    print(stat.loc[idx])

In [ ]:
chi_dt_result =dt_result[dt_result['pp_id'] >= 31][dt_result['pp_id'] <=61]
stat = chi_dt_result['ratio'].describe()
for idx in ['mean', 'std',	'min',	'max',	'25%',	'50%',	'75%']:
    print(stat.loc[idx])

In [ ]:
menu_dt_result =dt_result[dt_result['pp_id'] < 31]

stat = menu_dt_result['ratio'].describe()
for idx in ['mean', 'std',	'min',	'max',	'25%',	'50%',	'75%']:
    print(stat.loc[idx])

## table eval ttest

# answer eval

In [62]:
par_folder = '/projects/bces/lanl2/LLM4DC'
datafile_path = f'{par_folder}/evaluation/answer_1-154_gt.json'
data = []
with open(datafile_path, 'r') as f:
    for l in f:
        data.append(json.loads(l))

In [63]:
from bert_score import score

In [64]:
import json
from typing import Union, List, Dict, Any
from difflib import SequenceMatcher
from math import isclose

# Define a utility to convert JSON strings to Python objects
def parse_input(answer: Union[str, float, List, Dict]) -> Any:
    if isinstance(answer, str):
        try:
            # Try to parse JSON strings into Python objects
            return json.loads(answer)
        except json.JSONDecodeError:
            return answer.lower().strip()  # Normalize strings for comparison
    elif isinstance(answer, float):
        return round(answer, 2)  # Round floats to two decimal places if needed
    return answer  # If already in desired format

# Calculate exact match accuracy
def accuracy_metric(gt: Any, pred: Any) -> float:
    return 1.0 if gt == pred else 0.0

# Calculate precision, recall, and F1 for lists (assuming items are unique)
def precision_recall_f1(gt: List, pred: List) -> Dict[str, float]:
    gt_set, pred_set = set(gt), set(pred)
    true_positives = len(gt_set & pred_set)
    precision = true_positives / len(pred_set) if pred_set else 0
    recall = true_positives / len(gt_set) if gt_set else 0
    f1_score = 2 * precision * recall / (precision + recall) if precision + recall > 0 else 0
    return {"precision": precision, "recall": recall, "f1": f1_score}

# Calculate semantic distance for string answers using sequence matching
def semantic_similarity(gt: str, pred: str) -> float:
    return SequenceMatcher(None, gt, pred).ratio()  # Returns a ratio between 0 and 1

# Evaluate an answer based on the ground truth
def calculate_answer_metrics(gt: Any, pred: Any) -> Dict[str, float]:
    # Parse inputs
    gt, pred = parse_input(gt), parse_input(pred)
    
    # Initialize results
    results = {"accuracy": 0, "semantic_similarity": 0, "precision": 0, "recall":0, "f1":0}
    
    # Check type and apply appropriate metrics
    if isinstance(gt, float) and isinstance(pred, float):
        results["accuracy"] = 1.0 if isclose(gt, pred, rel_tol=1e-2) else 0.0  # Accuracy for floats with tolerance
        precision, recall = results["accuracy"], results["accuracy"]
        results.update({"precision": precision, "recall": recall, "f1": 2 * precision * recall / (precision + recall) if precision + recall > 0 else 0})
        # results['bertscore'] = score([f"{pred}"], [f"{gt}"], lang='en', verbose=True)
        results["semantic_similarity"] = semantic_similarity(str(gt), str(pred))
    elif isinstance(gt, int) and isinstance(pred, int):
        results["accuracy"] = 1.0 if isclose(gt, pred, rel_tol=1e-2) else 0.0  # Accuracy for floats with tolerance
        precision, recall = results["accuracy"], results["accuracy"]
        results.update({"precision": precision, "recall": recall, "f1": 2 * precision * recall / (precision + recall) if precision + recall > 0 else 0})
        # results['bertscore'] = score([f"{pred}"], [f"{gt}"], lang='en', verbose=True)
        results["semantic_similarity"] = semantic_similarity(str(gt), str(pred))


    elif isinstance(gt, str) and isinstance(pred, str):
        results["accuracy"] = accuracy_metric(gt.lower(), pred.lower())
        precision, recall = results["accuracy"], results["accuracy"]
        results.update({"precision": precision, "recall": recall, "f1": 2 * precision * recall / (precision + recall) if precision + recall > 0 else 0})
        # results['bertscore'] = score([pred], [gt], lang='en', verbose=True)
        results["semantic_similarity"] = semantic_similarity(gt, pred)

    
    elif isinstance(gt, list) and isinstance(pred, list):
        if type(gt[0]) == str:
            gt = [x.lower() for x in gt]
            if len(pred) > 0:
                if type(pred[0]) == str:
                    pred = [x.lower() for x in pred]
        metrics = precision_recall_f1(gt, pred)
        results.update(metrics)
        results["accuracy"] = accuracy_metric(gt, pred)
        # results['bertscore'] = score([f"{pred}"], [f"{gt}"], lang='en', verbose=True)
        similarity = semantic_similarity(f"{gt}", f"{pred}")
        results["semantic_similarity"] = similarity

    
    elif isinstance(gt, dict) and isinstance(pred, dict):
        gt = {key.lower(): value for key, value in gt.items()}
        pred = {key.lower(): value for key, value in pred.items()}
        gt_keys, pred_keys = list(gt.keys()), list(pred.keys())
        if type(gt[gt_keys[0]]) == dict:
            precision_recall_f1_results = []
            for k in gt_keys:
                if k in pred.keys():
                    pred_input = pred[k].values()
                else:
                    pred_input = []
                precision_recall_f1_results.append(precision_recall_f1(gt[k].values(), pred_input))
            precision = sum([x['precision'] for x in precision_recall_f1_results])/len([x['precision'] for x in precision_recall_f1_results])
            recall = sum([x['recall'] for x in precision_recall_f1_results])/len([x['recall'] for x in precision_recall_f1_results])
            f1 =sum([x['f1'] for x in precision_recall_f1_results])/len([x['f1'] for x in precision_recall_f1_results])
            results.update({'precision': precision, 'recall':recall, 'f1': f1})  # Precision/Recall on keys

        elif type(gt[gt_keys[0]]) == list:
            precision_recall_f1_results = []
            for k in gt_keys:
                if k in pred:
                    pred_input = pred[k]
                else: 
                    pred_input = []
                if type(gt[k][0]) ==str:
                    gt_input = [x.lower() for x in gt[k]]
                    if len(pred_input) > 0:
                        if type(pred_input[0]) == str:
                            pred_input = [x.lower() for x in pred_input]    
                else:
                    gt_input = gt[k]
                precision_recall_f1_results.append(precision_recall_f1(gt[k], pred_input)) 
            precision = sum([x['precision'] for x in precision_recall_f1_results])/len([x['precision'] for x in precision_recall_f1_results])
            recall = sum([x['recall'] for x in precision_recall_f1_results])/len([x['recall'] for x in precision_recall_f1_results])
            f1 =sum([x['f1'] for x in precision_recall_f1_results])/len([x['f1'] for x in precision_recall_f1_results])
            results.update({'precision': precision, 'recall':recall, 'f1': f1})  # Precision/Recall on keys
        

        results["accuracy"] = accuracy_metric(gt, pred)
        # Check semantic similarity for each key-value pair
        similarity = [semantic_similarity(str(gt[k]), str(pred.get(k, ""))) for k in gt_keys]
        results["semantic_similarity"] = sum(similarity) / len(similarity) if similarity else 0
        
        # results['bertscore'] = score([f"{pred}"], [f"{gt}"], lang='en', verbose=True)
    p, r, f1 = score([f"{pred}"], [f"{gt}"], lang='en', verbose=True)
    results.update({'bertscore_p': p.detach().cpu().tolist(),
    'bertscore_r': r.detach().cpu().tolist(),
    'bertscore_f1': f1.detach().cpu().tolist()})
    # print(results)


    return results

In [42]:
test_json = "{\"Zip\":{\"0\":96701,\"1\":96704,\"2\":96707,\"3\":96708,\"4\":96749,\"5\":96750,\"6\":96754,\"7\":96791,\"8\":96813,\"9\":96814,\"10\":96815,\"11\":96816,\"12\":96817,\"13\":96821,\"14\":96825,\"15\":96826},\"LoanCount\":{\"0\":1,\"1\":1,\"2\":4,\"3\":1,\"4\":1,\"5\":1,\"6\":1,\"7\":1,\"8\":1,\"9\":1,\"10\":1,\"11\":2,\"12\":1,\"13\":1,\"14\":1,\"15\":1}}"

In [43]:
test_json = parse_input(test_json)

In [ ]:
test_json.keys()
test_json.get('Zip').values()

In [65]:
# LLM-based history update solution
import importlib.util
import inspect
from typing import List
import requests
import json
import re
import difflib
from collections import Counter
# from spellchecker import SpellChecker
from datetime import datetime
import pandas as pd
import ast
import random
import logging 
# from history_update_problem.call_or import export_rows
from call_or import *

# from evaluation.data_compare import calculate_answer_metrics


def load_answer_dataset(datafile_path):
    """
    load json file, each line is a json dictionary

    datafile_path: str
    return: data:  list_of_dictionary
    """
    data = []
    with open(datafile_path, 'r') as f:
        for l in f:
            data.append(json.loads(l))
    return data

def eval_answers(answer_gt_path, answer_preds_llama):
    answer_gt = load_answer_dataset(answer_gt_path)
    answer_gt = pd.DataFrame(answer_gt)
    answer_preds_llama = load_answer_dataset(answer_preds_llama)
    answer_preds_llama = pd.DataFrame(answer_preds_llama)
    answer_compare = answer_gt.merge(answer_preds_llama[['pp_id', 'answer']], on='pp_id', how='left', suffixes=('_gt', '_preds'))

    results = []
    for i, row in answer_compare.iterrows():
        
        gt = row['answer_gt']
        preds = row['answer_preds']
        
        single_result = calculate_answer_metrics(gt, preds)
        
        single_result['pp_id'] = row['pp_id']
        results.append(single_result)
        # break
    return pd.DataFrame(results)

In [66]:
# @title single eexample
answer_gt_path = 'evaluation/answer_1-154_gt.json'
answer_gt = load_answer_dataset(answer_gt_path)
answer_gt = pd.DataFrame(answer_gt)
answer_dirty = 'evaluation/answer_1-154_dirty.json'
answer_dirty = load_answer_dataset(answer_dirty)
answer_dirty = pd.DataFrame(answer_dirty)
answer_preds_llama = 'evaluation/answer_1-154_llama3.1.json'
answer_preds_llama = load_answer_dataset(answer_preds_llama)
answer_preds_llama = pd.DataFrame(answer_preds_llama)
answer_compare = answer_gt.merge(answer_preds_llama[['pp_id', 'answer']], on='pp_id', how='left', suffixes=('_gt', '_preds'))
# answer_compare = answer_gt.merge(answer_dirty[['pp_id', 'answer']], on='pp_id', how='left', suffixes=('_gt', '_preds'))

results = []
for i, row in answer_compare.iterrows():
    gt = row['answer_gt']
    preds = row['answer_preds']
    single_result = calculate_answer_metrics(gt, preds)
    single_result['pp_id'] = row['pp_id']
    print(gt, type(gt))
    print(preds, type(preds))
    results.append(single_result)
    break

pd.DataFrame(results)

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.21it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 849.22it/s]

done in 0.02 seconds, 48.08 sentences/sec
22 <class 'int'>
22 <class 'int'>

,accuracy,semantic_similarity,precision,recall,f1,bertscore_p,bertscore_r,bertscore_f1,pp_id
0,1.0,1.0,1.0,1.0,1.0,[1.0000004768371582],[1.0000004768371582],[1.0000004768371582],1

In [67]:
# 'dirty', 
models = ['llama3.1',  'mistral', 'gemma2','deepseek-r1']
for model in models[0:3] + ['dirty']: #['mistral', 'gemma2', 'llama3.1']:
    print(model)
    answer_gt_path = '/projects/bces/lanl2/LLM4DC/evaluation/answer_1-154_gt.json'
    # answer_preds_llama = '/projects/bces/lanl2/LLM4DC/evaluation/answer_1-154_llama3.1.json'
    # model = 'gemma2'
    # model = 'dirty'
    # model = 'llama3.1'
    # model = 'mistral'
    answer_preds = f'/projects/bces/lanl2/LLM4DC/evaluation/answer_1-154_{model}.json'
    # answer_preds = f'/projects/bces/lanl2/LLM4DC/evaluation/answer_1-110_dirty.json'
    eval_answer_results = eval_answers(answer_gt_path, answer_preds)
    eval_answer_results['bertscore_p'] = eval_answer_results['bertscore_p'].apply(lambda x: sum(x)/len(x) if len(x) > 0 else None)
    eval_answer_results['bertscore_r'] = eval_answer_results['bertscore_r'].apply(lambda x: sum(x)/len(x) if len(x) > 0 else None)
    eval_answer_results['bertscore_f1'] = eval_answer_results['bertscore_f1'].apply(lambda x: sum(x)/len(x) if len(x) > 0 else None)
    eval_answer_results.to_csv(f'/projects/bces/lanl2/LLM4DC/evaluation/{model}_answer_result.csv')

llama3.1

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.23it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 821.93it/s]

done in 0.02 seconds, 53.23 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.61it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 891.84it/s]

done in 0.02 seconds, 52.99 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.94it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 915.19it/s]

done in 0.02 seconds, 52.74 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 59.70it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 866.05it/s]

done in 0.05 seconds, 21.74 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.97it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 878.20it/s]

done in 0.02 seconds, 45.55 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.74it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 823.54it/s]

done in 0.03 seconds, 32.36 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 80.74it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 900.65it/s]

done in 0.02 seconds, 41.60 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.33it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 912.60it/s]

done in 0.02 seconds, 47.85 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.49it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 871.45it/s]

done in 0.02 seconds, 44.32 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.27it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 894.88it/s]

done in 0.02 seconds, 43.92 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.68it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 893.36it/s]

done in 0.02 seconds, 48.00 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.89it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 881.71it/s]

done in 0.02 seconds, 44.80 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 41.29it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 766.92it/s]

done in 0.04 seconds, 27.52 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.24it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 889.00it/s]

done in 0.02 seconds, 48.25 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 70.17it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 824.51it/s]

done in 0.02 seconds, 40.99 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 14.70it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 788.55it/s]

done in 0.09 seconds, 11.69 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 67.45it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 868.57it/s]

done in 0.02 seconds, 40.44 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.17it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 885.62it/s]

done in 0.04 seconds, 24.26 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 68.54it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 857.91it/s]

done in 0.02 seconds, 44.80 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.85it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 901.61it/s]

done in 0.02 seconds, 49.17 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 73.32it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 881.53it/s]

done in 0.02 seconds, 48.29 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.67it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 464.90it/s]

done in 0.02 seconds, 48.54 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 84.77it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 915.39it/s]

done in 0.02 seconds, 47.18 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.95it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 915.39it/s]

done in 0.02 seconds, 51.89 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.35it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 794.68it/s]

done in 0.02 seconds, 42.94 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 38.91it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 754.78it/s]

done in 0.04 seconds, 28.26 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.07it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 909.04it/s]

done in 0.02 seconds, 52.51 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 80.35it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 888.81it/s]

done in 0.02 seconds, 48.60 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 41.50it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 264.93it/s]

done in 0.03 seconds, 30.20 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.29it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 852.85it/s]

done in 0.02 seconds, 42.71 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.45it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 837.02it/s]

done in 0.03 seconds, 37.09 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.28it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 874.36it/s]

done in 0.02 seconds, 47.32 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.92it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 904.72it/s]

done in 0.02 seconds, 51.41 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 76.48it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 894.12it/s]

done in 0.02 seconds, 41.06 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.25it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 895.64it/s]

done in 0.02 seconds, 50.76 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.36it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 843.08it/s]

done in 0.02 seconds, 47.64 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 77.36it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 883.94it/s]

done in 0.02 seconds, 41.03 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 73.91it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 852.67it/s]

done in 0.03 seconds, 33.24 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.70it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 884.13it/s]

done in 0.02 seconds, 48.42 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 56.41it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 776.00it/s]

done in 0.04 seconds, 27.98 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 76.62it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 879.86it/s]

done in 0.02 seconds, 43.15 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.04it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 889.75it/s]

done in 0.02 seconds, 44.21 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 57.07it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 814.11it/s]

done in 0.03 seconds, 35.15 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.40it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 740.52it/s]

done in 0.02 seconds, 47.37 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.40it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 888.62it/s]

done in 0.02 seconds, 47.30 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.31it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 860.90it/s]

done in 0.02 seconds, 47.21 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.39it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 888.06it/s]

done in 0.02 seconds, 50.20 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.90it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 912.60it/s]

done in 0.02 seconds, 49.10 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.71it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 857.91it/s]

done in 0.04 seconds, 26.63 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.82it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 908.84it/s]

done in 0.02 seconds, 42.75 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 80.93it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 903.75it/s]

done in 0.02 seconds, 45.63 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.20it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 770.30it/s]

done in 0.02 seconds, 46.59 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 10.74it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 763.99it/s]

done in 0.11 seconds, 9.43 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 84.37it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 890.13it/s]

done in 0.03 seconds, 38.15 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.63it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 894.50it/s]

done in 0.02 seconds, 46.83 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 77.18it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 853.19it/s]

done in 0.02 seconds, 43.60 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 57.76it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 37.81it/s]

done in 0.06 seconds, 17.89 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.79it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 916.39it/s]

done in 0.02 seconds, 44.73 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 78.33it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 820.16it/s]

done in 0.02 seconds, 43.61 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.57it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 912.40it/s]

done in 0.02 seconds, 51.61 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.98it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 903.56it/s]

done in 0.02 seconds, 46.36 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.46it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 881.90it/s]

done in 0.02 seconds, 42.87 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.33it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 896.22it/s]

done in 0.02 seconds, 46.11 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.77it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 878.57it/s]

done in 0.02 seconds, 45.45 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.69it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 880.42it/s]

done in 0.02 seconds, 44.92 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.28it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 845.80it/s]

done in 0.02 seconds, 46.58 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 12.68it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 814.74it/s]

done in 0.09 seconds, 10.81 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 78.38it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 920.41it/s]

done in 0.02 seconds, 43.89 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 81.58it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 921.02it/s]

done in 0.02 seconds, 45.17 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 80.30it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 886.37it/s]

done in 0.03 seconds, 39.45 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 55.93it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 662.29it/s]

done in 0.03 seconds, 35.81 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 39.79it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 813.01it/s]

done in 0.04 seconds, 25.83 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 80.96it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 909.24it/s]

done in 0.02 seconds, 43.32 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 45.07it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 853.72it/s]

done in 0.04 seconds, 25.67 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.39it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 903.94it/s]

done in 0.02 seconds, 49.49 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 54.03it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 894.12it/s]

done in 0.03 seconds, 36.57 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.40it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 919.60it/s]

done in 0.02 seconds, 54.22 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.72it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 933.52it/s]

done in 0.02 seconds, 50.03 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.00it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 902.00it/s]

done in 0.02 seconds, 49.18 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.62it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 909.63it/s]

done in 0.02 seconds, 50.06 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 31.53it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 784.13it/s]

done in 0.04 seconds, 24.87 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.62it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 929.38it/s]

done in 0.02 seconds, 50.35 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.61it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 902.19it/s]

done in 0.02 seconds, 53.49 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 24.72it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 717.83it/s]

done in 0.05 seconds, 19.12 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.16it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 913.19it/s]

done in 0.02 seconds, 49.68 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 81.34it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 880.23it/s]

done in 0.02 seconds, 46.92 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.53it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 906.29it/s]

done in 0.02 seconds, 51.06 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 69.75it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 870.01it/s]

done in 0.02 seconds, 44.34 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.20it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 904.14it/s]

done in 0.02 seconds, 47.99 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 80.54it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 912.20it/s]

done in 0.02 seconds, 47.46 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 84.90it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 934.35it/s]

done in 0.02 seconds, 50.16 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 44.53it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 771.86it/s]

done in 0.03 seconds, 31.25 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 30.33it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 712.35it/s]

done in 0.05 seconds, 21.16 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 81.23it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 883.38it/s]

done in 0.02 seconds, 47.64 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 78.91it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 889.19it/s]

done in 0.02 seconds, 46.10 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 81.71it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 919.40it/s]

done in 0.02 seconds, 48.02 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 77.05it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 879.49it/s]

done in 0.02 seconds, 47.05 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 34.16it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 753.02it/s]

done in 0.04 seconds, 23.92 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.16it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 922.43it/s]

done in 0.02 seconds, 51.83 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.48it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 894.12it/s]

done in 0.02 seconds, 50.88 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.06it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 922.23it/s]

done in 0.02 seconds, 54.78 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.89it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 900.65it/s]

done in 0.02 seconds, 47.77 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 50.28it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 838.86it/s]

done in 0.06 seconds, 15.75 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.82it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 889.00it/s]

done in 0.02 seconds, 50.64 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 37.53it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 780.92it/s]

done in 0.04 seconds, 26.89 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.45it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 927.74it/s]

done in 0.02 seconds, 49.57 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 84.00it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 889.94it/s]

done in 0.02 seconds, 48.95 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.64it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 894.50it/s]

done in 0.02 seconds, 46.33 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.98it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 908.45it/s]

done in 0.02 seconds, 48.43 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 71.21it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 905.31it/s]

done in 0.02 seconds, 47.28 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 58.39it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 837.69it/s]

done in 0.03 seconds, 37.30 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.54it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 923.45it/s]

done in 0.02 seconds, 54.11 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.21it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 877.29it/s]

done in 0.04 seconds, 26.37 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.21it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 905.70it/s]

done in 0.02 seconds, 53.46 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.16it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 917.99it/s]

done in 0.02 seconds, 54.18 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 68.18it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 838.02it/s]

done in 0.02 seconds, 43.88 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 68.71it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 857.56it/s]

done in 0.02 seconds, 43.80 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.93it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 895.07it/s]

done in 0.02 seconds, 53.03 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 57.91it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 794.07it/s]

done in 0.03 seconds, 35.23 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 78.43it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 854.24it/s]

done in 0.08 seconds, 13.20 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.63it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 908.45it/s]

done in 0.02 seconds, 49.33 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.90it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 874.18it/s]

done in 0.03 seconds, 39.36 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 26.46it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 328.01it/s]

done in 0.05 seconds, 21.77 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 58.82it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 112.58it/s]

done in 0.04 seconds, 28.34 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 28.85it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 547.42it/s]

done in 0.05 seconds, 20.74 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 18.12it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 818.88it/s]

done in 0.06 seconds, 15.73 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 68.84it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 380.13it/s]

done in 0.02 seconds, 43.04 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 23.49it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 523.96it/s]

done in 0.05 seconds, 19.41 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 12.67it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 682.89it/s]

done in 0.09 seconds, 11.61 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.42it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 855.98it/s]

done in 0.02 seconds, 60.72 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 37.28it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 827.28it/s]

done in 0.03 seconds, 29.27 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 21.97it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 239.85it/s]

done in 0.06 seconds, 17.67 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.47it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 844.26it/s]

done in 0.02 seconds, 48.77 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 18.84it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 851.98it/s]

done in 0.08 seconds, 12.64 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 48.46it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 847.16it/s]

done in 0.03 seconds, 37.08 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.25it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 667.25it/s]

done in 0.02 seconds, 60.01 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 29.00it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 800.75it/s]

done in 0.07 seconds, 14.67 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 58.90it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 98.86it/s]

done in 0.03 seconds, 32.16 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 49.67it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 206.94it/s]

done in 0.03 seconds, 30.82 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 26.25it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 22.81it/s]

done in 0.09 seconds, 10.94 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 20.60it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 162.84it/s]

done in 0.06 seconds, 15.43 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 70.90it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 707.54it/s]

done in 0.04 seconds, 27.42 sentences/sec
mistral

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 74.37it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 876.37it/s]

done in 0.03 seconds, 37.38 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 80.25it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 886.56it/s]

done in 0.02 seconds, 41.82 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 34.05it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 394.02it/s]

done in 0.04 seconds, 25.73 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 55.16it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 380.78it/s]

done in 0.03 seconds, 38.35 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 27.34it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 269.66it/s]

done in 0.05 seconds, 21.55 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 43.49it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 861.78it/s]

done in 0.03 seconds, 33.22 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 14.82it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 461.06it/s]

done in 0.08 seconds, 13.28 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 33.45it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 446.01it/s]

done in 0.04 seconds, 27.03 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 79.52it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 479.73it/s]

done in 0.02 seconds, 48.74 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.99it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 346.24it/s]

done in 0.02 seconds, 55.39 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 34.61it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 539.18it/s]

done in 0.04 seconds, 27.99 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 75.76it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 211.37it/s]

done in 0.03 seconds, 39.30 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 23.47it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 773.71it/s]

done in 0.05 seconds, 18.95 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 66.37it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 68.19it/s]

done in 0.04 seconds, 23.97 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 76.64it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 862.67it/s]

done in 0.02 seconds, 40.63 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 46.82it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 673.68it/s]

done in 0.03 seconds, 34.44 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 26.71it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 805.05it/s]

done in 0.05 seconds, 21.07 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 41.17it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 883.57it/s]

done in 0.04 seconds, 28.56 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 66.23it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 839.03it/s]

done in 0.03 seconds, 39.06 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.00it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 889.75it/s]

done in 0.02 seconds, 47.73 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.86it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 893.74it/s]

done in 0.02 seconds, 48.58 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.98it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 920.41it/s]

done in 0.02 seconds, 48.70 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.62it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 875.45it/s]

done in 0.02 seconds, 45.83 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.96it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 916.79it/s]

done in 0.02 seconds, 49.52 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.19it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 924.06it/s]

done in 0.02 seconds, 50.76 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 39.32it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 846.14it/s]

done in 0.03 seconds, 28.78 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.67it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 915.59it/s]

done in 0.02 seconds, 50.19 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.76it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 928.15it/s]

done in 0.02 seconds, 46.31 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.65it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 911.81it/s]

done in 0.02 seconds, 49.29 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.09it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 909.04it/s]

done in 0.02 seconds, 49.36 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 69.54it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 273.32it/s]

done in 0.02 seconds, 40.05 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.55it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 923.45it/s]

done in 0.02 seconds, 52.08 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.44it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 889.38it/s]

done in 0.02 seconds, 53.05 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 77.22it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 895.45it/s]

done in 0.02 seconds, 47.24 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 31.51it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 666.19it/s]

done in 0.04 seconds, 25.62 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 53.66it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 897.18it/s]

done in 0.03 seconds, 34.53 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 33.02it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 132.93it/s]

done in 0.05 seconds, 21.25 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 34.28it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 715.87it/s]

done in 0.04 seconds, 25.44 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 50.84it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 824.68it/s]

done in 0.03 seconds, 32.34 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 53.22it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 774.71it/s]

done in 0.04 seconds, 28.27 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 81.11it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 870.19it/s]

done in 0.03 seconds, 38.03 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 37.67it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 479.90it/s]

done in 0.04 seconds, 28.43 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 49.13it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 342.81it/s]

done in 0.04 seconds, 26.19 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 70.49it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 882.08it/s]

done in 0.03 seconds, 35.37 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 12.27it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 879.31it/s]

done in 0.09 seconds, 10.95 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 40.94it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 460.46it/s]

done in 0.03 seconds, 30.51 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 63.62it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 255.24it/s]

done in 0.03 seconds, 39.04 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 57.35it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 850.43it/s]

done in 0.02 seconds, 43.96 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 33.29it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 808.46it/s]

done in 0.06 seconds, 15.95 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 73.41it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 873.27it/s]

done in 0.04 seconds, 24.49 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 38.95it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 834.69it/s]

done in 0.03 seconds, 32.59 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 69.38it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 824.19it/s]

done in 0.02 seconds, 43.23 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 30.11it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 893.93it/s]

done in 0.04 seconds, 24.49 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.18it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 744.33it/s]

done in 0.02 seconds, 60.25 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 47.05it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 842.23it/s]

done in 0.03 seconds, 30.36 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 55.28it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 892.22it/s]

done in 0.03 seconds, 33.92 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 72.24it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 876.00it/s]

done in 0.03 seconds, 39.88 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 22.96it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 490.79it/s]

done in 0.05 seconds, 19.62 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 79.10it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 893.36it/s]

done in 0.02 seconds, 41.25 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.15it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 921.02it/s]

done in 0.02 seconds, 58.33 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.72it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 875.82it/s]

done in 0.03 seconds, 36.82 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 32.69it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 539.18it/s]

done in 0.04 seconds, 26.89 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 53.83it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 873.27it/s]

done in 0.03 seconds, 31.10 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 76.64it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 741.57it/s]

done in 0.03 seconds, 36.28 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 20.34it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 424.87it/s]

done in 0.06 seconds, 17.41 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 76.99it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 482.21it/s]

done in 0.02 seconds, 45.03 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 76.92it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 856.50it/s]

done in 0.03 seconds, 36.29 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 39.53it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 874.18it/s]

done in 0.03 seconds, 31.89 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 57.06it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 847.68it/s]

done in 0.02 seconds, 42.78 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.26it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 911.81it/s]

done in 0.02 seconds, 63.30 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 14.87it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 682.33it/s]

done in 0.07 seconds, 13.48 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 20.29it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 435.68it/s]

done in 0.06 seconds, 16.31 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 84.66it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 898.33it/s]

done in 0.02 seconds, 42.28 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.30it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 908.05it/s]

done in 0.02 seconds, 49.19 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 72.59it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 881.53it/s]

done in 0.02 seconds, 40.60 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 41.74it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 116.69it/s]

done in 0.04 seconds, 26.20 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 34.12it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 667.03it/s]

done in 0.04 seconds, 27.91 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.28it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 821.45it/s]

done in 0.04 seconds, 25.38 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 32.81it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 209.33it/s]

done in 0.05 seconds, 20.83 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 44.22it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 410.12it/s]

done in 0.03 seconds, 33.47 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 30.89it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 631.20it/s]

done in 0.06 seconds, 16.10 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 75.71it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 129.65it/s]

done in 0.03 seconds, 30.37 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 33.97it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 508.28it/s]

done in 0.06 seconds, 17.56 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 21.42it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 709.82it/s]

done in 0.07 seconds, 15.24 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 19.22it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 892.41it/s]

done in 0.06 seconds, 16.55 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 61.64it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 874.36it/s]

done in 0.03 seconds, 37.99 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 28.43it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 819.04it/s]

done in 0.05 seconds, 18.38 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 72.21it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 375.97it/s]

done in 0.02 seconds, 40.05 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 23.12it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 858.26it/s]

done in 0.07 seconds, 13.77 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.59it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 855.81it/s]

done in 0.02 seconds, 57.73 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 66.06it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 892.60it/s]

done in 0.05 seconds, 22.22 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 46.62it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 816.97it/s]

done in 0.06 seconds, 16.21 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 15.12it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 737.27it/s]

done in 0.08 seconds, 12.37 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 41.04it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 885.25it/s]

done in 0.05 seconds, 21.89 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 35.67it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 860.90it/s]

done in 0.05 seconds, 19.47 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 17.62it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 861.25it/s]

done in 0.07 seconds, 14.67 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 32.72it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 403.03it/s]

done in 0.04 seconds, 24.93 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 15.31it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 749.12it/s]

done in 0.09 seconds, 11.09 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 17.39it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 854.59it/s]

done in 0.07 seconds, 13.53 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 15.60it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 872.90it/s]

done in 0.07 seconds, 14.46 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 49.50it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 830.88it/s]

done in 0.03 seconds, 34.48 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 54.10it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 710.30it/s]

done in 0.03 seconds, 30.23 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 21.95it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 82.43it/s]

done in 0.07 seconds, 14.83 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 84.72it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 860.55it/s]

done in 0.03 seconds, 35.76 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 33.16it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 735.46it/s]

done in 0.05 seconds, 21.04 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 70.41it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 901.42it/s]

done in 0.02 seconds, 40.40 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 23.89it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 387.29it/s]

done in 0.05 seconds, 18.90 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 81.90it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 908.64it/s]

done in 0.02 seconds, 40.75 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.59it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 874.00it/s]

done in 0.03 seconds, 38.63 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 80.03it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 850.60it/s]

done in 0.02 seconds, 40.38 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 57.21it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 877.47it/s]

done in 0.08 seconds, 12.49 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.04it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 900.65it/s]

done in 0.02 seconds, 48.14 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 80.67it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 924.06it/s]

done in 0.03 seconds, 38.39 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.47it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 909.63it/s]

done in 0.02 seconds, 45.16 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.47it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 908.84it/s]

done in 0.02 seconds, 51.03 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 68.44it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 817.76it/s]

done in 0.03 seconds, 34.85 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 67.51it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 842.40it/s]

done in 0.02 seconds, 40.24 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 32.31it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 486.92it/s]

done in 0.04 seconds, 25.72 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 48.57it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 811.75it/s]

done in 0.03 seconds, 29.75 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 70.22it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 881.34it/s]

done in 0.03 seconds, 31.91 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 60.60it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 863.38it/s]

done in 0.03 seconds, 32.05 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 51.81it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 207.31it/s]

done in 0.03 seconds, 30.32 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 10.94it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 859.66it/s]

done in 0.10 seconds, 9.78 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 27.93it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 328.86it/s]

done in 0.05 seconds, 21.27 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 34.60it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 95.66it/s]

done in 0.04 seconds, 22.78 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 25.29it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 612.22it/s]

done in 0.05 seconds, 21.86 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 69.97it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 786.04it/s]

done in 0.03 seconds, 30.62 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 21.50it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 839.20it/s]

done in 0.07 seconds, 14.77 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 29.34it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 607.61it/s]

done in 0.05 seconds, 19.32 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 858.08it/s]

done in 0.05 seconds, 21.30 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.65it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 903.94it/s]

done in 0.03 seconds, 34.07 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.26it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 895.26it/s]

done in 0.02 seconds, 45.96 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.42it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 259.56it/s]

done in 0.02 seconds, 41.64 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 38.36it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 882.83it/s]

done in 0.04 seconds, 25.89 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 66.73it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 831.54it/s]

done in 0.03 seconds, 32.54 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 72.63it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 513.88it/s]

done in 0.03 seconds, 37.83 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 39.20it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 657.62it/s]

done in 0.03 seconds, 29.90 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 32.02it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 423.32it/s]

done in 0.05 seconds, 21.51 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 72.52it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 863.74it/s]

done in 0.03 seconds, 34.68 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.39it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 893.36it/s]

done in 0.02 seconds, 46.97 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.98it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 893.55it/s]

done in 0.02 seconds, 48.85 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 57.49it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 416.97it/s]

done in 0.03 seconds, 35.11 sentences/sec
gemma2

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.15it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 868.03it/s]

done in 0.03 seconds, 33.69 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.59it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 901.23it/s]

done in 0.02 seconds, 50.09 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.52it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 914.99it/s]

done in 0.02 seconds, 47.70 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.60it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 893.55it/s]

done in 0.02 seconds, 43.12 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 29.64it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 266.51it/s]

done in 0.06 seconds, 16.84 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.15it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 909.24it/s]

done in 0.02 seconds, 48.46 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 42.40it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 892.79it/s]

done in 0.03 seconds, 32.42 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.08it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 906.48it/s]

done in 0.02 seconds, 46.30 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.02it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 906.88it/s]

done in 0.02 seconds, 49.10 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.68it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 917.19it/s]

done in 0.02 seconds, 49.71 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.43it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 890.51it/s]

done in 0.02 seconds, 49.00 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.36it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 898.91it/s]

done in 0.02 seconds, 49.46 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 41.24it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 756.00it/s]

done in 0.04 seconds, 25.85 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.43it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 893.74it/s]

done in 0.02 seconds, 47.71 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 78.61it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 860.37it/s]

done in 0.02 seconds, 47.37 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 76.06it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 887.68it/s]

done in 0.02 seconds, 44.87 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 65.23it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 866.05it/s]

done in 0.02 seconds, 40.65 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 78.60it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 866.41it/s]

done in 0.02 seconds, 45.89 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 68.02it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 839.36it/s]

done in 0.02 seconds, 41.98 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.84it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 903.56it/s]

done in 0.02 seconds, 54.63 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.54it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 896.79it/s]

done in 0.02 seconds, 52.46 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.45it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 838.36it/s]

done in 0.02 seconds, 47.66 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 81.56it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 911.61it/s]

done in 0.02 seconds, 46.72 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.28it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 926.30it/s]

done in 0.02 seconds, 53.08 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.16it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 895.45it/s]

done in 0.02 seconds, 52.67 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 30.12it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 343.54it/s]

done in 0.04 seconds, 23.95 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 69.32it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 894.50it/s]

done in 0.02 seconds, 43.30 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 81.93it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 925.28it/s]

done in 0.02 seconds, 47.32 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.10it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 899.49it/s]

done in 0.02 seconds, 52.93 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.27it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 911.01it/s]

done in 0.02 seconds, 55.57 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.85it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 895.64it/s]

done in 0.02 seconds, 53.06 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.41it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 919.60it/s]

done in 0.02 seconds, 49.92 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.38it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 902.39it/s]

done in 0.02 seconds, 54.52 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 78.15it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 857.56it/s]

done in 0.02 seconds, 45.44 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.31it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 888.25it/s]

done in 0.02 seconds, 51.86 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.23it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 887.87it/s]

done in 0.02 seconds, 51.08 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.29it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 906.88it/s]

done in 0.02 seconds, 53.83 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 84.42it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 920.21it/s]

done in 0.02 seconds, 50.25 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.25it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 792.42it/s]

done in 0.02 seconds, 50.01 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 52.63it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 834.19it/s]

done in 0.03 seconds, 37.10 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 81.04it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 883.20it/s]

done in 0.02 seconds, 49.32 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.96it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 905.90it/s]

done in 0.02 seconds, 51.65 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 57.16it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 846.65it/s]

done in 0.03 seconds, 39.27 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.91it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 897.75it/s]

done in 0.02 seconds, 54.12 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.71it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 917.59it/s]

done in 0.02 seconds, 53.38 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.17it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 843.42it/s]

done in 0.03 seconds, 28.75 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.80it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 892.98it/s]

done in 0.02 seconds, 54.41 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.16it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 905.31it/s]

done in 0.02 seconds, 54.96 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.13it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 920.61it/s]

done in 0.02 seconds, 50.99 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.48it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 914.79it/s]

done in 0.02 seconds, 51.03 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.35it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 905.90it/s]

done in 0.02 seconds, 47.67 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.47it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 871.82it/s]

done in 0.02 seconds, 51.53 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.90it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 763.99it/s]

done in 0.02 seconds, 46.20 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.92it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 910.42it/s]

done in 0.02 seconds, 51.70 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 80.99it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 888.81it/s]

done in 0.02 seconds, 47.51 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 68.32it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 868.93it/s]

done in 0.02 seconds, 41.11 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.25it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 868.21it/s]

done in 0.02 seconds, 44.42 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 81.44it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 898.91it/s]

done in 0.02 seconds, 44.02 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 78.71it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 907.47it/s]

done in 0.02 seconds, 43.98 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 78.78it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 898.72it/s]

done in 0.02 seconds, 48.57 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.25it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 896.22it/s]

done in 0.02 seconds, 46.36 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 40.48it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 921.62it/s]

done in 0.03 seconds, 31.28 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.82it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 496.90it/s]

done in 0.02 seconds, 40.48 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 33.13it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 531.40it/s]

done in 0.04 seconds, 25.86 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.88it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 890.51it/s]

done in 0.04 seconds, 23.71 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 34.85it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 313.19it/s]

done in 0.04 seconds, 26.22 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 26.30it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 834.36it/s]

done in 0.08 seconds, 13.23 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 40.19it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 735.33it/s]

done in 0.09 seconds, 11.50 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 37.50it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 843.42it/s]

done in 0.06 seconds, 16.01 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.75it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 763.29it/s]

done in 0.04 seconds, 25.73 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 10.40it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 741.70it/s]

done in 0.13 seconds, 7.79 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 24.05it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 394.54it/s]

done in 0.06 seconds, 16.26 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 22.55it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 743.54it/s]

done in 0.06 seconds, 17.43 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 26.32it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 396.25it/s]

done in 0.05 seconds, 21.04 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 66.54it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 260.86it/s]

done in 0.03 seconds, 37.64 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.02it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 897.18it/s]

done in 0.02 seconds, 49.18 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.04it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 864.98it/s]

done in 0.03 seconds, 35.13 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.47it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 868.57it/s]

done in 0.02 seconds, 44.41 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.35it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 898.72it/s]

done in 0.02 seconds, 45.91 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.22it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 886.56it/s]

done in 0.02 seconds, 51.29 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 35.27it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 773.86it/s]

done in 0.04 seconds, 26.32 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 38.44it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 560.81it/s]

done in 0.03 seconds, 30.97 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.40it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 899.29it/s]

done in 0.02 seconds, 53.57 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 24.15it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 437.50it/s]

done in 0.05 seconds, 20.27 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 79.13it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 917.59it/s]

done in 0.04 seconds, 27.24 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.50it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 892.60it/s]

done in 0.02 seconds, 48.14 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.01it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 895.84it/s]

done in 0.02 seconds, 50.14 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 62.92it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 888.62it/s]

done in 0.03 seconds, 35.37 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.97it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 876.37it/s]

done in 0.02 seconds, 47.79 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.60it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 857.03it/s]

done in 0.02 seconds, 49.31 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 79.29it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 895.84it/s]

done in 0.02 seconds, 46.15 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 33.51it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 770.30it/s]

done in 0.04 seconds, 25.77 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 15.90it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 356.20it/s]

done in 0.10 seconds, 9.95 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 78.25it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 424.31it/s]

done in 0.02 seconds, 46.09 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 39.39it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 411.33it/s]

done in 0.04 seconds, 28.26 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 76.96it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 454.42it/s]

done in 0.02 seconds, 46.52 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 79.19it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 862.85it/s]

done in 0.02 seconds, 44.73 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 18.44it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 243.97it/s]

done in 0.08 seconds, 12.76 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 68.59it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 895.26it/s]

done in 0.02 seconds, 44.01 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 63.18it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 867.49it/s]

done in 0.02 seconds, 43.95 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 62.09it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 273.28it/s]

done in 0.03 seconds, 34.99 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.32it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 857.20it/s]

done in 0.02 seconds, 62.17 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 23.64it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 846.82it/s]

done in 0.05 seconds, 21.17 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 39.02it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 886.56it/s]

done in 0.03 seconds, 31.77 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 43.46it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 790.33it/s]

done in 0.04 seconds, 28.44 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 66.96it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 898.33it/s]

done in 0.02 seconds, 45.22 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.68it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 889.57it/s]

done in 0.02 seconds, 41.67 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 45.62it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 919.20it/s]

done in 0.03 seconds, 33.39 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.06it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 522.98it/s]

done in 0.02 seconds, 50.47 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.62it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 896.79it/s]

done in 0.02 seconds, 56.30 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 57.65it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 869.65it/s]

done in 0.02 seconds, 40.25 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 80.98it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 857.56it/s]

done in 0.02 seconds, 51.14 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.37it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 919.20it/s]

done in 0.02 seconds, 52.93 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.09it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 893.36it/s]

done in 0.02 seconds, 53.31 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 80.12it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 860.37it/s]

done in 0.02 seconds, 44.28 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 80.10it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 809.87it/s]

done in 0.02 seconds, 42.28 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 80.35it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 840.04it/s]

done in 0.02 seconds, 47.36 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 72.48it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 816.81it/s]

done in 0.02 seconds, 49.45 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 54.17it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 756.68it/s]

done in 0.03 seconds, 31.01 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 70.70it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 857.20it/s]

done in 0.02 seconds, 47.83 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.79it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 844.94it/s]

done in 0.02 seconds, 60.51 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 66.49it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 853.19it/s]

done in 0.03 seconds, 34.75 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.21it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 904.33it/s]

done in 0.02 seconds, 46.51 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 69.34it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 783.98it/s]

done in 0.03 seconds, 38.73 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 78.89it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 895.84it/s]

done in 0.03 seconds, 37.78 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.01it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 489.70it/s]

done in 0.02 seconds, 40.36 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 51.63it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 823.70it/s]

done in 0.03 seconds, 30.26 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 49.82it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 839.20it/s]

done in 0.03 seconds, 37.13 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 34.61it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 710.66it/s]

done in 0.04 seconds, 28.05 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.02it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 906.88it/s]

done in 0.02 seconds, 45.37 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 59.97it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 886.56it/s]

done in 0.03 seconds, 32.42 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.37it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 895.45it/s]

done in 0.02 seconds, 49.38 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 81.96it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 864.27it/s]

done in 0.02 seconds, 53.54 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 73.85it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 893.93it/s]

done in 0.02 seconds, 47.19 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.57it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 841.22it/s]

done in 0.02 seconds, 43.45 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.05it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 905.31it/s]

done in 0.02 seconds, 47.46 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 59.01it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 896.03it/s]

done in 0.02 seconds, 40.18 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 64.35it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 891.84it/s]

done in 0.02 seconds, 46.51 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 57.20it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 864.45it/s]

done in 0.03 seconds, 37.97 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.07it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 359.78it/s]

done in 0.02 seconds, 58.01 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 53.01it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 888.62it/s]

done in 0.03 seconds, 37.17 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.15it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 848.19it/s]

done in 0.03 seconds, 36.81 sentences/sec
dirty

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 27.07it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 419.51it/s]

done in 0.04 seconds, 22.95 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 53.63it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 854.41it/s]

done in 0.02 seconds, 40.29 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.80it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 904.14it/s]

done in 0.02 seconds, 42.96 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 80.70it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 897.56it/s]

done in 0.02 seconds, 43.96 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 68.56it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 481.72it/s]

done in 0.04 seconds, 27.11 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 61.39it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 872.54it/s]

done in 0.02 seconds, 43.90 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 73.45it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 867.31it/s]

done in 0.03 seconds, 33.29 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 76.55it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 866.77it/s]

done in 0.03 seconds, 30.35 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.42it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 844.77it/s]

done in 0.02 seconds, 63.92 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.51it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 916.79it/s]

done in 0.02 seconds, 48.05 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 57.52it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 856.33it/s]

done in 0.02 seconds, 41.16 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.98it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 848.88it/s]

done in 0.02 seconds, 58.50 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 39.42it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 780.63it/s]

done in 0.04 seconds, 27.57 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 29.57it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 861.25it/s]

done in 0.05 seconds, 18.72 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 56.54it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 813.32it/s]

done in 0.02 seconds, 43.57 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 78.67it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 794.68it/s]

done in 0.02 seconds, 44.48 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 40.20it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 822.57it/s]

done in 0.04 seconds, 28.43 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 41.17it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 810.34it/s]

done in 0.03 seconds, 33.27 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 69.50it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 821.12it/s]

done in 0.03 seconds, 30.06 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.66it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 903.75it/s]

done in 0.02 seconds, 48.58 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.74it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 890.89it/s]

done in 0.02 seconds, 47.32 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.02it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 902.97it/s]

done in 0.02 seconds, 47.16 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 26.53it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 849.91it/s]

done in 0.05 seconds, 18.43 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.32it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 897.56it/s]

done in 0.02 seconds, 46.05 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 68.81it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 873.27it/s]

done in 0.03 seconds, 35.94 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 15.04it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 716.36it/s]

done in 0.07 seconds, 13.69 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.02it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 873.81it/s]

done in 0.02 seconds, 42.40 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 80.53it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 864.45it/s]

done in 0.03 seconds, 36.50 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.48it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 893.74it/s]

done in 0.02 seconds, 42.54 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 37.97it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 869.11it/s]

done in 0.05 seconds, 21.65 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 84.68it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 907.66it/s]

done in 0.02 seconds, 52.81 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 81.04it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 888.25it/s]

done in 0.02 seconds, 41.86 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 59.21it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 881.53it/s]

done in 0.02 seconds, 43.19 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 80.34it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 832.70it/s]

done in 0.02 seconds, 46.30 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.68it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 908.84it/s]

done in 0.03 seconds, 29.25 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 81.26it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 882.83it/s]

done in 0.02 seconds, 47.80 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.29it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 930.83it/s]

done in 0.03 seconds, 39.01 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 84.34it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 917.59it/s]

done in 0.02 seconds, 50.73 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.14it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 909.83it/s]

done in 0.02 seconds, 51.12 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 39.42it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 768.75it/s]

done in 0.03 seconds, 30.29 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 81.27it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 869.83it/s]

done in 0.02 seconds, 51.49 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.28it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 926.30it/s]

done in 0.02 seconds, 53.72 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 51.58it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 818.56it/s]

done in 0.03 seconds, 37.16 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.34it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 919.20it/s]

done in 0.02 seconds, 54.73 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.75it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 930.00it/s]

done in 0.02 seconds, 56.61 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 71.41it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 850.77it/s]

done in 0.02 seconds, 47.61 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 76.55it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 923.45it/s]

done in 0.04 seconds, 26.24 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.34it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 924.67it/s]

done in 0.02 seconds, 60.54 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.83it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 926.30it/s]

done in 0.02 seconds, 58.74 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.96it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 890.51it/s]

done in 0.02 seconds, 58.99 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 46.91it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 846.48it/s]

done in 0.03 seconds, 37.45 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.53it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 915.59it/s]

done in 0.02 seconds, 55.23 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.45it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 912.00it/s]

done in 0.02 seconds, 55.18 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 100.30it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 894.50it/s]

done in 0.02 seconds, 61.47 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 70.82it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 877.65it/s]

done in 0.02 seconds, 49.06 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.37it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 905.31it/s]

done in 0.02 seconds, 56.42 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.43it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 912.20it/s]

done in 0.02 seconds, 54.37 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.69it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 908.45it/s]

done in 0.02 seconds, 54.15 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.86it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 925.69it/s]

done in 0.02 seconds, 56.20 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 72.70it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 902.58it/s]

done in 0.02 seconds, 50.17 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.63it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 926.30it/s]

done in 0.02 seconds, 61.62 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.87it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 924.06it/s]

done in 0.02 seconds, 60.82 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.85it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 937.07it/s]

done in 0.02 seconds, 60.17 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.87it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 877.10it/s]

done in 0.02 seconds, 55.13 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.42it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 918.80it/s]

done in 0.02 seconds, 60.70 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.23it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 927.53it/s]

done in 0.02 seconds, 59.79 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 56.70it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 874.18it/s]

done in 0.03 seconds, 34.82 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 75.03it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 878.20it/s]

done in 0.02 seconds, 41.66 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 81.74it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 880.60it/s]

done in 0.02 seconds, 46.48 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 31.24it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 812.06it/s]

done in 0.04 seconds, 25.53 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 26.38it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 696.38it/s]

done in 0.04 seconds, 22.99 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 26.22it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 669.38it/s]

done in 0.05 seconds, 21.10 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 80.65it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 892.03it/s]

done in 0.05 seconds, 19.58 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 69.89it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 850.43it/s]

done in 0.04 seconds, 27.47 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 76.63it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 913.19it/s]

done in 0.02 seconds, 44.65 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 46.52it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 862.85it/s]

done in 0.03 seconds, 37.66 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.07it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 909.43it/s]

done in 0.02 seconds, 49.51 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 54.80it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 838.69it/s]

done in 0.03 seconds, 37.26 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 81.72it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 910.82it/s]

done in 0.02 seconds, 45.36 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 52.92it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 897.95it/s]

done in 0.03 seconds, 30.49 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 26.65it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 729.57it/s]

done in 0.05 seconds, 21.50 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 54.39it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 434.15it/s]

done in 0.03 seconds, 39.05 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 55.47it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 909.24it/s]

done in 0.02 seconds, 41.18 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 25.12it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 645.87it/s]

done in 0.05 seconds, 19.06 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 78.12it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 783.69it/s]

done in 0.02 seconds, 40.28 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 36.28it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 529.85it/s]

done in 0.04 seconds, 23.60 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.93it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 898.52it/s]

done in 0.02 seconds, 45.70 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 46.86it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 850.43it/s]

done in 0.03 seconds, 37.71 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 78.90it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 876.19it/s]

done in 0.02 seconds, 43.63 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 41.29it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 263.05it/s]

done in 0.04 seconds, 27.68 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 30.25it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 416.39it/s]

done in 0.04 seconds, 23.98 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 22.02it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 473.77it/s]

done in 0.06 seconds, 16.54 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 30.19it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 626.39it/s]

done in 0.08 seconds, 13.18 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 52.69it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 826.30it/s]

done in 0.02 seconds, 40.86 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 56.44it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 864.45it/s]

done in 0.03 seconds, 28.77 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 34.67it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 736.23it/s]

done in 0.10 seconds, 10.43 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 80.37it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 872.54it/s]

done in 0.02 seconds, 47.81 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 34.11it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 750.32it/s]

done in 0.06 seconds, 17.32 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 59.10it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 914.19it/s]

done in 0.02 seconds, 41.41 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 84.77it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 883.94it/s]

done in 0.03 seconds, 33.71 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 57.68it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 501.77it/s]

done in 0.03 seconds, 34.45 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 44.60it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 347.44it/s]

done in 0.03 seconds, 33.14 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 34.36it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 444.64it/s]

done in 0.04 seconds, 27.41 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.05it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 907.86it/s]

done in 0.03 seconds, 39.20 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 25.89it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 718.69it/s]

done in 0.05 seconds, 19.56 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.89it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 904.33it/s]

done in 0.02 seconds, 45.79 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.47it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 876.74it/s]

done in 0.02 seconds, 45.54 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 60.95it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 915.39it/s]

done in 0.03 seconds, 34.88 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 84.87it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 917.59it/s]

done in 0.02 seconds, 47.29 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.19it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 833.36it/s]

done in 0.03 seconds, 38.30 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 56.84it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 881.90it/s]

done in 0.02 seconds, 41.66 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.82it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 888.25it/s]

done in 0.03 seconds, 39.61 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 75.49it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 916.79it/s]

done in 0.02 seconds, 43.20 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 59.25it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 706.71it/s]

done in 0.02 seconds, 43.04 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.74it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 894.69it/s]

done in 0.02 seconds, 42.51 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 47.37it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 414.01it/s]

done in 0.03 seconds, 33.03 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 53.96it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 796.79it/s]

done in 0.03 seconds, 29.60 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 46.33it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 787.66it/s]

done in 0.03 seconds, 29.53 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 36.45it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 748.45it/s]

done in 0.04 seconds, 27.07 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.29it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 70.47it/s]

done in 0.03 seconds, 32.89 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.01it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 889.00it/s]

done in 0.02 seconds, 40.82 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 24.60it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 858.08it/s]

done in 0.05 seconds, 19.82 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 84.39it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 859.66it/s]

done in 0.03 seconds, 38.18 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.86it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 369.15it/s]

done in 0.02 seconds, 47.67 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 68.95it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 851.64it/s]

done in 0.03 seconds, 33.43 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 56.03it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 882.64it/s]

done in 0.03 seconds, 38.85 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 69.90it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 398.28it/s]

done in 0.03 seconds, 38.62 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.08it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 736.49it/s]

done in 0.03 seconds, 28.96 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 11.66it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 652.51it/s]

done in 0.10 seconds, 10.31 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 52.50it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 885.25it/s]

done in 0.03 seconds, 37.43 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 76.95it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 908.05it/s]

done in 0.02 seconds, 45.73 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 76.72it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 824.35it/s]

done in 0.03 seconds, 29.79 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.17it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 880.79it/s]

done in 0.02 seconds, 44.71 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 43.43it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 180.55it/s]

done in 0.07 seconds, 14.79 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 72.04it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 877.29it/s]

done in 0.03 seconds, 36.24 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 62.97it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 796.34it/s]

done in 0.02 seconds, 43.53 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.42it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 888.25it/s]

done in 0.03 seconds, 37.04 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.27it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 882.64it/s]

done in 0.02 seconds, 44.72 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.94it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 783.25it/s]

done in 0.02 seconds, 45.47 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.65it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 893.17it/s]

done in 0.02 seconds, 54.40 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.04it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 932.69it/s]

done in 0.02 seconds, 55.64 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.31it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 922.43it/s]

done in 0.02 seconds, 55.86 sentences/sec

In [68]:
def calculate_eval_stats(eval_answer_results_text):

    total_stat_table = eval_answer_results_text.describe().loc['mean']
    eval_answer_results_text.set_index('pp_id', inplace=True)

    hos_results = eval_answer_results_text.loc[127:155]
    hos_stat_table = hos_results.describe().loc['mean']
    # print('hos', hos_stat_table)

    flights_results = eval_answer_results_text.loc[111:127]
    flights_stat_table = flights_results.describe().loc['mean']

    ppp_results = eval_answer_results_text.loc[62:92] #[eval_answer_results_text['pp_id'] >= 62][eval_answer_results_text['pp_id'] <=91]
    ppp_stat_table = ppp_results.describe().loc['mean']

    dish_results = eval_answer_results_text.loc[92:111] #[eval_answer_results_text['pp_id'] >= 92]
    dish_stat_table = dish_results.describe().loc['mean']
    
    menu_results = eval_answer_results_text.loc[:31] #[eval_answer_results_text['pp_id'] < 31]
    menu_stat_table = menu_results.describe().loc['mean']

    chi_results = eval_answer_results_text.loc[31:62] #[eval_answer_results_text['pp_id'] >= 31][eval_answer_results_text['pp_id'] <=61]
    chi_stat_table = chi_results.describe().loc['mean']


    final_result = pd.concat([total_stat_table, menu_stat_table, dish_stat_table, chi_stat_table, ppp_stat_table, hos_stat_table, flights_stat_table], axis=1)
    final_result = final_result.transpose()
    final_result['data'] = ['Total', 'Menu', 'Dish', 'CFI','PPP', 'Hospital', 'Flights' ]
    return final_result

In [69]:
total_stat_df = []
for model in models[:3] + ['dirty']: #, 'llama3.1', 'mistral', 'gemma2']:
    eval_answer_results = pd.read_csv(f'/projects/bces/lanl2/LLM4DC/evaluation/{model}_answer_result.csv')
    # evaL_answer_results_flag = eval_answer_results.merge(numeric_pp_tag, on='pp_id', how='left', suffixes=('', '_numeric'))
    # eval_answer_results_text = evaL_answer_results_flag[evaL_answer_results_flag['flag'] == 0]
    final_stat = calculate_eval_stats(eval_answer_results)
    final_stat['model'] = [model] * 7
    total_stat_df.append(final_stat)
total_stat_df = pd.concat(total_stat_df, axis=0)
total_stat_df = total_stat_df.reset_index()
total_stat_df.iloc[:,2:]

,accuracy,semantic_similarity,precision,recall,f1,bertscore_p,bertscore_r,bertscore_f1,pp_id,data,model
0,0.373239,0.659084,0.493390,0.477637,0.477002,0.962967,0.962568,0.962485,76.739437,Total,llama3.1
1,0.322581,0.530480,0.476959,0.442979,0.442478,0.978846,0.972110,0.975181,NaN,Menu,llama3.1
2,0.176471,0.701403,0.326891,0.299241,0.307843,0.898197,0.912858,0.905092,NaN,Dish,llama3.1
3,0.483871,0.770539,0.644355,0.668011,0.648361,0.975466,0.973030,0.974068,NaN,CFI,llama3.1
4,0.434783,0.713796,0.581239,0.533191,0.544857,0.933808,0.942958,0.937943,NaN,PPP,llama3.1
5,0.500000,0.763193,0.549107,0.536905,0.541187,0.990591,0.991000,0.990773,NaN,Hospital,llama3.1
6,0.176471,0.379284,0.176471,0.176471,0.176471,0.979115,0.964792,0.971532,NaN,Flights,llama3.1
7,0.154930,0.474471,0.276792,0.246581,0.253126,0.938756,0.930821,0.934099,76.739437,Total,mistral
8,0.258065,0.441937,0.414747,0.325467,0.350158,0.971932,0.950788,0.960648,NaN,Menu,mistral
9,0.058824,0.545327,0.147059,0.147059,0.147059,0.863558,0.846879,0.853979,NaN,Dish,mistral
10,0.193548,0.571991,0.388441,0.344086,0.349644,0.940342,0.936550,0.937746,NaN,CFI,mistral
11,0.260870,0.538659,0.318150,0.322464,0.319089,0.902713,0.907679,0.904471,NaN,PPP,mistral
12,0.071429,0.451722,0.199580,0.190774,0.193249,0.969402,0.973264,0.971123,NaN,Hospital,mistral
13,0.117647,0.325599,0.117647,0.117647,0.117647,0.965187,0.947972,0.955957,NaN,Flights,mistral
14,0.478873,0.727479,0.576283,0.571509,0.567480,0.974242,0.970696,0.972279,76.739437,Total,gemma2
15,0.419355,0.652667,0.601654,0.560416,0.569438,0.984539,0.977171,0.980631,NaN,Menu,gemma2
16,0.411765,0.774473,0.605882,0.573624,0.583660,0.957709,0.937577,0.947106,NaN,Dish,gemma2
17,0.548387,0.799194,0.691052,0.736559,0.702568,0.969999,0.973017,0.971341,NaN,CFI,gemma2
18,0.652174,0.864741,0.737319,0.725932,0.727295,0.971398,0.969477,0.970361,NaN,PPP,gemma2
19,0.607143,0.813440,0.553571,0.553571,0.553571,0.989619,0.993538,0.991475,NaN,Hospital,gemma2
20,0.117647,0.374290,0.117647,0.117647,0.117647,0.964156,0.958738,0.961379,NaN,Flights,gemma2
21,0.126761,0.440209,0.205254,0.190663,0.188437,0.927601,0.932993,0.929594,76.739437,Total,dirty
22,0.225806,0.425082,0.351254,0.272918,0.291398,0.970948,0.954411,0.962275,NaN,Menu,dirty
23,0.058824,0.677156,0.147059,0.147059,0.147059,0.873260,0.894107,0.882798,NaN,Dish,dirty
24,0.161290,0.496739,0.251075,0.255376,0.231797,0.913808,0.929999,0.920975,NaN,CFI,dirty
25,0.260870,0.533461,0.331815,0.333204,0.330923,0.896283,0.916411,0.905723,NaN,PPP,dirty
26,0.000000,0.332942,0.047932,0.054762,0.050990,0.952814,0.966863,0.959561,NaN,Hospital,dirty
27,0.058824,0.195861,0.058824,0.058824,0.058824,0.944151,0.917961,0.929799,NaN,Flights,dirty

In [70]:
total_stat_df.to_csv('answer_performance_table_llama_gemma_mistral.csv', header=True, index=False)

## numeric tags

In [71]:
numeric_pp_tag = pd.read_csv('/projects/bces/lanl2/LLM4DC/evaluation/purposes_category.csv')
numeric_pp_tag.columns = ['pp_id', 'purposes', 'flag']

In [72]:
evaL_answer_results_flag = eval_answer_results.merge(numeric_pp_tag, on='pp_id', how='left', suffixes=('', '_numeric'))

In [73]:
eval_answer_results_text = evaL_answer_results_flag[evaL_answer_results_flag['flag'] == 0]

In [74]:
def eval_answers_numeric(answer_gt_path, answer_preds_llama):
    answer_gt = load_answer_dataset(answer_gt_path)
    answer_gt = pd.DataFrame(answer_gt)
    answer_preds_llama = load_answer_dataset(answer_preds_llama)
    answer_preds_llama = pd.DataFrame(answer_preds_llama)
    answer_compare = answer_gt.merge(answer_preds_llama[['pp_id', 'answer']], on='pp_id', how='left', suffixes=('_gt', '_preds'))
    answer_compare = answer_compare.merge(numeric_pp_tag, on='pp_id', how='left', suffixes=('', '_numeric'))
    answer_compare = answer_compare[answer_compare['flag'] == 1]
    answer_compare['answer_preds'] = pd.to_numeric(answer_compare['answer_preds'], errors='coerce')
    answer_compare['answer_gt'] = pd.to_numeric(answer_compare['answer_gt'], errors='coerce')
    answer_compare['difference'] = (answer_compare['answer_preds'] - answer_compare['answer_gt']).abs()/answer_compare['answer_gt']
    return answer_compare

In [75]:
total_stat_df = []
for model in ['dirty', 'mistral', 'gemma2', 'llama3.1']:
    answer_gt_path = '/projects/bces/lanl2/LLM4DC/evaluation/answer_1-154_gt.json'
    # answer_preds_llama = '/projects/bces/lanl2/LLM4DC/evaluation/answer_1-110_llama3.1.json'
    # model = 'gemma2'
    # model = 'dirty'
    # model = 'llama3.1'
    # model = 'mistral'
    answer_preds = f'/projects/bces/lanl2/LLM4DC/evaluation/answer_1-154_{model}.json'
    # answer_preds = f'/projects/bces/lanl2/LLM4DC/evaluation/answer_1-110_dirty.json'
    eval_answer_results = eval_answers_numeric(answer_gt_path, answer_preds)
    # eval_answer_results.to_csv(f'evaluation/numeric_answer_diff_{model}.csv')
    final_stat = calculate_eval_stats(eval_answer_results[['difference', 'pp_id']])
    final_stat['model'] = [model] * 7
    total_stat_df.append(final_stat)

In [76]:
total_stat_df = pd.concat(total_stat_df, axis=0)

In [77]:
total_stat_df.to_csv('numeric_answer_stats_llamma_mistral_gemma.csv')

In [37]:
dish_results = eval_answer_results_text[eval_answer_results_text['pp_id'] >= 92]
dish_stat_table = dish_results.describe().loc['mean']

In [ ]:
dish_stat_table

In [ ]:
eval_answer_results.describe()

In [78]:
ppp_results = eval_answer_results[eval_answer_results['pp_id'] >= 62][eval_answer_results['pp_id'] <=91]

/tmp/ipykernel_4172012/2424205661.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ppp_results = eval_answer_results[eval_answer_results['pp_id'] >= 62][eval_answer_results['pp_id'] <=91]

In [38]:
dish_results = eval_answer_results[eval_answer_results['pp_id'] >= 92]

In [ ]:
chi_results = eval_answer_results[eval_answer_results['pp_id'] >= 31][eval_answer_results['pp_id'] <=61]

In [66]:
menu_results = eval_answer_results[eval_answer_results['pp_id'] < 31]

In [79]:
ppp_results.describe()

           pp_id      answer_gt   answer_preds  flag  difference
count   7.000000       7.000000       7.000000   7.0    7.000000
mean   68.428571   53280.180327   53281.180327   1.0    0.057147
std     7.091242   57649.758793   57649.520360   0.0    0.151184
min    62.000000       0.862289       0.862289   1.0    0.000000
25%    63.500000    1005.000000    1007.000000   1.0    0.000000
50%    66.000000   37030.400000   37030.400000   1.0    0.000000
75%    72.500000   96760.000000   96761.500000   1.0    0.000015
max    79.000000  140400.000000  140400.000000   1.0    0.400000

In [ ]:
dish_results.describe()

In [ ]:
menu_results.describe()

In [ ]:
chi_results.describe()

In [71]:
eval_answer_results = pd.DataFrame(eval_answer_results)

In [ ]:
eval_answer_results['accuracy'].sum()

In [ ]:
eval_answer_results.describe()

## answer eval ttest

In [80]:
from scipy import stats

In [81]:
dirty_answer_result = pd.read_csv('/projects/bces/lanl2/LLM4DC/evaluation/dirty_answer_result.csv')
dirty_answer_result = dirty_answer_result.iloc[:,1:]
gemma2_answer_result = pd.read_csv('/projects/bces/lanl2/LLM4DC/evaluation/gemma2_answer_result.csv')
gemma2_answer_result = gemma2_answer_result.iloc[:, 1:]
llama_answer_result = pd.read_csv('/projects/bces/lanl2/LLM4DC/evaluation/llama3.1_answer_result.csv')
llama_answer_result = llama_answer_result.iloc[:,1:]
mistral_answer_result = pd.read_csv('/projects/bces/lanl2/LLM4DC/evaluation/mistral_answer_result.csv')
mistral_answer_result = mistral_answer_result.iloc[:,1:]

In [82]:
answer_result = llama_answer_result.merge(gemma2_answer_result, on='pp_id', how='left', suffixes=('_llama3.1', '_gemma2')).merge(mistral_answer_result, on='pp_id', how='left', suffixes=('', '_mistral'))

In [83]:
answer_result = answer_result.merge(dirty_answer_result, on='pp_id', how='left', suffixes=('', '_dirty'))

In [84]:
answer_result.columns

Index(['accuracy_llama3.1', 'semantic_similarity_llama3.1',
       'precision_llama3.1', 'recall_llama3.1', 'f1_llama3.1',
       'bertscore_p_llama3.1', 'bertscore_r_llama3.1', 'bertscore_f1_llama3.1',
       'pp_id', 'accuracy_gemma2', 'semantic_similarity_gemma2',
       'precision_gemma2', 'recall_gemma2', 'f1_gemma2', 'bertscore_p_gemma2',
       'bertscore_r_gemma2', 'bertscore_f1_gemma2', 'accuracy',
       'semantic_similarity', 'precision', 'recall', 'f1', 'bertscore_p',
       'bertscore_r', 'bertscore_f1', 'accuracy_dirty',
       'semantic_similarity_dirty', 'precision_dirty', 'recall_dirty',
       'f1_dirty', 'bertscore_p_dirty', 'bertscore_r_dirty',
       'bertscore_f1_dirty'],
      dtype='object')

In [85]:
metric_names = ['accuracy','semantic_similarity', 'precision', 'recall', 'f1', 'bertscore_p', 'bertscore_r','bertscore_f1']

In [86]:
ttest_result = []
for m in metric_names:
    model_list = models[:3] + ['dirty'] #['llama', 'gemma2', 'mistral', 'dirty']
    llama_result = stats.ttest_rel(answer_result[f'{m}_dirty'].values, answer_result[f'{m}_llama3.1'].values)
    gemma_result = stats.ttest_rel(answer_result[f'{m}_dirty'].values, answer_result[f'{m}_gemma2'].values)
    # print(answer_result[f'{m}_llama'].values)
    mistral_result = stats.ttest_ind(answer_result[f'{m}_dirty'].values, answer_result[f'{m}'].values)
    ttest_result.append({f'{m}':[llama_result.pvalue.item(), gemma_result.pvalue.item(), mistral_result.pvalue.item()]})
    # print(gemma_result)
    # print(mistral_result)
    # break

In [87]:
def ttest_answer(answer_result):
    ttest_result = []
    for m in metric_names:
        model_list = ['llama', 'gemma2', 'mistral', 'dirty']
        llama_result = stats.ttest_rel(answer_result[f'{m}_dirty'].values, answer_result[f'{m}_llama'].values)
        gemma_result = stats.ttest_rel(answer_result[f'{m}_dirty'].values, answer_result[f'{m}_gemma2'].values)
        # print(answer_result[f'{m}_llama'].values)
        mistral_result = stats.ttest_ind(answer_result[f'{m}_dirty'].values, answer_result[f'{m}'].values)
        ttest_result.append({f'{m}':[llama_result.pvalue.item(), gemma_result.pvalue.item(), mistral_result.pvalue.item()]})
    combined_data = {k: v for d in ttest_result for k, v in d.items()}

    ttest_result = pd.DataFrame(combined_data)
    return ttest_result

In [88]:
combined_data = {k: v for d in ttest_result for k, v in d.items()}

ttest_result = pd.DataFrame(combined_data)

In [89]:
ttest_result['model'] = ['llama3.1', 'gemma2', 'mistral']

In [90]:
ttest_result

,accuracy,semantic_similarity,precision,recall,f1,bertscore_p,bertscore_r,bertscore_f1,model
0,2.864563e-10,6.345800e-10,5.739748e-13,4.884652e-13,1.177774e-13,2.444723e-10,8.522843e-08,5.135466e-10,llama3.1
1,5.734715e-15,8.883108e-15,2.444326e-17,3.528703e-18,1.468522e-18,3.674575e-12,2.976615e-09,8.863923e-12,gemma2
2,4.967583e-01,4.435126e-01,1.272800e-01,2.021279e-01,1.383219e-01,2.057995e-01,8.279164e-01,6.203541e-01,mistral

In [91]:
ppp_results = answer_result[answer_result['pp_id'] >= 62][answer_result['pp_id'] <=91]
ppp_ttest = ttest_answer(ppp_results)

/tmp/ipykernel_4172012/3278763139.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ppp_results = answer_result[answer_result['pp_id'] >= 62][answer_result['pp_id'] <=91]

KeyError: 'accuracy_llama'

In [ ]:
ppp_ttest

In [ ]:
dish_result= answer_result[answer_result['pp_id'] >= 92]
dish_ttest = ttest_answer(dish_result)
dish_ttest

In [ ]:
menu_results = answer_result[answer_result['pp_id'] < 31]
menu_ttest = ttest_answer(menu_results)
menu_ttest

In [ ]:
chi_results = answer_result[answer_result['pp_id'] >= 31][answer_result['pp_id'] <=61]
chi_ttest = ttest_answer(chi_results)
chi_ttest

In [ ]:
ppp_results = answer_result[answer_result['pp_id'] >= 62][answer_result['pp_id'] <=91]
ppp_ttest = ttest_answer(ppp_results)
ppp_ttest

In [4]:
def json_to_custom_string(data):
    # Serialize JSON with indentation for readability within each nested structure
    json_str = json.dumps(data, indent=None, separators=(r'')
    
    # Insert newline only after each top-level key-value pair
    # This keeps inner lists and dicts intact without adding extra line breaks
    formatted_str = json_str[1:-1].replace('", "', '",\n"')  # Exclude outer braces for custom formatting
    return f"{{\n{formatted_str}\n}}"

In [ ]:
json.dumps(data, indent=1, sepera)

In [11]:
data = {'table_caption': 'A mix of simple bibliographic description of the menus', 'columns': ['id', 'name', 'sponsor', 'event', 'venue', 'place', 'physical_description', 'occasion', 'notes', 'call_number', 'keywords', 'language', 'date', 'location', 'location_type', 'currency', 'currency_symbol', 'status', 'page_count', 'dish_count'], 'table_column_priority': [['id', '12579', '25121', '21960'], ['name', '', '', ''], ['sponsor', 'TRUSTEES OF THE MISSOURI BOTANICAL GARDEN', 'HOLLAND HOUSE', 'BATTERY PARK HOTEL'], ['event', '11TH ANNUAL BANQUET', 'LUNCHEON', 'CHRISTMAS DINNER'], ['venue', 'PROF;', 'COMMERCIAL', 'COMMERCIAL'], ['place', 'SOUTHERN HOTEL,ST. LOUIS,MO.', '', 'ASHVILLE, NC'], ['physical_description', 'BROADSIDE; ILLUS; 5.5 X 8.75;', 'CARD;6X8.75;', 'BOOKLET; ILLUS; COL; 6 X 8;'], ['occasion', 'ANNUAL', 'DAILY;', 'RELIGIOUS HOLIDAY'], ['notes', 'WINES LISTED FOR EACH COURSE;', 'ENGLISH ON ONE SIDE,FRENCH ON ONE SIDE;', 'PRINTED ON PARCHMENT-LIKE PAPER; RED LION; DRAWING OF HOTEL; TIED WITH TWINE AND SEALING WAX; MOST OF BOOKLET CONSISTS OF INFORMATION AND PRAISE ABOUT THE HOTEL;'], ['call_number', '1900-2627', '1900-517', '1898-432'], ['keywords', '', '', ''], ['language', '', '', ''], ['date', '1900-03-31', '1900-01-25', '1898-12-25'], ['location', 'Trustees Of The Missouri Botanical Garden', 'Holland House', 'Battery Park Hotel'], ['location_type', '', '', ''], ['currency', '', 'Dollars', ''], ['currency_symbol', '', '$', ''], ['status', 'complete', 'complete', 'complete'], ['page_count', '2', '2', '16'], ['dish_count', '22.0', '546.0', '28.0']]}

In [27]:
data_str = '\{\n'
for key, value in data.items():
    if key in ['table_caption', 'columns']:
        data_str += f'{key}: {value},\n'
    else:
        data_str += key + ': [\n'
        for l in value:
            data_str += f'  {l},\n'
data_str += '  ]\n}'

In [ ]:
type(data_str)

In [ ]:
pprint.pprint(data_str)

In [10]:
import pandas as pd
import pprint

In [ ]:
pprint.pprint(json_to_custom_string(data))

In [28]:
paragraph = "[    {'from': ['Luncheon', 'lunch'], 'to': 'Luncheon'},    {'from': ['Dinner'], 'to': 'Dinner'},  # No change needed for Dinner    {'from': ['Breakfast'], 'to': 'Breakfast'},  # No change needed for Breakfast    {'from': ['', 'Unknown', None], 'to': 'Unknown'},  # Replace missing values with Unknown    {'from': ['Banquet', 'Annual Banquet'], 'to': 'Annual Banquet'},    {'from': ['Tiffin'], 'to': 'Tiffin'}  # No change needed for Tiffin]"

In [3]:
raw_string = """```python
[
    {'from': ['HONOLULU', 'Honolulu'], 'to': 'Honolulu'},
    {'from': ['KANEOHE'], 'to': 'Kaneohe'},  # corrected spelling
    {'from': ['KIHEI'], 'to': 'Kihei'},  # corrected spelling
    {'from': ['Kailua Kona', 'KAUNAKAKAI', 'WAIMANALO', 'Waimea', 'kalaheo', 'Kahului'], 'to': 'Unknown'},  # unknown cities
    {'from': ['HONOLULUulu'], 'to': 'Honolulu'}  # corrected spelling
]
```"""

In [4]:
result = re.findall(r'(\[(:?\n?.*\n?)*\])', raw_string, re.DOTALL)

In [5]:
if result:
        for r in result:
            raw_string = r[0]

In [ ]:
raw_string

In [ ]:
eval(raw_string)

In [26]:
paragraph = re.sub(r'#.*\{$', '{', paragraph, flags=re.MULTILINE)

In [29]:
result = re.findall(r'(\[(:?\n?(^#.*\{|]}).*\n?)*\])', paragraph, re.DOTALL)

In [ ]:
line = "{'city':['hhhh'] #????ddfgtecg"

In [ ]:
input = '''
[{'foo':'bar'} # 000asd
]'''
eval(input)

In [ ]:
paragraph

In [ ]:
import pandas as pd
import json

def df_to_table_format(df, table_caption):
    # Extract column headers and index to form the first row in the table
    columns = ["competition"] + df.columns.tolist()
    
    # Prepare rows by combining index and corresponding row values in the DataFrame
    table_column_priority = [columns]  # Start with header row
    for idx, row in df.iterrows():
        table_column_priority.append([idx] + row.tolist())
    
    # Create the dictionary in the required format
    table_data = {
        "table_caption": table_caption,
        "columns": columns,
        "table_column_priority": table_column_priority
    }
    
    # Convert to JSON string with indentation for readability
    return json.dumps(table_data, indent=2)

# Example DataFrame
data = {
    "total matches": ["55", "2", "5"],
    "cardiff win": ["19", "0", "2"],
    "draw": ["16", "27", "0"],
    "swansea win": ["20", "2", "3"]
}
index = ["league", "fa cup", "league cup"]

df = pd.DataFrame(data, index=index)

# Convert DataFrame to the specified format and print
table_format_json = df_to_table_format(df, "south wales derby")
print(table_format_json)

In [ ]:
import pandas as pd
import json

def df_to_table_format(df, table_caption):
    # Extract column headers and index to form the first row in the table
    columns = ["competition"] + df.columns.tolist()
    
    # Prepare rows by combining index and corresponding row values in the DataFrame
    table_column_priority = [columns]  # Start with header row
    for idx, row in df.iterrows():
        table_column_priority.append([idx] + row.tolist())
    
    # Create the dictionary in the required format
    table_data = {
        "table_caption": table_caption,
        "columns": columns,
        "table_column_priority": table_column_priority
    }
    
    # Format 'columns' as a compact list and use json.dumps for the rest
    columns_str = f'"columns": {json.dumps(columns)}'
    table_column_priority_str = f'"table_column_priority": {json.dumps(table_column_priority)}'
    caption_str = f'"table_caption": "{table_caption}"'
    
    # Concatenate each component into a final JSON format
    final_output = f'{{\n  {caption_str},\n  {columns_str},\n  {table_column_priority_str}\n}}'
    
    return final_output

# Example DataFrame
data = {
    "total matches": ["55", "2", "5"],
    "cardiff win": ["19", "0", "2"],
    "draw": ["16", "27", "0"],
    "swansea win": ["20", "2", "3"]
}
index = ["league", "fa cup", "league cup"]

df = pd.DataFrame(data, index=index)

# Convert DataFrame to the specified format and print
table_format_json = df_to_table_format(df, "south wales derby")
print(table_format_json)

In [ ]:
import pandas as pd
import json

def df_to_table_format(df, table_caption):
    # Prepare rows for table_column_priority
    table_column_priority = []
    
    # The first list is the competition names (the DataFrame index)
    table_column_priority.append(["competition"] + df.index.tolist())
    
    # Append each DataFrame column values to table_column_priority
    for col in df.columns:
        table_column_priority.append([col] + df[col].tolist())
    
    # Create the final dictionary
    table_data = {
        "table_caption": table_caption,
        "columns": ["competition"] + df.columns.tolist(),
        "table_column_priority": table_column_priority
    }
    
    return table_data

# Example DataFrame
data = {
    "total matches": ["55", "2", "5"],
    "cardiff win": ["19", "0", "2"],
    "draw": ["16", "27", "0"],
    "swansea win": ["20", "2", "3"]
}
index = ["league", "fa cup", "league cup"]

df = pd.DataFrame(data, index=index)

# Convert DataFrame to the specified format
table_format = df_to_table_format(df, "south wales derby")

# Print the output in the desired format
print(json.dumps(table_format, indent=2))