In [12]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [2]:
# models generation directory: LLM4DC/CoT.response
# predicted dataset by model:  LLM4DC/CoT.response/{model}/datasets_llm
# predicted workflow by model:  LLM4DC/CoT.response/{model}/recipes_llm
# predicted operations by model:  LLM4DC/CoT.response/{model}/operation
# logging:  LLM4DC/CoT.response/logging

# all the sample tables are under: LLM4DC/datasets
# query: 1-30 [menu]: LLM4DC/datasets/menu_datasets
# clean table (ground truth) LLM4DC/datasets/menu_datasets/clean_tables/
# clean workflow (silver ground truth):  LLM4DC/datasets/menu_datasets/workflows

# query: 31-61 [chicago]: LLM4DC/datasets/CFI_datasets
# clean table (ground truth): LLM4DC/datasets/CFI_datasets/cleaned_tables/
# clean workflow (silver ground truth):  LLM4DC/datasets/CFI_datasets/workflows

# query: 62-91 [ppp]:LLM4DC/datasets/ppp_datasets
# clean table (ground truth): LLM4DC/datasets/ppp_datasets/cleaned_tables/
# clean workflow (silver ground truth):  LLM4DC/datasets/ppp_datasets/workflows

# query: 92-110 [dish]: LLM4DC/datasets/dish_datasets
# clean table (ground truth): LLM4DC/datasets/dish_datasets/cleaned_tables/
# clean workflow (silver ground truth):  LLM4DC/datasets/dish_datasets/workflows

# query: 111-126 [flights]: LLM4DC/datasets/flights
# clean table (ground truth): LLM4DC/datasets/flights/cleaned_tables/flights_data_p{query_id}.csv
# clean workflow (silver ground truth):  LLM4DC/datasets/flights/workflows/flights_p{query_id}.json

# query: 127- 154 [hospital]: LLM4DC/datasets/hospital
# clean table (ground truth): LLM4DC/datasets/hospital/clean_tables/
# clean workflow (silver ground truth):  LLM4DC/datasets/hospital/workflows

In [13]:
import re

In [14]:
import json

In [15]:
import ast
# LLM-based history update solution
import importlib.util
import inspect
from typing import List
import requests
import json
import re
import difflib
from collections import Counter
# from spellchecker import SpellChecker
from datetime import datetime
import pandas as pd
import ast
import random
import logging 
# from history_update_problem.call_or import export_rows
from call_or import *
from evaluation import *

# Worflow eval

In [16]:
def eval_workflows(pp_id, gt_wf_fp, pred_wf_fp):
    # print(gt_wf_fp)
    gt_ops_list = parse_recipe(pp_id, recipe=gt_wf_fp)
    pred_ops_list = parse_recipe(pp_id, recipe=pred_wf_fp)
    return {'pp_id': pp_id, 'gt_ops': gt_ops_list[pp_id], 'pred_ops': pred_ops_list[pp_id]}
    # print(gt_ops_list)
    # print(pred_ops_list)


models = ['llama3.1',  'mistral', 'gemma2','deepseek-r1']
answer_gt_path = '/projects/bces/lanl2/LLM4DC/evaluation/answer_1-154_gt.json'
answer_preds_llama = '/projects/bces/lanl2/LLM4DC/evaluation/answer_1-154_llama3.1.json'


# eval_answer_results = eval_answers(answer_gt_path, answer_preds_llama)
# model = models[0]
wf_gt_folder = '/projects/bces/lanl2/LLM4DC/datasets'

query_contents = pd.read_csv('/projects/bces/lanl2/LLM4DC/purposes/all_purposes.csv')
    
ops_result = {}
for model in models[:3]:
    ops_list = []

    wf_pred_folder = f'/projects/bces/lanl2/LLM4DC/CoT.response/{model}/recipes_llm'
    for query_id in range(155):
        row = query_contents[query_contents['ID'] == query_id]
        if len(row) == 0:
            continue
        # if model == 'llama3.1':
        if query_id >126:
            #TODO: what's the point to have the target_path here? 
            target_path = f'{wf_gt_folder}/hospital/clean_tables/hos_pp{query_id}.csv'
            wf_gt_fp = f"{wf_gt_folder}/hospital/workflows/hos_p{query_id}.json"
            wf_pred_fp = f"{wf_pred_folder}/{model}_hos_test_p{query_id}.json"
        elif query_id >= 111 and query_id <=126:
            target_path = f'{wf_gt_folder}/flights/cleaned_tables/flights_data_p{query_id}.csv'
            wf_gt_fp = f"{wf_gt_folder}/flights/workflows/flights_p{query_id}.json"
            wf_pred_fp = f"{wf_pred_folder}/{model}_flights_test_p{query_id}.json"
        elif query_id >= 92 and query_id <=110:
            target_path = f'{wf_gt_folder}/dish_datasets/cleaned_tables/dish_sample_p{query_id}.csv'
            wf_gt_fp = f"{wf_gt_folder}/dish_datasets/workflows/dish_sample_p{query_id}.json"
            wf_pred_fp = f"{wf_pred_folder}/{model}_dish_test_p{query_id}.json"
        elif query_id >= 62 and query_id <= 91:
            target_path = f'{wf_gt_folder}/ppp_datasets/cleaned_tables/ppp_sample_p{query_id}.csv'
            wf_gt_fp = f"{wf_gt_folder}/ppp_datasets/workflows/ppp_sample_p{query_id}.json"
            wf_pred_fp = f"{wf_pred_folder}/{model}_ppp_test_p{query_id}.json"
        elif query_id >= 31 and query_id <= 61:
            target_path = f'{wf_gt_folder}/CFI_datasets/cleaned_tables/chi_sample_p{query_id}.csv'
            wf_gt_fp = f"{wf_gt_folder}/CFI_datasets/workflows/chi_sample_p{query_id}.json"
            wf_pred_fp = f"{wf_pred_folder}/{model}_chi_test_p{query_id}.json"

        elif query_id <31:
            target_path = f'{wf_gt_folder}/menu_datasets/clean_tables/menu_sample_p{query_id}'
            wf_gt_fp = f"{wf_gt_folder}/menu_datasets/workflows/menu_sample_p{query_id}.json"
            wf_pred_fp = f"{wf_pred_folder}/{model}_menu_test_p{query_id}.json"
        if wf_gt_fp and wf_pred_fp:
            ops_list.append(eval_workflows(query_id, wf_gt_fp, wf_pred_fp))
    ops_result[model] = pd.DataFrame(ops_list)
# ops_df = pd.DataFrame(ops_list)

In [17]:
def parse_mean(df, col_name):
    total_wf = df.describe().loc['mean']
    # total_wf.columns = [col_name] #rename(columns={"mean": col_name})
    return total_wf

In [50]:
llama = ops_result['llama3.1'].set_index('pp_id')

In [60]:
chi = llama.loc[31:61]

In [48]:
calculate_operation_metrics(chi['gt_ops'], chi['pred_ops']).describe()

       accuracy  precision     recall         f1
count      30.0  30.000000  30.000000  30.000000
mean        0.0   0.915556   0.471667   0.576852
std         0.0   0.185020   0.223356   0.173080
min         0.0   0.333333   0.200000   0.333333
25%         0.0   1.000000   0.270833   0.425000
50%         0.0   1.000000   0.450000   0.500000
75%         0.0   1.000000   0.666667   0.729167
max         0.0   1.000000   1.000000   0.888889

In [18]:
wf_length = []
total_wf = []
print(len(ops_result))
ppp_wf, dish_wf, menu_wf,chi_wf,hos_wf, flights_wf = [],[],[],[],[],[]
col_name = []
output_wf =  []
for key, value in ops_result.items():
    model = key
    ops_df = value
    ops_df['gt_ops_length'] = ops_df['gt_ops'].apply(len)
    ops_df['pred_ops_length'] = ops_df['pred_ops'].apply(len)
    ops_df['gt_ops_set_length'] = ops_df['gt_ops'].apply(lambda x: len(set(x)))
    ops_df['pred_ops_set_length'] = ops_df['pred_ops'].apply(lambda x: len(set(x)))

    ops_length_desc = ops_df.describe().loc['mean']
    ops_length_desc.columns = [model]
    wf_length.append(ops_length_desc)

    workflow_results = calculate_operation_metrics(ops_df['gt_ops'], ops_df['pred_ops'])
    workflow_results['pp_id'] = ops_df['pp_id']
    # print(workflow_results[workflow_results['pp_id'] == 127])
    workflow_results.set_index('pp_id', inplace=True)
    total_wf.append(parse_mean(workflow_results, f'total__{model}'))
    col_name.append(f'total__{model}')
    
    
    hos_results = workflow_results.loc[127:155]
    hos_results.reset_index()
    # hos_results = workflow_results[workflow_results['pp_id'] >= 127]
    total_wf.append(parse_mean(hos_results, f'hos__{model}'))
    
    col_name.append(f'hos__{model}')


    # flights_results = workflow_results[workflow_results['pp_id'] >= 111][workflow_results['pp_id'] <=126]
    flights_results = workflow_results.loc[111:127]
    flights_results.reset_index()
    total_wf.append(parse_mean(flights_results, f'flights__{model}'))
    col_name.append(f'flights__{model}')

    # ppp_results = workflow_results[workflow_results['pp_id'] >= 62][workflow_results['pp_id'] <=91]
    ppp_results = workflow_results.loc[62:91]
    ppp_results.reset_index()
    total_wf.append(parse_mean(ppp_results, f'ppp__{model}'))
    col_name.append(f'ppp__{model}')

    # dish_results = workflow_results[workflow_results['pp_id'] >= 92][workflow_results['pp_id'] <= 110]
    dish_results = workflow_results.loc[92:111]
    dish_results.reset_index()
    total_wf.append(parse_mean(dish_results, f'dish__{model}'))
    col_name.append(f'dish__{model}')

    # menu_results = workflow_results[workflow_results['pp_id'] < 31]
    menu_results = workflow_results.loc[:31]
    menu_results = menu_results.reset_index()
    total_wf.append(parse_mean(menu_results, f'menu__{model}'))
    col_name.append(f'menu__{model}')
    # chi_results = workflow_results[workflow_results['pp_id'] >= 31][workflow_results['pp_id'] <=61]
    chi_results = workflow_results.loc[31:62]
    chi_results = chi_results.reset_index()
    total_wf.append(parse_mean(chi_results, f'chi__{model}'))
    col_name.append(f'chi__{model}')
wf_perf = pd.concat(total_wf, axis=1)
wf_perf.columns = col_name
# print(wf_perf)
wf_perf = wf_perf.transpose()
wf_length = pd.concat(wf_length, axis=1)
wf_length.columns = list(ops_result.keys())
wf_length = wf_length.transpose()

3

In [19]:
wf_length

,pp_id,gt_ops_length,pred_ops_length,gt_ops_set_length,pred_ops_set_length
llama3.1,76.739437,7.091549,4.105634,3.394366,1.774648
mistral,76.739437,7.091549,3.323944,3.394366,1.767606
gemma2,76.739437,7.091549,4.978873,3.394366,2.140845

In [22]:
wf_perf = wf_perf.reset_index()
# wf_perf['dataset']

In [25]:
wf_perf = wf_perf[['index','accuracy',	'precision',	'recall',	'f1',	'pp_id']]

In [26]:
wf_perf.to_csv('workflow_results_llama_mistral_gemma2.csv')

In [19]:
ops_df['gt_ops_length'] = ops_df['gt_ops'].apply(len)
ops_df['pred_ops_length'] = ops_df['pred_ops'].apply(len)

In [20]:
ops_df['gt_ops_set_length'] = ops_df['gt_ops'].apply(lambda x: len(set(x)))
ops_df['pred_ops_set_length'] = ops_df['pred_ops'].apply(lambda x: len(set(x)))

In [21]:
ops_df.describe()

,pp_id,gt_ops_length,pred_ops_length,gt_ops_set_length,pred_ops_set_length
count,126.000000,126.000000,126.000000,126.000000,126.000000
mean,71.436508,6.865079,3.452381,3.341270,1.888889
std,46.519071,3.714519,2.334462,1.125435,0.981609
min,1.000000,1.000000,1.000000,1.000000,1.000000
25%,32.250000,4.250000,1.000000,3.000000,1.000000
50%,64.500000,6.000000,2.500000,4.000000,2.000000
75%,106.750000,9.000000,6.000000,4.000000,3.000000
max,154.000000,21.000000,8.000000,6.000000,5.000000

In [9]:
from evaluation import calculate_operation_metrics

In [22]:
workflow_results = calculate_operation_metrics(ops_df['gt_ops'], ops_df['pred_ops'])
workflow_results['pp_id'] = ops_df['pp_id']

In [23]:
workflow_results.to_csv(f'evaluation/workflow_result_{model}.csv')

In [25]:
workflow_results.describe()

         accuracy   precision      recall          f1       pp_id
count  126.000000  126.000000  126.000000  126.000000  126.000000
mean     0.071429    0.793519    0.478704    0.549969   71.436508
std      0.258567    0.341096    0.297356    0.266544   46.519071
min      0.000000    0.000000    0.000000    0.000000    1.000000
25%      0.000000    0.666667    0.250000    0.400000   32.250000
50%      0.000000    1.000000    0.500000    0.571429   64.500000
75%      0.000000    1.000000    0.666667    0.729167  106.750000
max      1.000000    1.000000    1.000000    1.000000  154.000000

In [26]:
ppp_ops = ops_df[ops_df['pp_id'] >= 62][ops_df['pp_id'] <=91]
ppp_ops.describe()

/tmp/ipykernel_4106111/3936841685.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ppp_ops = ops_df[ops_df['pp_id'] >= 62][ops_df['pp_id'] <=91]

,pp_id,gt_ops_length,pred_ops_length,gt_ops_set_length,pred_ops_set_length
count,22.000000,22.000000,22.000000,22.000000,22.000000
mean,73.000000,3.409091,5.136364,2.363636,2.818182
std,7.438638,1.842852,2.188617,1.255292,1.180652
min,62.000000,1.000000,1.000000,1.000000,1.000000
25%,67.250000,2.000000,5.000000,1.000000,2.000000
50%,72.500000,3.000000,6.000000,3.000000,3.000000
75%,77.750000,5.000000,6.750000,3.000000,3.000000
max,89.000000,6.000000,8.000000,4.000000,5.000000

In [27]:
hos_results = workflow_results[workflow_results['pp_id'] >= 127]
hos_results.describe()

       accuracy  precision     recall         f1       pp_id
count      28.0  28.000000  28.000000  28.000000   28.000000
mean        0.0   0.940476   0.488690   0.621684  140.500000
std         0.0   0.151903   0.182634   0.171073    8.225975
min         0.0   0.500000   0.250000   0.400000  127.000000
25%         0.0   1.000000   0.333333   0.475000  133.750000
50%         0.0   1.000000   0.500000   0.666667  140.500000
75%         0.0   1.000000   0.616667   0.750000  147.250000
max         0.0   1.000000   0.750000   0.857143  154.000000

In [28]:
flights_results = workflow_results[workflow_results['pp_id'] >= 111][workflow_results['pp_id'] <=126]
flights_results.describe()

/tmp/ipykernel_4106111/2866722024.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  flights_results = workflow_results[workflow_results['pp_id'] >= 111][workflow_results['pp_id'] <=126]

       accuracy  precision  recall   f1  pp_id
count       0.0        0.0     0.0  0.0    0.0
mean        NaN        NaN     NaN  NaN    NaN
std         NaN        NaN     NaN  NaN    NaN
min         NaN        NaN     NaN  NaN    NaN
25%         NaN        NaN     NaN  NaN    NaN
50%         NaN        NaN     NaN  NaN    NaN
75%         NaN        NaN     NaN  NaN    NaN
max         NaN        NaN     NaN  NaN    NaN

In [21]:
ppp_results = workflow_results[workflow_results['pp_id'] >= 62][workflow_results['pp_id'] <=91]
ppp_results.describe()

/tmp/ipykernel_3976518/1041013513.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ppp_results = workflow_results[workflow_results['pp_id'] >= 62][workflow_results['pp_id'] <=91]

        accuracy  precision     recall         f1      pp_id
count  22.000000  22.000000  22.000000  22.000000  22.000000
mean    0.227273   0.707576   0.852273   0.732287  73.000000
std     0.428932   0.283997   0.225568   0.223887   7.438638
min     0.000000   0.250000   0.333333   0.333333  62.000000
25%     0.000000   0.500000   0.750000   0.517857  67.250000
50%     0.000000   0.708333   1.000000   0.800000  72.500000
75%     0.000000   1.000000   1.000000   0.880952  77.750000
max     1.000000   1.000000   1.000000   1.000000  89.000000

In [22]:
dish_results = workflow_results[workflow_results['pp_id'] >= 92][workflow_results['pp_id'] <= 110]
dish_results.describe()

/tmp/ipykernel_3976518/2466038161.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  dish_results = workflow_results[workflow_results['pp_id'] >= 92][workflow_results['pp_id'] <= 110]

       accuracy  precision     recall         f1      pp_id
count   16.0000  16.000000  16.000000  16.000000   16.00000
mean     0.0625   0.906250   0.390625   0.515476  101.93750
std      0.2500   0.171796   0.203485   0.173702    5.65059
min      0.0000   0.500000   0.250000   0.333333   92.00000
25%      0.0000   0.916667   0.250000   0.400000   98.75000
50%      0.0000   1.000000   0.250000   0.400000  102.50000
75%      0.0000   1.000000   0.500000   0.595238  106.25000
max      1.0000   1.000000   1.000000   1.000000  110.00000

In [23]:
chi_results = workflow_results[workflow_results['pp_id'] >= 31][workflow_results['pp_id'] <=61]
chi_results.describe()

/tmp/ipykernel_3976518/2907689086.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  chi_results = workflow_results[workflow_results['pp_id'] >= 31][workflow_results['pp_id'] <=61]

        accuracy  precision     recall         f1      pp_id
count  30.000000  30.000000  30.000000  30.000000  30.000000
mean    0.033333   0.897222   0.431111   0.553889  45.500000
std     0.182574   0.269528   0.239121   0.227077   8.803408
min     0.000000   0.000000   0.000000   0.000000  31.000000
25%     0.000000   1.000000   0.250000   0.400000  38.250000
50%     0.000000   1.000000   0.366667   0.535714  45.500000
75%     0.000000   1.000000   0.575000   0.666667  52.750000
max     1.000000   1.000000   1.000000   1.000000  60.000000

In [24]:
chi_ops = ops_df[ops_df['pp_id'] >= 31][ops_df['pp_id'] <=61]

chi_ops.describe()

/tmp/ipykernel_3976518/2470253216.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  chi_ops = ops_df[ops_df['pp_id'] >= 31][ops_df['pp_id'] <=61]

,pp_id,gt_ops_length,pred_ops_length,gt_ops_set_length,pred_ops_set_length
count,30.000000,30.000000,30.000000,30.000000,30.000000
mean,45.500000,6.833333,2.666667,3.633333,1.733333
std,8.803408,2.901644,1.988473,0.999425,0.868345
min,31.000000,1.000000,1.000000,1.000000,1.000000
25%,38.250000,5.000000,1.000000,3.000000,1.000000
50%,45.500000,6.000000,2.000000,4.000000,2.000000
75%,52.750000,8.750000,4.000000,4.000000,2.000000
max,60.000000,13.000000,7.000000,6.000000,4.000000

In [25]:
menu_results = workflow_results[workflow_results['pp_id'] < 31]
menu_results.describe()

        accuracy  precision     recall         f1      pp_id
count  30.000000  30.000000  30.000000  30.000000  30.000000
mean    0.066667   0.555556   0.290000   0.363810  15.500000
std     0.253708   0.480129   0.291896   0.329866   8.803408
min     0.000000   0.000000   0.000000   0.000000   1.000000
25%     0.000000   0.000000   0.000000   0.000000   8.250000
50%     0.000000   0.833333   0.333333   0.450000  15.500000
75%     0.000000   1.000000   0.500000   0.642857  22.750000
max     1.000000   1.000000   1.000000   1.000000  30.000000

In [26]:
menu_ops = ops_df[ops_df['pp_id'] < 31]
menu_ops.describe()

,pp_id,gt_ops_length,pred_ops_length,gt_ops_set_length,pred_ops_set_length
count,30.000000,30.000000,30.000000,30.000000,30.000000
mean,15.500000,7.100000,1.866667,2.933333,1.300000
std,8.803408,3.575298,1.332183,1.080655,0.534983
min,1.000000,1.000000,1.000000,1.000000,1.000000
25%,8.250000,4.000000,1.000000,2.000000,1.000000
50%,15.500000,7.000000,1.000000,3.000000,1.000000
75%,22.750000,9.750000,2.000000,3.750000,1.750000
max,30.000000,13.000000,7.000000,5.000000,3.000000

# Dataset Eval

In [27]:
# def retrieve_tg_cols(tg_cols_fp="target_columns_list.csv"):
#     id_tg_cols = {}
#     tg_df = pd.read_csv(tg_cols_fp)
#     result_dict = tg_df.set_index('ID')['tg_columns'].to_dict()
#     return result_dict

In [34]:
result_dict = retrieve_tg_cols("/projects/bces/lanl2/LLM4DC/evaluation/target_column_list.csv")
print(result_dict)
# model = "llama3.1"
# model = "mistral"
# model = "gemma2"
# model = "dirty"
data_gt_folder = "/projects/bces/lanl2/LLM4DC/datasets"

for model in models[:3] + ["dirty"]:
    ratio_list = []
    for query_id in range(155):
        # print(query_id)
        tg_cols = result_dict.get(query_id)
        if tg_cols:
            if model=="dirty":
                if query_id >126:
                    target_path = f'{data_gt_folder}/hospital/clean_tables/hos_pp{query_id}.csv'
                    table_preds_path = f'/projects/bces/lanl2/LLM4DC/datasets/hospital/hos_data_p{query_id}.csv'
                elif query_id >= 111 and query_id <=126:
                    target_path = f'{data_gt_folder}/flights/cleaned_tables/flights_data_p{query_id}.csv'
                    table_preds_path = f'/projects/bces/lanl2/LLM4DC/datasets/flights/flights_data_p{query_id}.csv'
                    # target_path = None
                    # table_preds_path = None
                elif query_id >= 92 and query_id <=110:
                    target_path = f'{data_gt_folder}/dish_datasets/cleaned_tables/dish_sample_p{query_id}.csv'
                    table_preds_path = f'/projects/bces/lanl2/LLM4DC/datasets/dish_datasets/dish_data_p{query_id}.csv'
                elif query_id >= 62 and query_id <= 91:
                    target_path = f'{data_gt_folder}/ppp_datasets/cleaned_tables/ppp_sample_p{query_id}.csv'
                    table_preds_path =  f'/projects/bces/lanl2/LLM4DC/datasets/ppp_datasets/ppp_data_p{query_id}.csv'
                elif query_id >= 31 and query_id <= 61:
                    target_path = f'{data_gt_folder}/CFI_datasets/cleaned_tables/chi_sample_p{query_id}.csv'
                    table_preds_path = f'/projects/bces/lanl2/LLM4DC/datasets/CFI_datasets/chi_food_data_p{query_id}.csv'
                elif query_id <31:
                    target_path = f'{data_gt_folder}/menu_datasets/clean_tables/menu_sample_p{query_id}.csv'
                    table_preds_path = f'/projects/bces/lanl2/LLM4DC/datasets/menu_datasets/menu_p{query_id}.csv'
            else:
                llm_folder = f"CoT.response/{model}/datasets_llm"
                data_gt_folder = "/projects/bces/lanl2/LLM4DC/datasets"
                pred_fp = f'/projects/bces/lanl2/LLM4DC/{llm_folder}'
                if query_id >126:
                    target_path = f'{data_gt_folder}/hospital/clean_tables/hos_pp{query_id}.csv'
                    table_preds_path = f'{pred_fp}/{model}_hos_test_p{query_id}.csv'
                elif query_id >= 111 and query_id <=126:
                    target_path = f'{data_gt_folder}/flights/cleaned_tables/flights_data_p{query_id}.csv'
                    table_preds_path = f'{pred_fp}/{model}_flights_test_p{query_id}.csv'
                elif query_id >= 92 and query_id <=110:
                    target_path = f'{data_gt_folder}/dish_datasets/cleaned_tables/dish_sample_p{query_id}.csv'
                    table_preds_path = f'{pred_fp}/{model}_dish_test_p{query_id}.csv'
                elif query_id >= 62 and query_id <= 91:
                    target_path = f'{data_gt_folder}/ppp_datasets/cleaned_tables/ppp_sample_p{query_id}.csv'
                    table_preds_path = f'{pred_fp}/{model}_ppp_test_p{query_id}.csv'
                elif query_id >= 31 and query_id <= 61:
                    target_path = f'{data_gt_folder}/CFI_datasets/cleaned_tables/chi_sample_p{query_id}.csv'
                    table_preds_path = f'{pred_fp}/{model}_chi_test_p{query_id}.csv'
                elif query_id <31:
                    target_path = f'{data_gt_folder}/menu_datasets/clean_tables/menu_sample_p{query_id}.csv'
                    table_preds_path = f'{pred_fp}/{model}_menu_test_p{query_id}.csv'
            if target_path and table_preds_path:
                gt_df = pd.read_csv(target_path)
                preds_df = pd.read_csv(table_preds_path)
                # print(gt_df.head(5), preds_df.head(5))
                res = average_match_ratio(gt_df, preds_df, tg_cols)
                ratio_list.append({'pp_id': query_id, 'ratio': res})
    dt_result = pd.DataFrame(ratio_list)
    dt_result.to_csv(f'{model}_table_result.csv')

{1: 'page_count', 2: 'page_count', 3: 'event', 4: 'event', 5: 'event', 6: 'venue', 7: 'occasion', 8: 'occasion', 9: 'page_count, dish_count', 10: 'dish_count', 11: 'page_count, dish_count', 12: 'page_count, location', 13: 'sponsor, currency', 14: 'sponsor, dish_count', 15: 'sponsor, event', 16: 'sponsor, event', 17: 'sponsor, event', 18: 'sponsor, event', 19: 'page_count, venue', 20: 'sponsor', 21: 'event', 22: 'occasion', 23: 'venue, dish_count', 24: 'status', 25: 'sponsor, currency', 26: 'date', 27: 'date, page_count, dish_count', 28: 'page_count, venue', 29: 'occasion', 30: 'currency', 31: 'Risk', 32: 'Results', 33: 'Facility Type', 34: 'Facility Type', 35: 'Inspection Type', 36: 'DBA Name, Results', 37: 'DBA Name, Results', 38: 'Facility Type, Risk', 39: 'Facility Type, Risk', 40: 'Facility Type, Risk', 41: 'Facility Type, Risk', 42: 'Facility Type, Risk', 43: 'Facility Type, Results', 44: 'Results', 45: 'Facility Type, Inspection ID', 46: 'Risk', 47: 'Facility Type, Results', 48: 'DBA Name, Inspection ID', 49: 'Facility Type, Risk, Results', 50: 'Inspection Type', 51: 'Facility Type,Results', 52: 'Address, Risk, Results', 53: 'Risk, Results', 54: 'Inspection Date', 55: 'DBA Name', 56: 'License #, Results', 57: 'DBA Name, Risk, Inspection Date', 58: 'Facility Type, Risk', 59: 'DBA Name, Inspection Date', 60: 'Facility Type, Inspection ID, Inspection Date', 62: 'LoanAmount', 63: 'LoanAmount', 64: 'LoanAmount', 65: 'NAICSCode, JobsReported', 66: 'JobsReported, LoanAmount', 67: 'City', 68: 'BusinessType, LoanAmount', 69: 'BusinessType, LoanAmount', 70: 'BusinessType, LoanAmount', 71: 'BusinessType, Zip', 72: 'Zip, LoanAmount', 73: 'Zip, LoanAmount', 74: 'Gender, LoanAmount', 75: 'Gender, LoanAmount', 76: 'City, LoanAmount', 77: 'City, LoanAmount', 78: 'Zip, LoanAmount', 79: 'Zip, LoanAmount', 80: 'RaceEthnicity, LoanAmount', 81: 'RaceEthnicity, LoanAmount', 87: 'City, LoanAmount, JobsReported', 89: 'City, LoanAmount, State, Zip', 92: 'times_appeared', 93: 'name, first_appeared, last_appeared', 94: 'name, first_appeared, last_appeared', 98: 'name, lowest_price', 99: 'name, highest_price', 100: 'name, first_appeared', 101: 'name, first_appeared', 102: 'name, menus_appeared', 103: 'name, menus_appeared', 104: 'name, times_appeared, highest_price', 105: 'name, times_appeared, lowest_price', 106: 'name, highest_price, lowest_price', 107: 'name, highest_price, lowest_price', 108: 'name,  highest_price, lowest_price', 109: 'name, menus_appeared, times_appeared', 110: 'name, times_appeared, highest_price, \nlowest_price', 111: 'sched_dep_time, act_dep_time', 112: 'sched_dep_time, sched_arr_time', 113: 'src, sched_dep_time, act_dep_time', 114: 'src', 115: 'flight', 116: 'sched_arr_time', 117: 'src, act_arr_time, sched_arr_time', 118: 'sched_dep_time, act_dep_time', 119: 'sched_arr_time', 120: 'src, sched_dep_time, act_dep_time', 121: 'act_dep_time, sched_dep_time', 122: 'act_dep_time, act_arr_time', 123: 'sched_dep_time, act_dep_time', 124: 'sched_arr_time, act_arr_time', 125: 'src, sched_dep_time, act_dep_time', 126: 'sched_arr_time, act_arr_time', 127: 'City', 128: 'City', 129: 'CountyName', 130: 'HospitalType, CountyName, EmergencyService', 131: 'HospitalOwner, City, ZipCode', 132: 'HospitalName, HospitalType, HospitalOwner', 133: 'EmergencyService, HospitalType', 134: 'HospitalType, HospitalOwner', 135: 'CountyName, EmergencyService', 136: 'City, HospitalOwner, EmergencyService', 137: 'CountyName, HospitalType', 138: 'HospitalType, HospitalOwner, City', 139: 'ZipCode, HospitalType, HospitalOwner', 140: 'City, HospitalType', 141: 'HospitalType, City, ZipCode', 142: 'EmergencyService, HospitalType', 143: 'CountyName, HospitalOwner, HospitalType', 144: 'HospitalOwner, EmergencyService', 145: 'City, EmergencyService', 146: 'HospitalType, ZipCode', 147: 'HospitalOwner, HospitalType', 148: 'EmergencyService, CountyName', 149: 'HospitalOwner, ZipCode, HospitalType', 150: 'HospitalType, EmergencyService', 151: 'City, HospitalOwner, HospitalType', 152: 'HospitalOwner, City', 153: 'ZipCode, EmergencyService', 154: 'City, HospitalOwner'}
16 <-!=->  16.0
4 <-!=->  4.0
4 <-!=->  4.0
4 <-!=->  4.0
4 <-!=->  4.0
4 <-!=->  4.0
4 <-!=->  4.0
4 <-!=->  4.0
3 <-!=->  3.0
2 <-!=->  2.0
2 <-!=->  2.0
2 <-!=->  2.0
2 <-!=->  2.0
2 <-!=->  2.0
2 <-!=->  2.0
2 <-!=->  2.0
2 <-!=->  2.0
2 <-!=->  2.0
2 <-!=->  2.0
2 <-!=->  2.0
2 <-!=->  2.0
2 <-!=->  2.0
2 <-!=->  2.0
2 <-!=->  2.0
2 <-!=->  2.0
2 <-!=->  2.0
2 <-!=->  2.0
2 <-!=->  2.0
2 <-!=->  2.0
2 <-!=->  2.0
2 <-!=->  2.0
2 <-!=->  2.0
16 <-!=->  16.0
2 <-!=->  2.0
4 <-!=->  4.0
4 <-!=->  4.0
4 <-!=->  4.0
5 <-!=->  5.0
3 <-!=->  3.0
4 <-!=->  4.0
2 <-!=->  2.0
1 <-!=->  1.0
4 <-!=->  4.0
2 <-!=->  2.0
4 <-!=->  4.0
2 <-!=->  2.0
8 <-!=->  8.0
6 <-!=->  6.0
2 <-!=->  2.0
5 <-!=->  5.0
2 <-!=->  2.0
11 <-!=->  11.0
4 <-!=->  4.0
1 <-!=->  1.0
5 <-!=->  5.0
2 <-!=->  2.0
3 <-!=->  3.0
14 <-!=->  14.0
4 <-!=->  4.0
1 <-!=->  1.0
8 <-!=->  8.0
4 <-!=->  4.0
4 <-!=->  4.0
4 <-!=->  4.0
2 <-!=->  2.0
2 <-!=->  2.0
12 <-!=->  12.0
2 <-!=->  2.0
4 <-!=->  4.0
4 <-!=->  4.0
2 <-!=->  2.0
1 <-!=->  1.0
2 <-!=->  2.0
2 <-!=->  2.0
2 <-!=->  2.0
2 <-!=->  2.0
20 <-!=->  20.0
2 <-!=->  2.0
3 <-!=->  3.0
2 <-!=->  2.0
4 <-!=->  4.0
2 <-!=->  2.0
2 <-!=->  2.0
2 <-!=->  2.0
4 <-!=->  4.0
3 <-!=->  3.0
2 <-!=->  2.0
2 <-!=->  2.0
4 <-!=->  4.0
1 <-!=->  1.0
1 <-!=->  1.0
4 <-!=->  4.0
2 <-!=->  2.0
2 <-!=->  2.0
1 <-!=->  1.0
4 <-!=->  4.0
2 <-!=->  2.0
4 <-!=->  4.0
2 <-!=->  2.0
22 <-!=->  22.0
2 <-!=->  2.0
3 <-!=->  3.0
2 <-!=->  2.0
1 <-!=->  1.0
2 <-!=->  2.0
2 <-!=->  2.0
1 <-!=->  1.0
2 <-!=->  2.0
2 <-!=->  2.0
4 <-!=->  4.0
1 <-!=->  1.0
4 <-!=->  4.0
2 <-!=->  2.0
4 <-!=->  4.0
2 <-!=->  2.0
2 <-!=->  2.0
2 <-!=->  2.0
8 <-!=->  8.0
3 <-!=->  3.0
2 <-!=->  2.0
6 <-!=->  6.0
8 <-!=->  8.0
4 <-!=->  4.0
2 <-!=->  2.0
8 <-!=->  8.0
4 <-!=->  4.0
5 <-!=->  5.0
4 <-!=->  4.0
8 <-!=->  8.0
2 <-!=->  2.0
BANQUET <-->  11TH ANNUAL BANQUET
LUNCHEON <-->  Dinner
DINNER <-->  CHRISTMAS DINNER
LUNCHEON <-->  LUNCHEON TENDERED IMPERIAL COUNCIL
BREAKFAST <-->  Dinner
BANQUET <-->  Dinner
15NTH BURNS ANNIVERSARY <-->  Dinner
BREAKFAST <-->  Dinner
BREAKFAST <-->  Dinner
DINNER <-->  DINNER (?)
BANQUET <-->  BANQUET AND RECEPTION COMMEMORATING 50 YEARS SINCE THE ADMISSION OF HONORABLE JAMES TYNDALE MITCHELL,LL.D. CHIEF JUSTICE OF THE SUPREME COURT OF PA TO THE BAR OF PHILADELPHIA
TIFFIN <-->  Dinner
DINNER <-->  DAILY MENU, DINNER
BANQUET <-->  THIRD ANNUAL BANQUET
TIFFIN <-->  Dinner
LUNCHEON <-->  Dinner
BANQUET <-->  Dinner
BANQUET <-->  ALL AMERICAN BANQUET IN HONOR OF EDWIN C. HALL
BANQUET <-->  Dinner
11TH ANNUAL BANQUET <-->  Other
BREAKFAST <-->  Other
FOURTH ANNUSL DINNER <-->  DINNER
BREAKFAST <-->  Other
PRIVATE BANQUET <-->  Other
BREAKFAST <-->  Other
MENU <-->  DINNER
BREAKFAST MENU <-->  Other
ZWEITES FRUHSTUCK <-->  BREAKFAST
DINNER <-->  Other
FRUHSTUCK <-->  BREAKFAST
LUNCH <-->  Other
TIFFIN <-->  Other
BREAKFAST <-->  Other
BREAKFAST <-->  Other
DAILY MENU, DINNER <-->  DINNER
THIRD ANNUAL BANQUET <-->  BANQUET
LUNCH <-->  Other
PERSONALLY CONDUCTED TOUR THROUGH MEXICO & CALIFORNIA <-->  TOUR
TIFFIN <-->  Other
FIRST ANNUAL BANQUET <-->  BANQUET
BREAKFAST <-->  Other
ANNUAL BANQUET <-->  BANQUET
11TH ANNUAL BANQUET <-->  Lunch
LUNCHEON <-->  Lunch
FOURTH ANNUSL DINNER <-->  Dinner
LUNCHEON <-->  Lunch
LUNCH AND DINNER <-->  Lunch
PRIVATE BANQUET <-->  Lunch
15NTH BURNS ANNIVERSARY <-->  Dinner
SECOND ANNUAL DINNER <-->  Dinner
BREAKFAST MENU <-->  Dinner
ZWEITES FRUHSTUCK <-->  Breakfast
DINNER <-->  dinner (?)
FRUHSTUCK <-->  Breakfast
BANQUET AND RECEPTION COMMEMORATING 50 YEARS SINCE THE ADMISSION OF HONORABLE JAMES TYNDALE MITCHELL,LL.D. CHIEF JUSTICE OF THE SUPREME COURT OF PA TO THE BAR OF PHILADELPHIA <-->  Lunch
TIFFIN <-->  Dinner
DINNER TO QUEEN ALEXANDRE & PRINCESS VICTORIA OF RUSSIA <-->  Dinner
DAILY MENU, DINNER <-->  Dinner
THIRD ANNUAL BANQUET <-->  Dinner
PERSONALLY CONDUCTED TOUR THROUGH MEXICO & CALIFORNIA <-->  Other
TIFFIN <-->  Dinner
LUNCHEON <-->  Lunch
FIRST ANNUAL BANQUET <-->  Dinner
ALL AMERICAN BANQUET IN HONOR OF EDWIN C. HALL <-->  Dinner
PROF <-->  PROF;
GOVT <-->  GOVT;
PATR <-->  PATR;
POL <-->  POL;
SOC <-->  SOCIAL
SOC <-->  SOCIAL
COMMERCIAL <-->  COM
PROF <-->  PROF;
SOC <-->  SOC;
COMMERCIAL <-->  COM
GOVT <-->  GOV;
SOC <-->  SOC;
SOC <-->  SOC;
PATR <-->  PATR;
SOC <-->  SOC;
POL <-->  POL;
EDUC <-->  EDUC;
SOC <-->  SOC;
ANNUAL <-->  SECULAR HOLIDAY
[SOC?] <-->  COMPLIMENTARY/TESTIMONIAL
UNKNOWN <-->  DAILY
ANNIVERSARY <-->  ANNIVERSARYERSARY
ANNIVERSARY <-->  ANNIVERSARY;
DAILY <-->  OTHER
DAILY <-->  OTHER
ANNIVERSARY <-->  ANNIVERSARY;
OTHER (ANNIV) <-->  OTHER
OTHER, [SOC?] <-->  COMPLIMENTARY/TESTIMONIAL
ANNUAL <-->  SECULAR HOLIDAY
[SOC?] <-->  [SOCIAL]
DAILY <-->  OTHER (DAILY MENU)
DAILY <-->  OTHER (DAILY);
OTHER, [SOC?] <-->  OTHER, [SOCIAL]
2 <-!=->  2.0
2 <-!=->  2.0
16 <-!=->  16.0
2 <-!=->  2.0
4 <-!=->  4.0
4 <-!=->  4.0
4 <-!=->  4.0
5 <-!=->  5.0
3 <-!=->  3.0
4 <-!=->  4.0
2 <-!=->  2.0
1 <-!=->  1.0
4 <-!=->  4.0
2 <-!=->  2.0
4 <-!=->  4.0
2 <-!=->  2.0
8 <-!=->  8.0
6 <-!=->  6.0
2 <-!=->  2.0
5 <-!=->  5.0
2 <-!=->  2.0
11 <-!=->  11.0
4 <-!=->  4.0
1 <-!=->  1.0
5 <-!=->  5.0
2 <-!=->  2.0
3 <-!=->  3.0
14 <-!=->  14.0
4 <-!=->  4.0
1 <-!=->  1.0
8 <-!=->  8.0
4 <-!=->  4.0
4 <-!=->  4.0
4 <-!=->  4.0
2 <-!=->  2.0
2 <-!=->  2.0
12 <-!=->  12.0
2 <-!=->  2.0
4 <-!=->  4.0
4 <-!=->  4.0
2 <-!=->  2.0
1 <-!=->  1.0
2 <-!=->  2.0
2 <-!=->  2.0
2 <-!=->  2.0
2 <-!=->  2.0
20 <-!=->  20.0
2 <-!=->  2.0
3 <-!=->  3.0
2 <-!=->  2.0
4 <-!=->  4.0
2 <-!=->  2.0
2 <-!=->  2.0
2 <-!=->  2.0
4 <-!=->  4.0
3 <-!=->  3.0
2 <-!=->  2.0
2 <-!=->  2.0
4 <-!=->  4.0
1 <-!=->  1.0
1 <-!=->  1.0
4 <-!=->  4.0
2 <-!=->  2.0
2 <-!=->  2.0
1 <-!=->  1.0
4 <-!=->  4.0
2 <-!=->  2.0
4 <-!=->  4.0
2 <-!=->  2.0
22 <-!=->  22.0
2 <-!=->  2.0
3 <-!=->  3.0
2 <-!=->  2.0
1 <-!=->  1.0
2 <-!=->  2.0
2 <-!=->  2.0
1 <-!=->  1.0
2 <-!=->  2.0
2 <-!=->  2.0
4 <-!=->  4.0
1 <-!=->  1.0
4 <-!=->  4.0
2 <-!=->  2.0
4 <-!=->  4.0
2 <-!=->  2.0
2 <-!=->  2.0
2 <-!=->  2.0
8 <-!=->  8.0
3 <-!=->  3.0
2 <-!=->  2.0
6 <-!=->  6.0
8 <-!=->  8.0
4 <-!=->  4.0
2 <-!=->  2.0
8 <-!=->  8.0
4 <-!=->  4.0
5 <-!=->  5.0
4 <-!=->  4.0
8 <-!=->  8.0
2 <-!=->  2.0
22 <-!=->  22.0
546 <-!=->  546.0
28 <-!=->  28.0
23 <-!=->  23.0
78 <-!=->  78.0
55 <-!=->  55.0
383 <-!=->  383.0
416 <-!=->  416.0
60 <-!=->  60.0
34 <-!=->  34.0
20 <-!=->  20.0
6 <-!=->  6.0
78 <-!=->  78.0
227 <-!=->  227.0
479 <-!=->  479.0
13 <-!=->  13.0
19 <-!=->  19.0
188 <-!=->  188.0
8 <-!=->  8.0
17 <-!=->  17.0
23 <-!=->  23.0
12 <-!=->  12.0
67 <-!=->  67.0
47 <-!=->  47.0
201 <-!=->  201.0
43 <-!=->  43.0
172 <-!=->  172.0
27 <-!=->  27.0
19 <-!=->  19.0
22 <-!=->  22.0
55 <-!=->  55.0
92 <-!=->  92.0
14 <-!=->  14.0
378 <-!=->  378.0
34 <-!=->  34.0
26 <-!=->  26.0
93 <-!=->  93.0
9 <-!=->  9.0
430 <-!=->  430.0
14 <-!=->  14.0
226 <-!=->  226.0
25 <-!=->  25.0
14 <-!=->  14.0
93 <-!=->  93.0
75 <-!=->  75.0
11 <-!=->  11.0
29 <-!=->  29.0
218 <-!=->  218.0
97 <-!=->  97.0
33 <-!=->  33.0
22 <-!=->  22.0
37 <-!=->  37.0
68 <-!=->  68.0
13 <-!=->  13.0
298 <-!=->  298.0
125 <-!=->  125.0
24 <-!=->  24.0
11 <-!=->  11.0
18 <-!=->  18.0
43 <-!=->  43.0
90 <-!=->  90.0
151 <-!=->  151.0
7 <-!=->  7.0
65 <-!=->  65.0
38 <-!=->  38.0
22 <-!=->  22.0
26 <-!=->  26.0
170 <-!=->  170.0
26 <-!=->  26.0
17 <-!=->  17.0
69 <-!=->  69.0
70 <-!=->  70.0
20 <-!=->  20.0
13 <-!=->  13.0
50 <-!=->  50.0
113 <-!=->  113.0
20 <-!=->  20.0
12 <-!=->  12.0
311 <-!=->  311.0
186 <-!=->  186.0
114 <-!=->  114.0
48 <-!=->  48.0
30 <-!=->  30.0
13 <-!=->  13.0
16 <-!=->  16.0
81 <-!=->  81.0
23 <-!=->  23.0
16 <-!=->  16.0
45 <-!=->  45.0
254 <-!=->  254.0
12 <-!=->  12.0
18 <-!=->  18.0
489 <-!=->  489.0
43 <-!=->  43.0
26 <-!=->  26.0
164 <-!=->  164.0
69 <-!=->  69.0
76 <-!=->  76.0
23 <-!=->  23.0
22 <-!=->  22.0
546.0 <-!=->  546.0
55.0 <-!=->  55.0
60.0 <-!=->  60.0
34.0 <-!=->  34.0
13.0 <-!=->  13.0
8.0 <-!=->  8.0
12.0 <-!=->  12.0
67.0 <-!=->  67.0
172.0 <-!=->  172.0
27.0 <-!=->  27.0
378.0 <-!=->  378.0
26.0 <-!=->  26.0
93.0 <-!=->  93.0
226.0 <-!=->  226.0
25.0 <-!=->  25.0
93.0 <-!=->  93.0
75.0 <-!=->  75.0
29.0 <-!=->  29.0
37.0 <-!=->  37.0
24.0 <-!=->  24.0
11.0 <-!=->  11.0
7.0 <-!=->  7.0
38.0 <-!=->  38.0
69.0 <-!=->  69.0
113.0 <-!=->  113.0
311.0 <-!=->  311.0
48.0 <-!=->  48.0
30.0 <-!=->  30.0
81.0 <-!=->  81.0
23.0 <-!=->  23.0
45.0 <-!=->  45.0
489.0 <-!=->  489.0
26.0 <-!=->  26.0
69.0 <-!=->  69.0
76.0 <-!=->  76.0
2.0 <-!=->  2.0
4.0 <-!=->  4.0
4.0 <-!=->  4.0
1.0 <-!=->  1.0
4.0 <-!=->  4.0
2.0 <-!=->  2.0
5.0 <-!=->  5.0
11.0 <-!=->  11.0
4.0 <-!=->  4.0
1.0 <-!=->  1.0
14.0 <-!=->  14.0
4.0 <-!=->  4.0
1.0 <-!=->  1.0
4.0 <-!=->  4.0
2.0 <-!=->  2.0
4.0 <-!=->  4.0
2.0 <-!=->  2.0
2.0 <-!=->  2.0
4.0 <-!=->  4.0
2.0 <-!=->  2.0
1.0 <-!=->  1.0
2.0 <-!=->  2.0
4.0 <-!=->  4.0
4.0 <-!=->  4.0
22.0 <-!=->  22.0
2.0 <-!=->  2.0
3.0 <-!=->  3.0
1.0 <-!=->  1.0
2.0 <-!=->  2.0
4.0 <-!=->  4.0
2.0 <-!=->  2.0
2.0 <-!=->  2.0
2.0 <-!=->  2.0
6.0 <-!=->  6.0
8.0 <-!=->  8.0
4.0 <-!=->  4.0
2.0 <-!=->  2.0
546.0 <-!=->  546.0
55.0 <-!=->  55.0
60.0 <-!=->  60.0
34.0 <-!=->  34.0
13.0 <-!=->  13.0
8.0 <-!=->  8.0
12.0 <-!=->  12.0
67.0 <-!=->  67.0
172.0 <-!=->  172.0
27.0 <-!=->  27.0
378.0 <-!=->  378.0
26.0 <-!=->  26.0
93.0 <-!=->  93.0
226.0 <-!=->  226.0
25.0 <-!=->  25.0
93.0 <-!=->  93.0
75.0 <-!=->  75.0
29.0 <-!=->  29.0
37.0 <-!=->  37.0
24.0 <-!=->  24.0
11.0 <-!=->  11.0
7.0 <-!=->  7.0
38.0 <-!=->  38.0
69.0 <-!=->  69.0
113.0 <-!=->  113.0
311.0 <-!=->  311.0
48.0 <-!=->  48.0
30.0 <-!=->  30.0
81.0 <-!=->  81.0
23.0 <-!=->  23.0
45.0 <-!=->  45.0
489.0 <-!=->  489.0
26.0 <-!=->  26.0
69.0 <-!=->  69.0
76.0 <-!=->  76.0
2 <-!=->  2.0
2 <-!=->  2.0
16 <-!=->  16.0
2 <-!=->  2.0
4 <-!=->  4.0
4 <-!=->  4.0
4 <-!=->  4.0
5 <-!=->  5.0
3 <-!=->  3.0
4 <-!=->  4.0
2 <-!=->  2.0
1 <-!=->  1.0
4 <-!=->  4.0
2 <-!=->  2.0
4 <-!=->  4.0
2 <-!=->  2.0
8 <-!=->  8.0
6 <-!=->  6.0
2 <-!=->  2.0
5 <-!=->  5.0
2 <-!=->  2.0
11 <-!=->  11.0
4 <-!=->  4.0
1 <-!=->  1.0
5 <-!=->  5.0
2 <-!=->  2.0
3 <-!=->  3.0
14 <-!=->  14.0
4 <-!=->  4.0
1 <-!=->  1.0
8 <-!=->  8.0
4 <-!=->  4.0
4 <-!=->  4.0
4 <-!=->  4.0
2 <-!=->  2.0
2 <-!=->  2.0
12 <-!=->  12.0
2 <-!=->  2.0
4 <-!=->  4.0
4 <-!=->  4.0
2 <-!=->  2.0
1 <-!=->  1.0
2 <-!=->  2.0
2 <-!=->  2.0
2 <-!=->  2.0
2 <-!=->  2.0
20 <-!=->  20.0
2 <-!=->  2.0
3 <-!=->  3.0
2 <-!=->  2.0
4 <-!=->  4.0
2 <-!=->  2.0
2 <-!=->  2.0
2 <-!=->  2.0
4 <-!=->  4.0
3 <-!=->  3.0
2 <-!=->  2.0
2 <-!=->  2.0
4 <-!=->  4.0
1 <-!=->  1.0
1 <-!=->  1.0
4 <-!=->  4.0
2 <-!=->  2.0
2 <-!=->  2.0
1 <-!=->  1.0
4 <-!=->  4.0
2 <-!=->  2.0
4 <-!=->  4.0
2 <-!=->  2.0
22 <-!=->  22.0
2 <-!=->  2.0
3 <-!=->  3.0
2 <-!=->  2.0
1 <-!=->  1.0
2 <-!=->  2.0
2 <-!=->  2.0
1 <-!=->  1.0
2 <-!=->  2.0
2 <-!=->  2.0
4 <-!=->  4.0
1 <-!=->  1.0
4 <-!=->  4.0
2 <-!=->  2.0
4 <-!=->  4.0
2 <-!=->  2.0
2 <-!=->  2.0
2 <-!=->  2.0
8 <-!=->  8.0
3 <-!=->  3.0
2 <-!=->  2.0
6 <-!=->  6.0
8 <-!=->  8.0
4 <-!=->  4.0
2 <-!=->  2.0
8 <-!=->  8.0
4 <-!=->  4.0
5 <-!=->  5.0
4 <-!=->  4.0
8 <-!=->  8.0
2 <-!=->  2.0
TRUSTEES OF THE MISSOURI BOTANICAL GARDEN <-->  Missouri Botanical Garden
USMS <-->  Unknown
SOUTHERN PACIFIC <-->  UNKNOWN
HOLLAND SOCIETY <-->  Holland America
ADAM'S RESTAURANT <-->  Adams Restaurant
UNKNOWN <-->  ?
LOUIS SHERRY <-->  UNKNOWN
THE MOUQUIN RESTAURANT AND WINE CO. <-->  Mouquin
SOUTHERN PACIFIC <-->  UNKNOWN
THE MAYFLOWER HOTEL <-->  Mayflower Hotel
HAMBURG AMERIKA LINIE <-->  Hamburg America
YAMATO <-->  UNKNOWN
THE BRASS RAIL <-->  Brass Rail
COMSTOCK ROOM OF THE PALACE HOTEL <-->  Palace Hotel
THE COMMODORE HOTEL <-->  Commodore Hotel
HAMBURG AMERIKA LINIE <-->  Hamburg America
NORDDEUTSCHER LLOYD BREMEN <-->  Norddeutscherrr Lloyd Bremen
FIFTH AVENUE RESTAURANT <-->  Fifth Avenue
TOYO KISEN KAISHA   HING KONG MARU <-->  Toyo Kisen Kaisha Hing Kong Maru
TOOTS SHOR <-->  UNKNOWN
HAMBURG AMERIKA LINIE <-->  Hamburg America
HAMBURG AMERIKA LINIE <-->  Hamburg America
THE BILTMORE <-->  UNKNOWN
PENNSYLVANIA RAILROAD <-->  UNKNOWN
R.M.S. PARTHIA <-->  Parthia
UNKNOWN <-->  [Restaurant And/Or Location Not Given]
HOTEL MAJESTIC <-->  Majestic Hotel
HOLLAND AMERICA CRUISES <-->  Holland America
SOCIETY SONS OF THE REVOLUTION IN THE STATE OF MISSOURI <-->  UNKNOWN
COEUR DE LION CAMMANDERY NUMBER TWENTY THREE KNIGHTS TEMPLAR <-->  Coeur de Lion Commandery No. 23 Knights Templar
THE BILTMORE <-->  UNKNOWN
KAISERHOF <-->  UNKNOWN
FREINDS OF WILLIAM CLAUSS <-->  Friends of William Claus
ADAM'S RESTAURANT <-->  Adams' Restaurant
S.S. NIEUW AMSTERDAM <-->  SS Nieuw Amsterdam
THE COMMODORE HOTEL <-->  Commodore Hotel
ADAM'S RESTAURANT <-->  Adams Restaurant
TWENTIETH CENTURY ALDERMANIR ASSOCIATION <-->  20th Century Aldermanic Association
S.S. NIEUW AMSTERDAM <-->  SS Nieuw Amsterdam
THE FOUR SEASONS <-->  Four Seasons
DOLLARS <-->  DOLARS$
DOLLARS <-->  dolars
DOLLARS <-->  DOLARS$
DOLLARS <-->  Dolar
DOLLARS <-->  Dolar
DOLLARS <-->  Dolar
DOLLARS <-->  dolr
DOLLARS <-->  dolr
DOLLARS <-->  dolar
DOLLARS <-->  DOLARS$
DOLLARS <-->  Dolars
DOLLARS <-->  Dolars
DOLLARS <-->  dolars$
DOLLARS <-->  Dolar
DOLLARS <-->  dolr
DOLLARS <-->  dolars$
DOLLARS <-->  DOLR
DOLLARS <-->  DOLR
DOLLARS <-->  dolar
DOLLARS <-->  Dolars
DOLLARS <-->  dolars
DOLLARS <-->  dolars
DOLLARS <-->  dolar
DOLLARS <-->  Dolar
ADAM'S RESTAURANT <-->  Adams' Restaurant
WIEHL & WIDMAN <-->  Wiehl and Widman
[RESTAURANT AND/OR LOCATION NOT GIVEN] <-->  [Restaurant name and/or location not given]
[RESTAURANT AND/OR LOCATION NOT GIVEN] <-->  [Restaurant name and/or location not given]
22 <-!=->  22.0
546 <-!=->  546.0
28 <-!=->  28.0
23 <-!=->  23.0
78 <-!=->  78.0
55 <-!=->  55.0
383 <-!=->  383.0
416 <-!=->  416.0
60 <-!=->  60.0
34 <-!=->  34.0
20 <-!=->  20.0
6 <-!=->  6.0
78 <-!=->  78.0
227 <-!=->  227.0
479 <-!=->  479.0
13 <-!=->  13.0
19 <-!=->  19.0
188 <-!=->  188.0
8 <-!=->  8.0
17 <-!=->  17.0
23 <-!=->  23.0
12 <-!=->  12.0
67 <-!=->  67.0
47 <-!=->  47.0
201 <-!=->  201.0
43 <-!=->  43.0
172 <-!=->  172.0
27 <-!=->  27.0
19 <-!=->  19.0
22 <-!=->  22.0
55 <-!=->  55.0
92 <-!=->  92.0
14 <-!=->  14.0
378 <-!=->  378.0
34 <-!=->  34.0
26 <-!=->  26.0
93 <-!=->  93.0
9 <-!=->  9.0
430 <-!=->  430.0
14 <-!=->  14.0
226 <-!=->  226.0
25 <-!=->  25.0
14 <-!=->  14.0
93 <-!=->  93.0
75 <-!=->  75.0
11 <-!=->  11.0
29 <-!=->  29.0
218 <-!=->  218.0
97 <-!=->  97.0
33 <-!=->  33.0
22 <-!=->  22.0
37 <-!=->  37.0
68 <-!=->  68.0
13 <-!=->  13.0
298 <-!=->  298.0
125 <-!=->  125.0
24 <-!=->  24.0
11 <-!=->  11.0
18 <-!=->  18.0
43 <-!=->  43.0
90 <-!=->  90.0
151 <-!=->  151.0
7 <-!=->  7.0
65 <-!=->  65.0
38 <-!=->  38.0
22 <-!=->  22.0
26 <-!=->  26.0
170 <-!=->  170.0
26 <-!=->  26.0
17 <-!=->  17.0
69 <-!=->  69.0
70 <-!=->  70.0
20 <-!=->  20.0
13 <-!=->  13.0
50 <-!=->  50.0
113 <-!=->  113.0
20 <-!=->  20.0
12 <-!=->  12.0
311 <-!=->  311.0
186 <-!=->  186.0
114 <-!=->  114.0
48 <-!=->  48.0
30 <-!=->  30.0
13 <-!=->  13.0
16 <-!=->  16.0
81 <-!=->  81.0
23 <-!=->  23.0
16 <-!=->  16.0
45 <-!=->  45.0
254 <-!=->  254.0
12 <-!=->  12.0
18 <-!=->  18.0
489 <-!=->  489.0
43 <-!=->  43.0
26 <-!=->  26.0
164 <-!=->  164.0
69 <-!=->  69.0
76 <-!=->  76.0
23 <-!=->  23.0
22 <-!=->  22.0
Spilker's Restaurant and Grill Room <-->  Wiehl and Widman
Adam's Restaurant <-->  Adams' Restaurant
S.S. Nieuw Amsterdam <-->  SS Nieuw Amsterdam
Wiehl & Widman <-->  Wiehl and Widman
University Of Richmond <-->  Springfield Caledonians
The Mouquin Restaurant and Wine Co. <-->  Four Seasons
The Brass Rail <-->  Four Seasons
THE PENNSYLVANIA BAR ASSOCIATION ON BEHALF OF THE BAR OF THE COMMONWEALTH <-->  Pennsylvania Bar Association
NORDDEUTSCHER LLOYD BREMEN <-->  NORDDEUTSCHERRR LLOYD BREMEN
Gardner & Smith <-->  Gardner and Smith
TOYO KISEN KAISHA - HING KONG MARU <-->  Toyo Kisen Kaisha - Hong Kong Maru

In [32]:
dt_result

     pp_id  ratio
0        1  0.300
1        2  1.000
2        3  0.260
3        4  0.400
4        5  0.070
..     ...    ...
137    150  0.450
138    151  0.450
139    152  0.300
140    153  0.775
141    154  0.500

[142 rows x 2 columns]

In [39]:
total_tab = []
col_name = []
for model in models[:3] + ["dirty"]:
    print(model)
    
    table_results = pd.read_csv(f'evaluation/{model}_table_result.csv')
    table_results.set_index('pp_id', inplace=True)

    total_tab.append(parse_mean(table_results, f'total__{model}'))
    col_name.append(f'total__{model}')
    
    
    hos_results = table_results.loc[127:155]
    hos_results.reset_index()
    # hos_results = workflow_results[workflow_results['pp_id'] >= 127]
    total_tab.append(parse_mean(hos_results, f'hos__{model}'))
    
    col_name.append(f'hos__{model}')


    # flights_results = workflow_results[workflow_results['pp_id'] >= 111][workflow_results['pp_id'] <=126]
    flights_results = table_results.loc[111:127]
    flights_results.reset_index()
    total_tab.append(parse_mean(flights_results, f'flights__{model}'))
    col_name.append(f'flights__{model}')

    # ppp_results = workflow_results[workflow_results['pp_id'] >= 62][workflow_results['pp_id'] <=91]
    ppp_results = table_results.loc[62:91]
    ppp_results.reset_index()
    total_tab.append(parse_mean(ppp_results, f'ppp__{model}'))
    col_name.append(f'ppp__{model}')

    # dish_results = workflow_results[workflow_results['pp_id'] >= 92][workflow_results['pp_id'] <= 110]
    dish_results = table_results.loc[92:111]
    dish_results.reset_index()
    total_tab.append(parse_mean(dish_results, f'dish__{model}'))
    col_name.append(f'dish__{model}')

    # menu_results = workflow_results[workflow_results['pp_id'] < 31]
    menu_results = table_results.loc[:31]
    menu_results = menu_results.reset_index()
    total_tab.append(parse_mean(menu_results, f'menu__{model}'))
    col_name.append(f'menu__{model}')
    # chi_results = workflow_results[workflow_results['pp_id'] >= 31][workflow_results['pp_id'] <=61]
    chi_results = table_results.loc[31:62]
    chi_results = chi_results.reset_index()
    total_tab.append(parse_mean(chi_results, f'chi__{model}'))
    col_name.append(f'chi__{model}')
tab_perf = pd.concat(total_tab, axis=1)
tab_perf.columns = col_name
# print(wf_perf)
tab_perf = tab_perf.transpose()
tab_perf.to_csv('table_column_ratio_results_llama_mistral_gemma2.csv')

llama3.1
mistral
gemma2
dirty

In [28]:
dt_result.head()

   pp_id  ratio
0      1   0.30
1      2   1.00
2      3   0.26
3      4   0.40
4      5   0.07

In [47]:
stat = dt_result['ratio'].describe()
for idx in ['mean', 'std',	'min',	'max',	'25%',	'50%',	'75%']:
    print(stat.loc[idx])

0.4870411865130175
0.3372507748499357
0.0
1.0
0.20416666666666666
0.45
0.8066666666666666

In [41]:
hos_dt_results = dt_result[dt_result['pp_id'] >= 127]
stat = hos_dt_results['ratio'].describe()
for idx in ['mean', 'std',	'min',	'max',	'25%',	'50%',	'75%']:
    print(stat.loc[idx])

0.6333333333333332
0.19121659448967931
0.19999999999999998
0.9
0.5375
0.6499999999999999
0.7708333333333333

In [42]:
flights_dt_results = dt_result[dt_result['pp_id'] >= 111][dt_result['pp_id'] <=126]
stat = flights_dt_results['ratio'].describe()
for idx in ['mean', 'std',	'min',	'max',	'25%',	'50%',	'75%']:
    print(stat.loc[idx])

0.6229166666666667
0.199532323567256
0.12666666666666668
1.0
0.5375000000000001
0.5983333333333334
0.7050000000000001

/tmp/ipykernel_1743614/1502436861.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  flights_dt_results = dt_result[dt_result['pp_id'] >= 111][dt_result['pp_id'] <=126]

In [35]:
ppp_dt_results = dt_result[dt_result['pp_id'] >= 62][dt_result['pp_id'] <=91]
stat = ppp_dt_results['ratio'].describe()
for idx in ['mean', 'std',	'min',	'max',	'25%',	'50%',	'75%']:
    print(stat.loc[idx])

0.8435606060606061
0.19292944638979112
0.275
1.0
0.75
0.9416666666666667
1.0

/tmp/ipykernel_1743614/1140604443.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ppp_dt_results = dt_result[dt_result['pp_id'] >= 62][dt_result['pp_id'] <=91]

In [43]:
dish_dt_result =dt_result[dt_result['pp_id'] >= 92][dt_result['pp_id'] <=110]
stat = dish_dt_result['ratio'].describe()
for idx in ['mean', 'std',	'min',	'max',	'25%',	'50%',	'75%']:
    print(stat.loc[idx])

0.8670833333333333
0.11863966609178556
0.5599999999999999
1.0
0.87
0.8799999999999999
0.9383333333333332

/tmp/ipykernel_1743614/1535956895.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  dish_dt_result =dt_result[dt_result['pp_id'] >= 92][dt_result['pp_id'] <=110]

In [37]:
chi_dt_result =dt_result[dt_result['pp_id'] >= 31][dt_result['pp_id'] <=61]
stat = chi_dt_result['ratio'].describe()
for idx in ['mean', 'std',	'min',	'max',	'25%',	'50%',	'75%']:
    print(stat.loc[idx])

0.49530303030303036
0.24220351432506884
0.0
1.0
0.35
0.5
0.6875

/tmp/ipykernel_3976518/3331208062.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  chi_dt_result =dt_result[dt_result['pp_id'] >= 31][dt_result['pp_id'] <=61]

In [38]:
menu_dt_result =dt_result[dt_result['pp_id'] < 31]

stat = menu_dt_result['ratio'].describe()
for idx in ['mean', 'std',	'min',	'max',	'25%',	'50%',	'75%']:
    print(stat.loc[idx])

0.4023333333333333
0.303228982935263
0.0
1.0
0.17
0.3175
0.6212500000000001

## table eval ttest

# answer eval

In [5]:
par_folder = '/projects/bces/lanl2/LLM4DC'
datafile_path = f'{par_folder}/evaluation/answer_1-154_gt.json'
data = []
with open(datafile_path, 'r') as f:
    for l in f:
        data.append(json.loads(l))

In [42]:
from bert_score import score

/u/lirif2/.conda/envs/llm4dc/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [43]:
import json
from typing import Union, List, Dict, Any
from difflib import SequenceMatcher
from math import isclose

# Define a utility to convert JSON strings to Python objects
def parse_input(answer: Union[str, float, List, Dict]) -> Any:
    if isinstance(answer, str):
        try:
            # Try to parse JSON strings into Python objects
            return json.loads(answer)
        except json.JSONDecodeError:
            return answer.lower().strip()  # Normalize strings for comparison
    elif isinstance(answer, float):
        return round(answer, 2)  # Round floats to two decimal places if needed
    return answer  # If already in desired format

# Calculate exact match accuracy
def accuracy_metric(gt: Any, pred: Any) -> float:
    return 1.0 if gt == pred else 0.0

# Calculate precision, recall, and F1 for lists (assuming items are unique)
def precision_recall_f1(gt: List, pred: List) -> Dict[str, float]:
    gt_set, pred_set = set(gt), set(pred)
    true_positives = len(gt_set & pred_set)
    precision = true_positives / len(pred_set) if pred_set else 0
    recall = true_positives / len(gt_set) if gt_set else 0
    f1_score = 2 * precision * recall / (precision + recall) if precision + recall > 0 else 0
    return {"precision": precision, "recall": recall, "f1": f1_score}

# Calculate semantic distance for string answers using sequence matching
def semantic_similarity(gt: str, pred: str) -> float:
    return SequenceMatcher(None, gt, pred).ratio()  # Returns a ratio between 0 and 1

# Evaluate an answer based on the ground truth
def calculate_answer_metrics(gt: Any, pred: Any) -> Dict[str, float]:
    # Parse inputs
    gt, pred = parse_input(gt), parse_input(pred)
    
    # Initialize results
    results = {"accuracy": 0, "semantic_similarity": 0, "precision": 0, "recall":0, "f1":0}
    
    # Check type and apply appropriate metrics
    if isinstance(gt, float) and isinstance(pred, float):
        results["accuracy"] = 1.0 if isclose(gt, pred, rel_tol=1e-2) else 0.0  # Accuracy for floats with tolerance
        precision, recall = results["accuracy"], results["accuracy"]
        results.update({"precision": precision, "recall": recall, "f1": 2 * precision * recall / (precision + recall) if precision + recall > 0 else 0})
        # results['bertscore'] = score([f"{pred}"], [f"{gt}"], lang='en', verbose=True)
        results["semantic_similarity"] = semantic_similarity(str(gt), str(pred))
    elif isinstance(gt, int) and isinstance(pred, int):
        results["accuracy"] = 1.0 if isclose(gt, pred, rel_tol=1e-2) else 0.0  # Accuracy for floats with tolerance
        precision, recall = results["accuracy"], results["accuracy"]
        results.update({"precision": precision, "recall": recall, "f1": 2 * precision * recall / (precision + recall) if precision + recall > 0 else 0})
        # results['bertscore'] = score([f"{pred}"], [f"{gt}"], lang='en', verbose=True)
        results["semantic_similarity"] = semantic_similarity(str(gt), str(pred))


    elif isinstance(gt, str) and isinstance(pred, str):
        results["accuracy"] = accuracy_metric(gt.lower(), pred.lower())
        precision, recall = results["accuracy"], results["accuracy"]
        results.update({"precision": precision, "recall": recall, "f1": 2 * precision * recall / (precision + recall) if precision + recall > 0 else 0})
        # results['bertscore'] = score([pred], [gt], lang='en', verbose=True)
        results["semantic_similarity"] = semantic_similarity(gt, pred)

    
    elif isinstance(gt, list) and isinstance(pred, list):
        if type(gt[0]) == str:
            gt = [x.lower() for x in gt]
            if len(pred) > 0:
                if type(pred[0]) == str:
                    pred = [x.lower() for x in pred]
        metrics = precision_recall_f1(gt, pred)
        results.update(metrics)
        results["accuracy"] = accuracy_metric(gt, pred)
        # results['bertscore'] = score([f"{pred}"], [f"{gt}"], lang='en', verbose=True)
        similarity = semantic_similarity(f"{gt}", f"{pred}")
        results["semantic_similarity"] = similarity

    
    elif isinstance(gt, dict) and isinstance(pred, dict):
        gt = {key.lower(): value for key, value in gt.items()}
        pred = {key.lower(): value for key, value in pred.items()}
        gt_keys, pred_keys = list(gt.keys()), list(pred.keys())
        if type(gt[gt_keys[0]]) == dict:
            precision_recall_f1_results = []
            for k in gt_keys:
                if k in pred.keys():
                    pred_input = pred[k].values()
                else:
                    pred_input = []
                precision_recall_f1_results.append(precision_recall_f1(gt[k].values(), pred_input))
            precision = sum([x['precision'] for x in precision_recall_f1_results])/len([x['precision'] for x in precision_recall_f1_results])
            recall = sum([x['recall'] for x in precision_recall_f1_results])/len([x['recall'] for x in precision_recall_f1_results])
            f1 =sum([x['f1'] for x in precision_recall_f1_results])/len([x['f1'] for x in precision_recall_f1_results])
            results.update({'precision': precision, 'recall':recall, 'f1': f1})  # Precision/Recall on keys

        elif type(gt[gt_keys[0]]) == list:
            precision_recall_f1_results = []
            for k in gt_keys:
                if k in pred:
                    pred_input = pred[k]
                else: 
                    pred_input = []
                if type(gt[k][0]) ==str:
                    gt_input = [x.lower() for x in gt[k]]
                    if len(pred_input) > 0:
                        if type(pred_input[0]) == str:
                            pred_input = [x.lower() for x in pred_input]    
                else:
                    gt_input = gt[k]
                precision_recall_f1_results.append(precision_recall_f1(gt[k], pred_input)) 
            precision = sum([x['precision'] for x in precision_recall_f1_results])/len([x['precision'] for x in precision_recall_f1_results])
            recall = sum([x['recall'] for x in precision_recall_f1_results])/len([x['recall'] for x in precision_recall_f1_results])
            f1 =sum([x['f1'] for x in precision_recall_f1_results])/len([x['f1'] for x in precision_recall_f1_results])
            results.update({'precision': precision, 'recall':recall, 'f1': f1})  # Precision/Recall on keys
        

        results["accuracy"] = accuracy_metric(gt, pred)
        # Check semantic similarity for each key-value pair
        similarity = [semantic_similarity(str(gt[k]), str(pred.get(k, ""))) for k in gt_keys]
        results["semantic_similarity"] = sum(similarity) / len(similarity) if similarity else 0
        
        # results['bertscore'] = score([f"{pred}"], [f"{gt}"], lang='en', verbose=True)
    p, r, f1 = score([f"{pred}"], [f"{gt}"], lang='en', verbose=True)
    results.update({'bertscore_p': p.detach().cpu().tolist(),
    'bertscore_r': r.detach().cpu().tolist(),
    'bertscore_f1': f1.detach().cpu().tolist()})
    # print(results)


    return results

In [42]:
test_json = "{\"Zip\":{\"0\":96701,\"1\":96704,\"2\":96707,\"3\":96708,\"4\":96749,\"5\":96750,\"6\":96754,\"7\":96791,\"8\":96813,\"9\":96814,\"10\":96815,\"11\":96816,\"12\":96817,\"13\":96821,\"14\":96825,\"15\":96826},\"LoanCount\":{\"0\":1,\"1\":1,\"2\":4,\"3\":1,\"4\":1,\"5\":1,\"6\":1,\"7\":1,\"8\":1,\"9\":1,\"10\":1,\"11\":2,\"12\":1,\"13\":1,\"14\":1,\"15\":1}}"

In [43]:
test_json = parse_input(test_json)

In [44]:
test_json.keys()
test_json.get('Zip').values()

dict_values([96701, 96704, 96707, 96708, 96749, 96750, 96754, 96791, 96813, 96814, 96815, 96816, 96817, 96821, 96825, 96826])

In [44]:
# LLM-based history update solution
import importlib.util
import inspect
from typing import List
import requests
import json
import re
import difflib
from collections import Counter
# from spellchecker import SpellChecker
from datetime import datetime
import pandas as pd
import ast
import random
import logging 
# from history_update_problem.call_or import export_rows
from call_or import *

# from evaluation.data_compare import calculate_answer_metrics


def load_answer_dataset(datafile_path):
    """
    load json file, each line is a json dictionary

    datafile_path: str
    return: data:  list_of_dictionary
    """
    data = []
    with open(datafile_path, 'r') as f:
        for l in f:
            data.append(json.loads(l))
    return data

def eval_answers(answer_gt_path, answer_preds_llama):
    answer_gt = load_answer_dataset(answer_gt_path)
    answer_gt = pd.DataFrame(answer_gt)
    answer_preds_llama = load_answer_dataset(answer_preds_llama)
    answer_preds_llama = pd.DataFrame(answer_preds_llama)
    answer_compare = answer_gt.merge(answer_preds_llama[['pp_id', 'answer']], on='pp_id', how='left', suffixes=('_gt', '_preds'))

    results = []
    for i, row in answer_compare.iterrows():
        
        gt = row['answer_gt']
        preds = row['answer_preds']
        
        single_result = calculate_answer_metrics(gt, preds)
        
        single_result['pp_id'] = row['pp_id']
        results.append(single_result)
        # break
    return pd.DataFrame(results)

In [9]:
# @title single eexample
answer_gt_path = 'evaluation/answer_1-154_gt.json'
answer_gt = load_answer_dataset(answer_gt_path)
answer_gt = pd.DataFrame(answer_gt)
answer_dirty = 'evaluation/answer_1-154_dirty.json'
answer_dirty = load_answer_dataset(answer_dirty)
answer_dirty = pd.DataFrame(answer_dirty)
answer_preds_llama = 'evaluation/answer_1-154_llama3.1.json'
answer_preds_llama = load_answer_dataset(answer_preds_llama)
answer_preds_llama = pd.DataFrame(answer_preds_llama)
answer_compare = answer_gt.merge(answer_preds_llama[['pp_id', 'answer']], on='pp_id', how='left', suffixes=('_gt', '_preds'))
# answer_compare = answer_gt.merge(answer_dirty[['pp_id', 'answer']], on='pp_id', how='left', suffixes=('_gt', '_preds'))

results = []
for i, row in answer_compare.iterrows():
    gt = row['answer_gt']
    preds = row['answer_preds']
    single_result = calculate_answer_metrics(gt, preds)
    single_result['pp_id'] = row['pp_id']
    print(gt, type(gt))
    print(preds, type(preds))
    results.append(single_result)
    break

pd.DataFrame(results)

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:09<00:00,  9.33s/it]

computing greedy matching.

100%|██████████| 1/1 [00:02<00:00,  2.27s/it]

done in 11.77 seconds, 0.08 sentences/sec
22 <class 'int'>
22 <class 'int'>

,accuracy,semantic_similarity,precision,recall,f1,bertscore_p,bertscore_r,bertscore_f1,pp_id
0,1.0,1.0,1.0,1.0,1.0,[1.0000004768371582],[1.0000004768371582],[1.0000004768371582],1

In [ ]:
# 'dirty', 
models = ['llama3.1',  'mistral', 'gemma2','deepseek-r1']
for model in models[0:3] + ['dirty']: #['mistral', 'gemma2', 'llama3.1']:
    print(model)
    answer_gt_path = '/projects/bces/lanl2/LLM4DC/evaluation/answer_1-154_gt.json'
    # answer_preds_llama = '/projects/bces/lanl2/LLM4DC/evaluation/answer_1-154_llama3.1.json'
    # model = 'gemma2'
    # model = 'dirty'
    # model = 'llama3.1'
    # model = 'mistral'
    answer_preds = f'/projects/bces/lanl2/LLM4DC/evaluation/answer_1-154_{model}.json'
    # answer_preds = f'/projects/bces/lanl2/LLM4DC/evaluation/answer_1-110_dirty.json'
    eval_answer_results = eval_answers(answer_gt_path, answer_preds)
    eval_answer_results['bertscore_p'] = eval_answer_results['bertscore_p'].apply(lambda x: sum(x)/len(x) if len(x) > 0 else None)
    eval_answer_results['bertscore_r'] = eval_answer_results['bertscore_r'].apply(lambda x: sum(x)/len(x) if len(x) > 0 else None)
    eval_answer_results['bertscore_f1'] = eval_answer_results['bertscore_f1'].apply(lambda x: sum(x)/len(x) if len(x) > 0 else None)
    eval_answer_results.to_csv(f'/projects/bces/lanl2/LLM4DC/evaluation/{model}_answer_result.csv')

llama3.1

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:01<00:00,  1.27s/it]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00,  1.43it/s]

done in 1.98 seconds, 0.51 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 29.25it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 894.31it/s]

done in 0.04 seconds, 24.17 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 50.41it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 837.02it/s]

done in 0.03 seconds, 35.70 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.88it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 821.93it/s]

done in 0.02 seconds, 54.12 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 51.58it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 827.28it/s]

done in 0.03 seconds, 37.79 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.55it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 832.04it/s]

done in 0.02 seconds, 55.36 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 45.82it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 854.76it/s]

done in 0.05 seconds, 20.12 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 45.19it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 791.83it/s]

done in 0.05 seconds, 21.26 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 51.15it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 802.12it/s]

done in 0.03 seconds, 37.07 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.31it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 836.52it/s]

done in 0.03 seconds, 32.66 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.12it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 916.59it/s]

done in 0.02 seconds, 53.06 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.26it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 887.68it/s]

done in 0.04 seconds, 27.02 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 19.24it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 705.28it/s]

done in 0.06 seconds, 16.81 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.26it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 894.69it/s]

done in 0.02 seconds, 42.53 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 57.26it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 802.28it/s]

done in 0.03 seconds, 39.94 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 52.87it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 898.14it/s]

done in 0.03 seconds, 32.77 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 46.64it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 735.71it/s]

done in 0.04 seconds, 27.44 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 80.06it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 778.89it/s]

done in 0.03 seconds, 32.65 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 47.31it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 801.97it/s]

done in 0.03 seconds, 35.58 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 23.93it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 902.78it/s]

done in 0.06 seconds, 17.23 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.46it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 625.46it/s]

done in 0.02 seconds, 53.78 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.49it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 844.60it/s]

done in 0.02 seconds, 56.95 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 48.86it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 819.84it/s]

done in 0.03 seconds, 36.59 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 45.91it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 900.84it/s]

done in 0.03 seconds, 32.40 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 34.88it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 881.53it/s]

done in 0.05 seconds, 21.83 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 25.48it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 734.68it/s]

done in 0.06 seconds, 17.56 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.65it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 935.18it/s]

done in 0.03 seconds, 29.08 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.89it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 871.63it/s]

done in 0.02 seconds, 48.84 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 99.45it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 908.25it/s]

done in 0.02 seconds, 52.31 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.36it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 862.32it/s]

done in 0.02 seconds, 44.71 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.06it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 870.37it/s]

done in 0.02 seconds, 43.76 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.63it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 889.38it/s]

done in 0.02 seconds, 53.24 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.25it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 890.70it/s]

done in 0.02 seconds, 54.17 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 77.03it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 864.98it/s]

done in 0.02 seconds, 46.94 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 100.77it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 917.79it/s]

done in 0.02 seconds, 54.64 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.25it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 892.41it/s]

done in 0.02 seconds, 53.12 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.30it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 901.42it/s]

done in 0.02 seconds, 53.27 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 79.82it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 899.68it/s]

done in 0.02 seconds, 49.02 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.47it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 906.29it/s]

done in 0.02 seconds, 44.57 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 56.50it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 826.30it/s]

done in 0.03 seconds, 38.30 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.15it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 903.36it/s]

done in 0.02 seconds, 49.92 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.45it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 886.93it/s]

done in 0.02 seconds, 50.16 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 52.27it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 748.72it/s]

done in 0.03 seconds, 36.44 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.77it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 908.84it/s]

done in 0.02 seconds, 47.29 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.35it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 887.12it/s]

done in 0.02 seconds, 43.41 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 77.13it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 825.81it/s]

done in 0.03 seconds, 39.09 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.97it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 886.56it/s]

done in 0.02 seconds, 43.60 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.09it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 886.93it/s]

done in 0.02 seconds, 49.54 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.76it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 857.56it/s]

done in 0.02 seconds, 41.83 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 99.15it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 915.59it/s]

done in 0.02 seconds, 47.34 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.16it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 893.36it/s]

done in 0.02 seconds, 49.22 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.48it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 887.87it/s]

done in 0.02 seconds, 50.47 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.13it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 902.39it/s]

done in 0.02 seconds, 46.77 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.06it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 915.59it/s]

done in 0.02 seconds, 52.22 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 80.05it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 764.41it/s]

done in 0.02 seconds, 45.98 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 75.45it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 696.15it/s]

done in 0.05 seconds, 21.05 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.73it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 730.33it/s]

done in 0.02 seconds, 47.10 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.37it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 856.85it/s]

done in 0.02 seconds, 50.35 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 77.33it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 806.13it/s]

done in 0.02 seconds, 43.92 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.18it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 799.07it/s]

done in 0.02 seconds, 50.74 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.25it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 901.81it/s]

done in 0.02 seconds, 53.67 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.37it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 902.00it/s]

done in 0.02 seconds, 52.27 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.76it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 916.79it/s]

done in 0.02 seconds, 54.32 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.65it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 862.85it/s]

done in 0.02 seconds, 50.27 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.37it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 856.85it/s]

done in 0.02 seconds, 49.64 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.22it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 922.64it/s]

done in 0.02 seconds, 53.39 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 75.51it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 830.39it/s]

done in 0.02 seconds, 45.58 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.89it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 911.81it/s]

done in 0.02 seconds, 51.47 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.04it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 902.78it/s]

done in 0.02 seconds, 52.58 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.22it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 893.55it/s]

done in 0.02 seconds, 54.82 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 58.54it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 652.81it/s]

done in 0.03 seconds, 32.49 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 31.69it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 621.75it/s]

done in 0.04 seconds, 23.67 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 27.66it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 689.29it/s]

done in 0.06 seconds, 16.86 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.98it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 912.80it/s]

done in 0.02 seconds, 49.74 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.45it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 887.68it/s]

done in 0.02 seconds, 49.67 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.59it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 754.51it/s]

done in 0.02 seconds, 47.79 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.60it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 788.11it/s]

done in 0.03 seconds, 35.83 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 84.49it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 878.57it/s]

done in 0.02 seconds, 48.86 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 76.32it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 687.70it/s]

done in 0.02 seconds, 41.99 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.34it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 895.64it/s]

done in 0.02 seconds, 49.67 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 52.64it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 793.62it/s]

done in 0.03 seconds, 34.19 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.95it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 883.94it/s]

done in 0.02 seconds, 49.61 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.90it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 922.43it/s]

done in 0.02 seconds, 52.45 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 18.33it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 568.41it/s]

done in 0.06 seconds, 15.70 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 45.59it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 854.76it/s]

done in 0.05 seconds, 20.77 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.18it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 856.16it/s]

done in 0.03 seconds, 33.37 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 48.82it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 771.30it/s]

done in 0.03 seconds, 34.96 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.17it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 857.91it/s]

done in 0.02 seconds, 57.20 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 38.46it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 827.28it/s]

done in 0.04 seconds, 23.18 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 52.71it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 828.59it/s]

done in 0.03 seconds, 38.37 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.11it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 878.02it/s]

done in 0.03 seconds, 37.01 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 27.40it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 674.54it/s]

done in 0.05 seconds, 18.61 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 25.96it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 642.61it/s]

done in 0.05 seconds, 21.78 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.25it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 783.40it/s]

done in 0.02 seconds, 52.62 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.36it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 836.85it/s]

done in 0.02 seconds, 40.07 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 53.28it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 860.55it/s]

done in 0.03 seconds, 39.20 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.35it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 836.02it/s]

done in 0.02 seconds, 53.03 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 23.73it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 697.08it/s]

done in 0.05 seconds, 20.37 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 56.60it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 782.23it/s]

done in 0.03 seconds, 39.55 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 50.15it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 840.54it/s]

done in 0.03 seconds, 36.99 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 54.12it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 834.36it/s]

done in 0.03 seconds, 36.44 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.53it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 911.61it/s]

done in 0.04 seconds, 23.08 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.40it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 859.66it/s]

done in 0.02 seconds, 42.07 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.74it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 876.55it/s]

done in 0.02 seconds, 49.11 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 44.84it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 805.20it/s]

done in 0.03 seconds, 33.21 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.92it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 822.74it/s]

done in 0.02 seconds, 49.55 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.48it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 801.36it/s]

done in 0.02 seconds, 47.76 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 84.39it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 860.90it/s]

done in 0.02 seconds, 50.73 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.68it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 849.05it/s]

done in 0.02 seconds, 51.41 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.29it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 804.12it/s]

done in 0.02 seconds, 53.81 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 58.98it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 792.42it/s]

done in 0.03 seconds, 39.84 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.71it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 894.69it/s]

done in 0.02 seconds, 52.74 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.43it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 889.19it/s]

done in 0.02 seconds, 52.36 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.22it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 884.87it/s]

done in 0.02 seconds, 52.86 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.73it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 627.70it/s]

done in 0.02 seconds, 40.05 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 70.56it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 688.04it/s]

done in 0.02 seconds, 44.38 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 70.79it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 808.77it/s]

done in 0.02 seconds, 43.71 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.40it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 850.77it/s]

done in 0.02 seconds, 48.49 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 56.17it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 724.03it/s]

done in 0.03 seconds, 37.73 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 99.62it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 896.22it/s]

done in 0.02 seconds, 56.71 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.76it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 904.33it/s]

done in 0.02 seconds, 49.74 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.95it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 891.46it/s]

done in 0.02 seconds, 49.88 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.75it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 916.19it/s]

done in 0.02 seconds, 48.47 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.88it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 912.40it/s]

done in 0.02 seconds, 40.34 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.29it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 914.79it/s]

done in 0.02 seconds, 51.41 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.71it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 844.26it/s]

done in 0.02 seconds, 46.92 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 67.62it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 781.94it/s]

done in 0.02 seconds, 42.53 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 81.06it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 873.63it/s]

done in 0.02 seconds, 42.68 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 33.90it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 499.20it/s]

done in 0.04 seconds, 24.85 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 49.52it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 861.25it/s]

done in 0.03 seconds, 37.33 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 100.08it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 858.26it/s]

done in 0.02 seconds, 59.76 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.23it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 853.54it/s]

done in 0.05 seconds, 19.87 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.19it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 879.86it/s]

done in 0.04 seconds, 26.15 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 48.21it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 835.52it/s]

done in 0.03 seconds, 36.10 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 51.23it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 841.72it/s]

done in 0.03 seconds, 38.21 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.39it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 859.66it/s]

done in 0.02 seconds, 57.36 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 101.04it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 866.59it/s]

done in 0.02 seconds, 59.90 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.83it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 832.53it/s]

done in 0.02 seconds, 57.05 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 84.06it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 889.19it/s]

done in 0.02 seconds, 49.82 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.13it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 903.75it/s]

done in 0.02 seconds, 54.07 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.70it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 887.68it/s]

done in 0.02 seconds, 48.98 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.12it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 896.03it/s]

done in 0.02 seconds, 49.91 sentences/sec
mistral

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.51it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 904.72it/s]

done in 0.02 seconds, 52.95 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.11it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 882.83it/s]

done in 0.02 seconds, 54.27 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.24it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 918.80it/s]

done in 0.02 seconds, 54.25 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.44it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 883.20it/s]

done in 0.02 seconds, 51.28 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.12it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 862.85it/s]

done in 0.02 seconds, 45.04 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.22it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 687.48it/s]

done in 0.02 seconds, 51.32 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.77it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 622.76it/s]

done in 0.02 seconds, 46.65 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 84.34it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 724.66it/s]

done in 0.02 seconds, 45.76 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.11it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 908.84it/s]

done in 0.02 seconds, 53.92 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.87it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 908.05it/s]

done in 0.02 seconds, 54.11 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.62it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 910.62it/s]

done in 0.02 seconds, 48.26 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.27it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 911.21it/s]

done in 0.02 seconds, 41.60 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 41.98it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 759.56it/s]

done in 0.03 seconds, 29.11 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 77.84it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 844.60it/s]

done in 0.02 seconds, 44.58 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 77.02it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 839.70it/s]

done in 0.02 seconds, 45.10 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 80.94it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 918.80it/s]

done in 0.02 seconds, 44.68 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 68.80it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 877.10it/s]

done in 0.02 seconds, 43.28 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.20it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 857.73it/s]

done in 0.03 seconds, 32.23 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 65.95it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 791.98it/s]

done in 0.02 seconds, 41.16 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.33it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 908.25it/s]

done in 0.02 seconds, 50.90 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.45it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 922.43it/s]

done in 0.02 seconds, 51.87 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.49it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 891.84it/s]

done in 0.02 seconds, 52.58 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 44.69it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 820.32it/s]

done in 0.03 seconds, 31.57 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.36it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 918.19it/s]

done in 0.02 seconds, 52.82 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.51it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 886.75it/s]

done in 0.02 seconds, 51.02 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 25.70it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 814.59it/s]

done in 0.07 seconds, 15.26 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 41.48it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 264.76it/s]

done in 0.03 seconds, 31.12 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 32.69it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 823.87it/s]

done in 0.04 seconds, 25.97 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 99.69it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 921.42it/s]

done in 0.02 seconds, 55.49 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.00it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 808.93it/s]

done in 0.03 seconds, 31.71 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 100.25it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 893.74it/s]

done in 0.02 seconds, 56.13 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.40it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 879.86it/s]

done in 0.02 seconds, 50.49 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.74it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 898.91it/s]

done in 0.02 seconds, 46.73 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 33.30it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 806.75it/s]

done in 0.06 seconds, 17.34 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.04it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 876.74it/s]

done in 0.03 seconds, 40.00 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.88it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 881.53it/s]

done in 0.02 seconds, 50.30 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 41.72it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 852.85it/s]

done in 0.03 seconds, 31.80 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 80.61it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 827.77it/s]

done in 0.02 seconds, 47.60 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.52it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 915.19it/s]

done in 0.02 seconds, 60.55 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 34.55it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 749.92it/s]

done in 0.04 seconds, 27.46 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.73it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 837.69it/s]

done in 0.02 seconds, 48.13 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.66it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 898.91it/s]

done in 0.02 seconds, 47.41 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 51.54it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 820.16it/s]

done in 0.03 seconds, 36.77 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.14it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 895.84it/s]

done in 0.02 seconds, 44.52 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 81.87it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 897.75it/s]

done in 0.03 seconds, 32.87 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 72.86it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 802.28it/s]

done in 0.02 seconds, 42.51 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.46it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 883.01it/s]

done in 0.03 seconds, 39.60 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.28it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 918.59it/s]

done in 0.02 seconds, 51.45 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.21it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 920.41it/s]

done in 0.02 seconds, 50.71 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 84.19it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 872.90it/s]

done in 0.02 seconds, 46.04 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 46.28it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 882.64it/s]

done in 0.03 seconds, 33.38 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.42it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 883.38it/s]

done in 0.02 seconds, 49.85 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.48it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 900.45it/s]

done in 0.02 seconds, 48.77 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.82it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 774.57it/s]

done in 0.02 seconds, 47.49 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.26it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 909.83it/s]

done in 0.02 seconds, 48.36 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 81.02it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 819.04it/s]

done in 0.04 seconds, 28.25 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.08it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 839.87it/s]

done in 0.02 seconds, 54.88 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.79it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 841.22it/s]

done in 0.02 seconds, 56.73 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.71it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 869.29it/s]

done in 0.02 seconds, 53.12 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 48.63it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 129.10it/s]

done in 0.03 seconds, 28.86 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.52it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 866.59it/s]

done in 0.02 seconds, 58.84 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 44.83it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 847.85it/s]

done in 0.03 seconds, 34.23 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.71it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 927.74it/s]

done in 0.02 seconds, 59.68 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 47.43it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 750.99it/s]

done in 0.03 seconds, 35.37 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.86it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 903.75it/s]

done in 0.03 seconds, 28.87 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 49.18it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 821.77it/s]

done in 0.03 seconds, 36.90 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 42.07it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 823.22it/s]

done in 0.03 seconds, 32.50 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 53.09it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 911.81it/s]

done in 0.03 seconds, 28.67 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 84.35it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 846.14it/s]

done in 0.03 seconds, 33.80 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 100.13it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 899.49it/s]

done in 0.04 seconds, 25.09 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 45.73it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 745.12it/s]

done in 0.03 seconds, 35.09 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 22.86it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 739.21it/s]

done in 0.05 seconds, 19.79 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.72it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 850.77it/s]

done in 0.02 seconds, 56.69 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 44.05it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 899.87it/s]

done in 0.04 seconds, 25.63 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 46.25it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 895.26it/s]

done in 0.03 seconds, 35.74 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.62it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 861.25it/s]

done in 0.02 seconds, 58.13 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.30it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 777.88it/s]

done in 0.02 seconds, 46.86 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 33.92it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 845.28it/s]

done in 0.04 seconds, 27.70 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.82it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 887.68it/s]

done in 0.02 seconds, 42.65 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.24it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 863.38it/s]

done in 0.02 seconds, 52.51 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 35.62it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 777.30it/s]

done in 0.04 seconds, 27.59 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.39it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 902.39it/s]

done in 0.02 seconds, 54.68 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.00it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 857.73it/s]

done in 0.02 seconds, 48.12 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 19.03it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 592.00it/s]

done in 0.06 seconds, 16.24 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.71it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 913.79it/s]

done in 0.02 seconds, 53.76 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 99.06it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 925.49it/s]

done in 0.02 seconds, 54.88 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.89it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 902.97it/s]

done in 0.02 seconds, 52.54 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.51it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 891.84it/s]

done in 0.02 seconds, 53.54 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 66.03it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 835.69it/s]

done in 0.03 seconds, 36.27 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.93it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 909.83it/s]

done in 0.02 seconds, 50.77 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.04it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 910.62it/s]

done in 0.02 seconds, 54.35 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 50.44it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 819.52it/s]

done in 0.03 seconds, 36.27 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 39.64it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 727.29it/s]

done in 0.03 seconds, 29.99 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.07it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 906.48it/s]

done in 0.02 seconds, 44.45 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.96it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 903.56it/s]

done in 0.03 seconds, 32.02 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.98it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 923.25it/s]

done in 0.03 seconds, 29.74 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 46.69it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 814.74it/s]

done in 0.03 seconds, 35.75 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 34.53it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 756.68it/s]

done in 0.04 seconds, 23.11 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 50.48it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 847.16it/s]

done in 0.03 seconds, 37.95 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.73it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 907.47it/s]

done in 0.02 seconds, 53.48 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.05it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 844.94it/s]

done in 0.02 seconds, 49.01 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.94it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 918.80it/s]

done in 0.02 seconds, 49.77 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.36it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 866.05it/s]

done in 0.02 seconds, 48.81 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.84it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 902.78it/s]

done in 0.02 seconds, 52.35 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 33.93it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 745.12it/s]

done in 0.04 seconds, 26.08 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.50it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 799.68it/s]

done in 0.02 seconds, 52.93 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.13it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 845.97it/s]

done in 0.02 seconds, 52.01 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.84it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 683.45it/s]

done in 0.02 seconds, 48.47 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.26it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 877.65it/s]

done in 0.02 seconds, 53.29 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.58it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 875.27it/s]

done in 0.02 seconds, 52.19 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 59.37it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 865.70it/s]

done in 0.02 seconds, 41.59 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.00it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 921.22it/s]

done in 0.02 seconds, 55.59 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.72it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 933.52it/s]

done in 0.02 seconds, 53.41 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.12it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 903.94it/s]

done in 0.02 seconds, 46.96 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 84.39it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 838.19it/s]

done in 0.02 seconds, 42.50 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 66.49it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 842.74it/s]

done in 0.02 seconds, 42.32 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 70.91it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 820.48it/s]

done in 0.02 seconds, 44.64 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.63it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 857.91it/s]

done in 0.02 seconds, 50.86 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 55.65it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 824.68it/s]

done in 0.03 seconds, 37.43 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.85it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 921.62it/s]

done in 0.02 seconds, 51.24 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.13it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 920.61it/s]

done in 0.02 seconds, 45.98 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.06it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 894.50it/s]

done in 0.02 seconds, 49.68 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.53it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 912.20it/s]

done in 0.02 seconds, 53.56 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.86it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 924.47it/s]

done in 0.02 seconds, 55.43 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.58it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 898.33it/s]

done in 0.02 seconds, 53.55 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 84.95it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 902.39it/s]

done in 0.02 seconds, 49.85 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 71.62it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 852.85it/s]

done in 0.02 seconds, 45.46 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 28.20it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 782.23it/s]

done in 0.05 seconds, 18.52 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 725.41it/s]

done in 0.05 seconds, 20.55 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.09it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 913.39it/s]

done in 0.02 seconds, 50.75 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.42it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 917.99it/s]

done in 0.02 seconds, 53.94 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.43it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 734.94it/s]

done in 0.02 seconds, 49.23 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.91it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 740.13it/s]

done in 0.02 seconds, 48.69 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.06it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 902.39it/s]

done in 0.02 seconds, 52.00 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.61it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 920.81it/s]

done in 0.02 seconds, 54.93 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.62it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 923.04it/s]

done in 0.02 seconds, 55.14 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.72it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 898.91it/s]

done in 0.02 seconds, 53.14 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.77it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 806.60it/s]

done in 0.02 seconds, 47.41 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.10it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 800.44it/s]

done in 0.02 seconds, 51.56 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.92it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 917.39it/s]

done in 0.02 seconds, 55.01 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.86it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 925.08it/s]

done in 0.02 seconds, 57.03 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.60it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 790.78it/s]

done in 0.02 seconds, 55.09 sentences/sec
gemma2

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 100.05it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 917.19it/s]

done in 0.02 seconds, 54.12 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.15it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 913.99it/s]

done in 0.02 seconds, 54.72 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.77it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 880.23it/s]

done in 0.02 seconds, 51.20 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.59it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 890.13it/s]

done in 0.02 seconds, 55.26 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.49it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 908.05it/s]

done in 0.02 seconds, 46.32 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.90it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 21.36it/s]

done in 0.07 seconds, 14.39 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 33.64it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 820.48it/s]

done in 0.05 seconds, 21.38 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.17it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 488.51it/s]

done in 0.03 seconds, 37.93 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.78it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 845.80it/s]

done in 0.02 seconds, 49.28 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.46it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 904.53it/s]

done in 0.02 seconds, 51.45 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 46.96it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 924.87it/s]

done in 0.03 seconds, 36.08 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 100.23it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 911.01it/s]

done in 0.02 seconds, 55.54 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 42.12it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 687.48it/s]

done in 0.03 seconds, 30.87 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.41it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 912.40it/s]

done in 0.02 seconds, 53.17 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 75.82it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 775.43it/s]

done in 0.02 seconds, 46.70 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.50it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 829.24it/s]

done in 0.02 seconds, 48.75 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 63.87it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 791.98it/s]

done in 0.02 seconds, 41.41 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.92it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 873.09it/s]

done in 0.02 seconds, 50.19 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 70.17it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 816.81it/s]

done in 0.03 seconds, 36.62 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.05it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 770.30it/s]

done in 0.02 seconds, 46.67 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.14it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 883.57it/s]

done in 0.02 seconds, 51.26 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.87it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 886.93it/s]

done in 0.02 seconds, 51.01 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.30it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 912.40it/s]

done in 0.02 seconds, 51.15 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.43it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 885.62it/s]

done in 0.02 seconds, 48.29 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.04it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 896.99it/s]

done in 0.02 seconds, 51.19 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 39.54it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 759.29it/s]

done in 0.03 seconds, 28.65 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.84it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 812.53it/s]

done in 0.02 seconds, 54.91 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.90it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 910.22it/s]

done in 0.03 seconds, 29.79 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 101.62it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 887.12it/s]

done in 0.02 seconds, 55.02 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.40it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 660.94it/s]

done in 0.02 seconds, 56.51 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.60it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 895.45it/s]

done in 0.02 seconds, 54.18 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.36it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 885.43it/s]

done in 0.02 seconds, 51.05 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 80.48it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 862.14it/s]

done in 0.05 seconds, 18.33 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 47.42it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 725.78it/s]

done in 0.03 seconds, 35.93 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 99.97it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 172.90it/s]

done in 0.02 seconds, 47.03 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.14it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 818.40it/s]

done in 0.02 seconds, 53.86 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.14it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 858.43it/s]

done in 0.02 seconds, 43.36 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 47.77it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 840.37it/s]

done in 0.03 seconds, 36.25 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 84.71it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 819.36it/s]

done in 0.02 seconds, 53.74 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 23.11it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 745.12it/s]

done in 0.05 seconds, 19.89 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 48.41it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 813.16it/s]

done in 0.03 seconds, 36.59 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.68it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 889.57it/s]

done in 0.04 seconds, 24.17 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 25.14it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 763.16it/s]

done in 0.05 seconds, 21.39 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.10it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 905.31it/s]

done in 0.02 seconds, 56.02 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.66it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 888.62it/s]

done in 0.02 seconds, 50.94 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.30it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 850.25it/s]

done in 0.02 seconds, 51.94 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.87it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 742.49it/s]

done in 0.02 seconds, 53.67 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.15it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 811.12it/s]

done in 0.02 seconds, 48.27 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.23it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 903.56it/s]

done in 0.02 seconds, 53.23 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.29it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 896.22it/s]

done in 0.02 seconds, 55.05 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.89it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 891.84it/s]

done in 0.02 seconds, 52.28 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.46it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 878.02it/s]

done in 0.02 seconds, 51.65 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.69it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 863.56it/s]

done in 0.02 seconds, 52.54 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.73it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 870.55it/s]

done in 0.02 seconds, 50.61 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 51.64it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 529.38it/s]

done in 0.03 seconds, 38.14 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.21it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 854.59it/s]

done in 0.02 seconds, 50.82 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.15it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 813.16it/s]

done in 0.03 seconds, 37.34 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.48it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 883.38it/s]

done in 0.02 seconds, 52.70 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.75it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 888.44it/s]

done in 0.02 seconds, 51.41 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.19it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 890.13it/s]

done in 0.02 seconds, 52.68 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.23it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 892.60it/s]

done in 0.02 seconds, 56.81 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.51it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 897.56it/s]

done in 0.02 seconds, 54.34 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.77it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 914.79it/s]

done in 0.02 seconds, 55.26 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 78.22it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 862.67it/s]

done in 0.03 seconds, 36.24 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.17it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 890.70it/s]

done in 0.02 seconds, 48.74 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.36it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 915.39it/s]

done in 0.02 seconds, 49.07 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 77.69it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 835.52it/s]

done in 0.02 seconds, 43.48 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.04it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 906.88it/s]

done in 0.02 seconds, 49.43 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 73.46it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 887.68it/s]

done in 0.02 seconds, 44.48 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.42it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 874.91it/s]

done in 0.02 seconds, 50.02 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 58.95it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 773.71it/s]

done in 0.03 seconds, 38.34 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 32.49it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 767.06it/s]

done in 0.04 seconds, 25.92 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.60it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 913.19it/s]

done in 0.02 seconds, 48.76 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.91it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 911.21it/s]

done in 0.02 seconds, 51.34 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.56it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 920.21it/s]

done in 0.02 seconds, 51.44 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.49it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 690.19it/s]

done in 0.02 seconds, 48.90 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 84.26it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 735.20it/s]

done in 0.02 seconds, 48.66 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.98it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 711.62it/s]

done in 0.05 seconds, 20.54 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.24it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 872.90it/s]

done in 0.04 seconds, 24.48 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.35it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 866.77it/s]

done in 0.02 seconds, 57.89 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 38.63it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 721.41it/s]

done in 0.04 seconds, 22.31 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 13.12it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 813.01it/s]

done in 0.08 seconds, 12.16 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.40it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 864.98it/s]

done in 0.02 seconds, 58.12 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 19.45it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 648.37it/s]

done in 0.08 seconds, 12.04 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 51.67it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 917.79it/s]

done in 0.03 seconds, 38.80 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 50.42it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 848.71it/s]

done in 0.02 seconds, 40.28 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 30.13it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 924.26it/s]

done in 0.04 seconds, 25.20 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 28.33it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 766.64it/s]

done in 0.04 seconds, 23.45 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 14.19it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 795.28it/s]

done in 0.09 seconds, 11.58 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.84it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 778.16it/s]

done in 0.02 seconds, 65.60 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 25.41it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 909.43it/s]

done in 0.04 seconds, 22.72 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 20.34it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 737.78it/s]

done in 0.06 seconds, 15.72 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 19.39it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 632.34it/s]

done in 0.11 seconds, 9.27 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 18.51it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 863.56it/s]

done in 0.07 seconds, 14.22 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.96it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 910.02it/s]

done in 0.02 seconds, 59.57 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.07it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 853.54it/s]

done in 0.02 seconds, 56.65 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.32it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 840.04it/s]

done in 0.04 seconds, 26.31 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 33.63it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 741.44it/s]

done in 0.07 seconds, 15.35 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 29.38it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 866.23it/s]

done in 0.04 seconds, 24.63 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.18it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 625.92it/s]

done in 0.03 seconds, 39.22 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.43it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 835.02it/s]

done in 0.02 seconds, 57.32 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.19it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 926.92it/s]

done in 0.04 seconds, 26.39 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.07it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 895.64it/s]

done in 0.04 seconds, 24.97 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.08it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 886.93it/s]

done in 0.02 seconds, 56.50 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 33.13it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 693.04it/s]

done in 0.04 seconds, 25.63 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.76it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 918.19it/s]

done in 0.02 seconds, 53.81 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.78it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 771.44it/s]

done in 0.02 seconds, 50.43 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 84.85it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 850.77it/s]

done in 0.02 seconds, 48.62 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.88it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 737.91it/s]

done in 0.02 seconds, 52.08 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 101.73it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 916.39it/s]

done in 0.02 seconds, 56.31 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 55.96it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 776.44it/s]

done in 0.03 seconds, 37.29 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.42it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 890.32it/s]

done in 0.02 seconds, 51.67 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.62it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 910.22it/s]

done in 0.02 seconds, 52.20 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.80it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 898.33it/s]

done in 0.02 seconds, 53.54 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 99.06it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 796.94it/s]

done in 0.02 seconds, 54.43 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 70.01it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 843.92it/s]

done in 0.02 seconds, 45.31 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 70.40it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 846.31it/s]

done in 0.02 seconds, 44.51 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.24it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 738.95it/s]

done in 0.02 seconds, 51.39 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 35.42it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 324.36it/s]

done in 0.04 seconds, 26.68 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 44.12it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 900.26it/s]

done in 0.03 seconds, 30.71 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.34it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 899.49it/s]

done in 0.02 seconds, 47.98 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.80it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 868.39it/s]

done in 0.02 seconds, 49.89 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.96it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 889.38it/s]

done in 0.02 seconds, 49.06 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.53it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 883.57it/s]

done in 0.02 seconds, 50.68 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 34.41it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 289.42it/s]

done in 0.04 seconds, 25.10 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.59it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 843.42it/s]

done in 0.02 seconds, 46.91 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 70.74it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 843.08it/s]

done in 0.02 seconds, 43.24 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 79.95it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 761.35it/s]

done in 0.02 seconds, 48.44 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 30.10it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 388.79it/s]

done in 0.04 seconds, 23.39 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.56it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 916.79it/s]

done in 0.02 seconds, 55.00 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.85it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 920.41it/s]

done in 0.02 seconds, 54.17 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 100.32it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 911.61it/s]

done in 0.02 seconds, 55.13 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.94it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 934.98it/s]

done in 0.02 seconds, 53.28 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.48it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 911.61it/s]

done in 0.02 seconds, 55.34 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 99.53it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 921.22it/s]

done in 0.02 seconds, 58.39 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.69it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 919.40it/s]

done in 0.02 seconds, 52.99 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.18it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 868.93it/s]

done in 0.02 seconds, 54.02 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.03it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 910.62it/s]

done in 0.02 seconds, 56.49 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.41it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 596.29it/s]

done in 0.02 seconds, 44.56 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.93it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 919.80it/s]

done in 0.02 seconds, 56.88 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 45.26it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 20.49it/s]

done in 0.08 seconds, 12.76 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 84.91it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 786.78it/s]

done in 0.02 seconds, 42.54 sentences/sec
dirty

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.57it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 909.83it/s]

done in 0.02 seconds, 52.99 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 30.37it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 69.94it/s]

done in 0.05 seconds, 18.58 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.43it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 922.03it/s]

done in 0.02 seconds, 50.57 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.53it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 917.79it/s]

done in 0.02 seconds, 53.96 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.06it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 833.86it/s]

done in 0.02 seconds, 44.33 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.80it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 901.23it/s]

done in 0.02 seconds, 52.09 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.95it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 905.51it/s]

done in 0.02 seconds, 53.02 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 55.37it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 820.00it/s]

done in 0.04 seconds, 28.05 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 32.99it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 831.71it/s]

done in 0.04 seconds, 25.62 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.22it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 920.61it/s]

done in 0.02 seconds, 53.91 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.00it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 898.91it/s]

done in 0.02 seconds, 53.42 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.01it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 921.42it/s]

done in 0.02 seconds, 48.52 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 42.49it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 775.86it/s]

done in 0.03 seconds, 31.67 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.35it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 834.85it/s]

done in 0.02 seconds, 51.63 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 80.68it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 856.33it/s]

done in 0.03 seconds, 32.19 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.09it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 902.97it/s]

done in 0.02 seconds, 52.69 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 68.96it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 828.59it/s]

done in 0.02 seconds, 44.63 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 78.36it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 889.57it/s]

done in 0.02 seconds, 49.86 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 67.10it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 829.24it/s]

done in 0.02 seconds, 44.97 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.01it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 895.84it/s]

done in 0.02 seconds, 51.60 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.42it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 906.09it/s]

done in 0.02 seconds, 51.65 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.34it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 912.60it/s]

done in 0.02 seconds, 53.12 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.41it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 879.12it/s]

done in 0.02 seconds, 52.08 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.02it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 881.16it/s]

done in 0.02 seconds, 50.99 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.35it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 848.19it/s]

done in 0.02 seconds, 46.02 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 40.16it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 778.60it/s]

done in 0.03 seconds, 28.78 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.20it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 916.19it/s]

done in 0.02 seconds, 42.61 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.37it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 909.83it/s]

done in 0.02 seconds, 46.56 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.91it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 875.45it/s]

done in 0.02 seconds, 49.95 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.92it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 31.58it/s]

done in 0.05 seconds, 19.06 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.39it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 916.19it/s]

done in 0.02 seconds, 51.19 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.35it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 920.41it/s]

done in 0.02 seconds, 52.27 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.74it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 916.19it/s]

done in 0.02 seconds, 52.15 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 75.92it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 855.98it/s]

done in 0.02 seconds, 47.02 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.94it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 921.83it/s]

done in 0.02 seconds, 52.58 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 80.96it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 880.79it/s]

done in 0.02 seconds, 52.11 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.70it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 883.20it/s]

done in 0.02 seconds, 51.02 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.48it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 892.60it/s]

done in 0.02 seconds, 52.43 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 53.14it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 751.94it/s]

done in 0.03 seconds, 38.32 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 39.61it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 642.41it/s]

done in 0.03 seconds, 30.31 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 80.45it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 880.79it/s]

done in 0.02 seconds, 48.60 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.77it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 904.14it/s]

done in 0.02 seconds, 55.66 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 52.71it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 795.28it/s]

done in 0.03 seconds, 37.57 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.48it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 890.51it/s]

done in 0.02 seconds, 54.82 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.18it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 916.59it/s]

done in 0.02 seconds, 55.38 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 70.89it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 785.60it/s]

done in 0.02 seconds, 43.14 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 75.26it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 910.42it/s]

done in 0.04 seconds, 25.60 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.53it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 913.19it/s]

done in 0.02 seconds, 54.02 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.18it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 928.35it/s]

done in 0.02 seconds, 58.38 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.99it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 892.98it/s]

done in 0.02 seconds, 54.36 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 88.30it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 899.87it/s]

done in 0.02 seconds, 53.34 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 70.73it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 896.22it/s]

done in 0.05 seconds, 18.46 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 84.02it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 869.47it/s]

done in 0.02 seconds, 46.94 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 98.97it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 905.51it/s]

done in 0.02 seconds, 54.66 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 71.19it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 842.57it/s]

done in 0.02 seconds, 43.66 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 84.98it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 902.00it/s]

done in 0.02 seconds, 51.60 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.03it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 890.89it/s]

done in 0.02 seconds, 50.25 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.67it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 883.57it/s]

done in 0.02 seconds, 50.72 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.01it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 892.79it/s]

done in 0.02 seconds, 48.27 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.46it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 913.79it/s]

done in 0.02 seconds, 52.70 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.25it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 866.23it/s]

done in 0.02 seconds, 50.06 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.03it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 920.01it/s]

done in 0.02 seconds, 53.46 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.77it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 922.23it/s]

done in 0.02 seconds, 51.42 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 44.61it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 841.22it/s]

done in 0.03 seconds, 34.60 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.37it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 895.64it/s]

done in 0.03 seconds, 31.62 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 97.49it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 928.56it/s]

done in 0.04 seconds, 27.80 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 68.72it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 859.14it/s]

done in 0.02 seconds, 44.12 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.48it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 896.03it/s]

done in 0.02 seconds, 50.78 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 84.64it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 916.99it/s]

done in 0.02 seconds, 51.15 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.87it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 919.60it/s]

done in 0.02 seconds, 51.97 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 58.91it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 728.30it/s]

done in 0.02 seconds, 40.09 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 33.98it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 764.41it/s]

done in 0.04 seconds, 26.86 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.01it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 665.87it/s]

done in 0.02 seconds, 48.30 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.44it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 920.41it/s]

done in 0.02 seconds, 52.16 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.04it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 760.66it/s]

done in 0.02 seconds, 51.40 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.86it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 805.20it/s]

done in 0.02 seconds, 54.31 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.99it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 914.19it/s]

done in 0.02 seconds, 52.09 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 79.90it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 848.71it/s]

done in 0.02 seconds, 47.45 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.12it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 924.06it/s]

done in 0.02 seconds, 53.11 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.60it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 917.79it/s]

done in 0.02 seconds, 54.13 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 35.91it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 772.72it/s]

done in 0.04 seconds, 28.49 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.79it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 880.60it/s]

done in 0.02 seconds, 52.98 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.91it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 915.79it/s]

done in 0.02 seconds, 55.40 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 18.44it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 562.16it/s]

done in 0.07 seconds, 14.67 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.59it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 695.80it/s]

done in 0.02 seconds, 46.62 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.88it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 907.27it/s]

done in 0.02 seconds, 54.90 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.94it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 899.10it/s]

done in 0.02 seconds, 51.15 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.18it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 909.24it/s]

done in 0.02 seconds, 43.48 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 66.79it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 854.76it/s]

done in 0.02 seconds, 40.63 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.89it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 871.45it/s]

done in 0.02 seconds, 50.73 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.93it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 738.69it/s]

done in 0.02 seconds, 45.59 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 50.83it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 745.52it/s]

done in 0.03 seconds, 33.46 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 40.95it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 671.73it/s]

done in 0.03 seconds, 30.40 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.22it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 906.88it/s]

done in 0.02 seconds, 49.03 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 37.23it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 137.27it/s]

done in 0.04 seconds, 24.49 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.34it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 904.72it/s]

done in 0.02 seconds, 52.78 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 81.68it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 863.56it/s]

done in 0.02 seconds, 49.90 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 34.45it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 760.25it/s]

done in 0.04 seconds, 27.35 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.45it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 880.23it/s]

done in 0.02 seconds, 50.89 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.99it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 931.24it/s]

done in 0.02 seconds, 51.68 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.32it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 928.56it/s]

done in 0.02 seconds, 48.07 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 75.81it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 871.09it/s]

done in 0.02 seconds, 46.53 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 83.85it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 796.64it/s]

done in 0.02 seconds, 49.66 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.60it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 916.19it/s]

done in 0.02 seconds, 54.89 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 25.92it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 720.92it/s]

done in 0.05 seconds, 21.36 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 77.29it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 714.41it/s]

done in 0.03 seconds, 37.91 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.94it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 922.64it/s]

done in 0.02 seconds, 52.29 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.32it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 920.01it/s]

done in 0.02 seconds, 50.56 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 82.73it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 778.60it/s]

done in 0.02 seconds, 45.79 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 96.19it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 914.79it/s]

done in 0.02 seconds, 47.88 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 59.63it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 818.72it/s]

done in 0.03 seconds, 38.48 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.90it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 896.79it/s]

done in 0.02 seconds, 52.39 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 86.07it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 912.20it/s]

done in 0.02 seconds, 46.60 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 87.10it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 658.45it/s]

done in 0.02 seconds, 44.04 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.38it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 908.05it/s]

done in 0.02 seconds, 50.93 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 56.82it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 826.30it/s]

done in 0.03 seconds, 38.70 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 56.26it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 768.75it/s]

done in 0.03 seconds, 37.31 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 85.55it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 813.80it/s]

done in 0.02 seconds, 49.34 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 51.58it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 676.39it/s]

done in 0.03 seconds, 35.83 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.20it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 927.53it/s]

done in 0.02 seconds, 53.94 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.68it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 921.22it/s]

done in 0.02 seconds, 54.14 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 79.43it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 811.43it/s]

done in 0.02 seconds, 47.37 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.98it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 884.13it/s]

done in 0.02 seconds, 48.44 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.02it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 925.49it/s]

done in 0.02 seconds, 54.93 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 89.46it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 906.48it/s]

done in 0.02 seconds, 48.76 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 50.13it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 739.87it/s]

done in 0.03 seconds, 35.27 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 72.58it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 860.37it/s]

done in 0.02 seconds, 47.56 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.42it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 844.26it/s]

done in 0.02 seconds, 52.06 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 30.50it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 721.79it/s]

done in 0.04 seconds, 24.29 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 84.48it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 785.01it/s]

done in 0.02 seconds, 40.95 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 93.94it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 917.99it/s]

done in 0.02 seconds, 50.39 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 90.78it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 915.39it/s]

done in 0.02 seconds, 50.75 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.94it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 900.45it/s]

done in 0.02 seconds, 50.77 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 84.77it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 887.68it/s]

done in 0.02 seconds, 52.93 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.54it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 824.19it/s]

done in 0.02 seconds, 58.05 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 27.36it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 802.74it/s]

done in 0.07 seconds, 13.95 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 91.20it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 471.59it/s]

done in 0.02 seconds, 44.42 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 92.99it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 904.14it/s]

done in 0.02 seconds, 46.94 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 28.86it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 853.02it/s]

done in 0.04 seconds, 24.80 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 95.16it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 915.59it/s]

done in 0.02 seconds, 54.40 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.32it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 917.19it/s]

done in 0.02 seconds, 41.96 sentences/sec

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

calculating scores...
computing bert embedding.

100%|██████████| 1/1 [00:00<00:00, 94.92it/s]

computing greedy matching.

100%|██████████| 1/1 [00:00<00:00, 922.43it/s]

done in 0.02 seconds, 49.42 sentences/sec

In [46]:
def calculate_eval_stats(eval_answer_results_text):

    total_stat_table = eval_answer_results_text.describe().loc['mean']
    eval_answer_results_text.set_index('pp_id', inplace=True)

    hos_results = eval_answer_results_text.loc[127:155]
    hos_stat_table = hos_results.describe().loc['mean']
    # print('hos', hos_stat_table)

    flights_results = eval_answer_results_text.loc[111:127]
    flights_stat_table = flights_results.describe().loc['mean']

    ppp_results = eval_answer_results_text.loc[62:92] #[eval_answer_results_text['pp_id'] >= 62][eval_answer_results_text['pp_id'] <=91]
    ppp_stat_table = ppp_results.describe().loc['mean']

    dish_results = eval_answer_results_text.loc[92:111] #[eval_answer_results_text['pp_id'] >= 92]
    dish_stat_table = dish_results.describe().loc['mean']
    
    menu_results = eval_answer_results_text.loc[:31] #[eval_answer_results_text['pp_id'] < 31]
    menu_stat_table = menu_results.describe().loc['mean']

    chi_results = eval_answer_results_text.loc[31:62] #[eval_answer_results_text['pp_id'] >= 31][eval_answer_results_text['pp_id'] <=61]
    chi_stat_table = chi_results.describe().loc['mean']


    final_result = pd.concat([total_stat_table, menu_stat_table, dish_stat_table, chi_stat_table, ppp_stat_table, hos_stat_table, flights_stat_table], axis=1)
    final_result = final_result.transpose()
    final_result['data'] = ['Total', 'Menu', 'Dish', 'CFI','PPP', 'Hospital', 'Flights' ]
    return final_result

In [47]:
total_stat_df = []
for model in models[:3] + ['dirty']: #, 'llama3.1', 'mistral', 'gemma2']:
    eval_answer_results = pd.read_csv(f'/projects/bces/lanl2/LLM4DC/evaluation/{model}_answer_result.csv')
    # evaL_answer_results_flag = eval_answer_results.merge(numeric_pp_tag, on='pp_id', how='left', suffixes=('', '_numeric'))
    # eval_answer_results_text = evaL_answer_results_flag[evaL_answer_results_flag['flag'] == 0]
    final_stat = calculate_eval_stats(eval_answer_results)
    final_stat['model'] = [model] * 7
    total_stat_df.append(final_stat)
total_stat_df = pd.concat(total_stat_df, axis=0)
total_stat_df = total_stat_df.reset_index()
total_stat_df.iloc[:,2:]

,accuracy,semantic_similarity,precision,recall,f1,pp_id,data,model
0,0.387324,0.639694,0.503457,0.489658,0.491543,76.739437,Total,llama3.1
1,0.258065,0.485702,0.399386,0.345164,0.360399,NaN,Menu,llama3.1
2,0.470588,0.779911,0.644706,0.644706,0.644706,NaN,Dish,llama3.1
3,0.483871,0.756498,0.624194,0.641129,0.625320,NaN,CFI,llama3.1
4,0.478261,0.703673,0.583092,0.581004,0.581095,NaN,PPP,llama3.1
5,0.464286,0.734147,0.549603,0.522619,0.532738,NaN,Hospital,llama3.1
6,0.117647,0.307606,0.117647,0.117647,0.117647,NaN,Flights,llama3.1
7,0.218310,0.527091,0.360445,0.338280,0.339757,76.739437,Total,mistral
8,0.225806,0.443093,0.382488,0.293209,0.317900,NaN,Menu,mistral
9,0.470588,0.809216,0.709412,0.706261,0.707406,NaN,Dish,mistral
10,0.161290,0.555628,0.399770,0.387097,0.372350,NaN,CFI,mistral
11,0.521739,0.704361,0.555868,0.569488,0.561338,NaN,PPP,mistral
12,0.035714,0.434654,0.146008,0.137202,0.139678,NaN,Hospital,mistral
13,0.058824,0.309366,0.058824,0.058824,0.058824,NaN,Flights,mistral
14,0.359155,0.619784,0.435857,0.443991,0.434197,76.739437,Total,gemma2
15,0.322581,0.543026,0.425062,0.420247,0.418153,NaN,Menu,gemma2
16,0.294118,0.655353,0.391176,0.391176,0.391176,NaN,Dish,gemma2
17,0.322581,0.589460,0.453405,0.489247,0.449839,NaN,CFI,gemma2
18,0.565217,0.752417,0.638509,0.644669,0.641294,NaN,PPP,gemma2
19,0.464286,0.748684,0.475840,0.477679,0.476732,NaN,Hospital,gemma2
20,0.235294,0.464268,0.235294,0.235294,0.235294,NaN,Flights,gemma2
21,0.225352,0.486886,0.314576,0.302833,0.299161,76.739437,Total,dirty
22,0.225806,0.425082,0.351254,0.272918,0.291398,NaN,Menu,dirty
23,0.470588,0.853741,0.680294,0.680294,0.680294,NaN,Dish,dirty
24,0.161290,0.496739,0.251075,0.255376,0.231797,NaN,CFI,dirty
25,0.565217,0.691123,0.612631,0.631599,0.620396,NaN,PPP,dirty
26,0.000000,0.332942,0.047932,0.054762,0.050990,NaN,Hospital,dirty
27,0.058824,0.195861,0.058824,0.058824,0.058824,NaN,Flights,dirty

In [48]:
total_stat_df.to_csv('answer_performance_table_llama_gemma_mistral.csv', header=True, index=False)

## numeric tags

In [51]:
numeric_pp_tag = pd.read_csv('/projects/bces/lanl2/LLM4DC/evaluation/purposes_category.csv')
numeric_pp_tag.columns = ['pp_id', 'purposes', 'flag']

In [52]:
evaL_answer_results_flag = eval_answer_results.merge(numeric_pp_tag, on='pp_id', how='left', suffixes=('', '_numeric'))

In [53]:
eval_answer_results_text = evaL_answer_results_flag[evaL_answer_results_flag['flag'] == 0]

In [54]:
def eval_answers_numeric(answer_gt_path, answer_preds_llama):
    answer_gt = load_answer_dataset(answer_gt_path)
    answer_gt = pd.DataFrame(answer_gt)
    answer_preds_llama = load_answer_dataset(answer_preds_llama)
    answer_preds_llama = pd.DataFrame(answer_preds_llama)
    answer_compare = answer_gt.merge(answer_preds_llama[['pp_id', 'answer']], on='pp_id', how='left', suffixes=('_gt', '_preds'))
    answer_compare = answer_compare.merge(numeric_pp_tag, on='pp_id', how='left', suffixes=('', '_numeric'))
    answer_compare = answer_compare[answer_compare['flag'] == 1]
    answer_compare['answer_preds'] = pd.to_numeric(answer_compare['answer_preds'], errors='coerce')
    answer_compare['answer_gt'] = pd.to_numeric(answer_compare['answer_gt'], errors='coerce')
    answer_compare['difference'] = (answer_compare['answer_preds'] - answer_compare['answer_gt']).abs()/answer_compare['answer_gt']
    return answer_compare

In [55]:
total_stat_df = []
for model in ['dirty', 'mistral', 'gemma2', 'llama3.1']:
    answer_gt_path = '/projects/bces/lanl2/LLM4DC/evaluation/answer_1-154_gt.json'
    # answer_preds_llama = '/projects/bces/lanl2/LLM4DC/evaluation/answer_1-110_llama3.1.json'
    # model = 'gemma2'
    # model = 'dirty'
    # model = 'llama3.1'
    # model = 'mistral'
    answer_preds = f'/projects/bces/lanl2/LLM4DC/evaluation/answer_1-154_{model}.json'
    # answer_preds = f'/projects/bces/lanl2/LLM4DC/evaluation/answer_1-110_dirty.json'
    eval_answer_results = eval_answers_numeric(answer_gt_path, answer_preds)
    # eval_answer_results.to_csv(f'evaluation/numeric_answer_diff_{model}.csv')
    final_stat = calculate_eval_stats(eval_answer_results[['difference', 'pp_id']])
    final_stat['model'] = [model] * 7
    total_stat_df.append(final_stat)

In [56]:
total_stat_df = pd.concat(total_stat_df, axis=0)

In [57]:
total_stat_df.to_csv('evaluation/numeric_answer_stats.csv')

In [58]:
dish_results = eval_answer_results_text[eval_answer_results_text['pp_id'] >= 92]
dish_stat_table = dish_results.describe().loc['mean']

In [59]:
dish_stat_table

pp_id                  119.000000
Unnamed: 0             106.176471
accuracy                 0.205882
semantic_similarity      0.632322
precision                0.350209
recall                   0.355833
f1                       0.352727
flag                     0.000000
Name: mean, dtype: float64

In [60]:
eval_answer_results.describe()

            pp_id      answer_gt   answer_preds  flag  difference
count   62.000000      62.000000      62.000000  62.0   62.000000
mean    73.419355    6070.641350    6068.683016   1.0    0.260413
std     53.756448   24804.745238   24805.229700   0.0    0.431859
min      1.000000       0.700000       0.000000   1.0    0.000000
25%     24.250000       3.250000       3.000000   1.0    0.000000
50%     63.500000       9.500000       8.500000   1.0    0.044444
75%    125.500000      25.250000      19.750000   1.0    0.326087
max    154.000000  140400.000000  140400.000000   1.0    2.500000

In [61]:
ppp_results = eval_answer_results[eval_answer_results['pp_id'] >= 62][eval_answer_results['pp_id'] <=91]

/tmp/ipykernel_1743614/2424205661.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ppp_results = eval_answer_results[eval_answer_results['pp_id'] >= 62][eval_answer_results['pp_id'] <=91]

In [64]:
dish_results = eval_answer_results[eval_answer_results['pp_id'] >= 92]

In [65]:
chi_results = eval_answer_results[eval_answer_results['pp_id'] >= 31][eval_answer_results['pp_id'] <=61]

/tmp/ipykernel_1743614/3367146683.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  chi_results = eval_answer_results[eval_answer_results['pp_id'] >= 31][eval_answer_results['pp_id'] <=61]

In [66]:
menu_results = eval_answer_results[eval_answer_results['pp_id'] < 31]

In [67]:
ppp_results.describe()

           pp_id      answer_gt   answer_preds  flag  difference
count   7.000000       7.000000       7.000000   7.0    7.000000
mean   68.428571   53280.180327   53281.608898   1.0    0.142857
std     7.091242   57649.758793   57648.218844   0.0    0.377964
min    62.000000       0.862289       0.862289   1.0    0.000000
25%    63.500000    1005.000000    1010.000000   1.0    0.000000
50%    66.000000   37030.400000   37030.400000   1.0    0.000000
75%    72.500000   96760.000000   96760.000000   1.0    0.000000
max    79.000000  140400.000000  140400.000000   1.0    1.000000

In [68]:
dish_results.describe()

            pp_id  answer_gt  answer_preds  flag  difference
count   26.000000  26.000000     26.000000  26.0   26.000000
mean   131.346154  14.761592     11.591719   1.0    0.217880
std     16.069704  17.440981     13.343632   0.0    0.296455
min     92.000000   1.000000      1.000000   1.0    0.000000
25%    119.500000   3.500000      2.250000   1.0    0.000000
50%    132.500000  11.000000      7.310000   1.0    0.119318
75%    146.250000  19.436047     16.000000   1.0    0.326087
max    154.000000  83.600000     54.000000   1.0    1.000000

In [69]:
menu_results.describe()

           pp_id   answer_gt  answer_preds  flag  difference
count  20.000000   20.000000     20.000000  20.0   20.000000
mean   13.800000   47.450000     45.250000   1.0    0.378203
std     9.833348   82.257283     82.667294   0.0    0.597454
min     1.000000    2.000000      0.000000   1.0    0.000000
25%     5.750000    6.000000      5.000000   1.0    0.000000
50%    10.500000    9.500000     13.000000   1.0    0.169753
75%    22.500000   48.750000     26.000000   1.0    0.416667
max    30.000000  273.000000    273.000000   1.0    2.500000

In [70]:
chi_results.describe()

           pp_id    answer_gt  answer_preds  flag  difference
count   9.000000     9.000000      9.000000   9.0    9.000000
mean   42.444444   231.744444    231.188889   1.0    0.212963
std     8.202303   669.278539    669.493257   0.0    0.370602
min    31.000000     0.700000      0.000000   1.0    0.000000
25%    35.000000     3.000000      1.000000   1.0    0.000000
50%    44.000000     3.000000      3.000000   1.0    0.000000
75%    49.000000     4.000000      5.000000   1.0    0.250000
max    54.000000  2016.000000   2016.000000   1.0    1.000000

In [71]:
eval_answer_results = pd.DataFrame(eval_answer_results)

In [72]:
eval_answer_results['accuracy'].sum()

KeyError: 'accuracy'

In [73]:
eval_answer_results.describe()

            pp_id      answer_gt   answer_preds  flag  difference
count   62.000000      62.000000      62.000000  62.0   62.000000
mean    73.419355    6070.641350    6068.683016   1.0    0.260413
std     53.756448   24804.745238   24805.229700   0.0    0.431859
min      1.000000       0.700000       0.000000   1.0    0.000000
25%     24.250000       3.250000       3.000000   1.0    0.000000
50%     63.500000       9.500000       8.500000   1.0    0.044444
75%    125.500000      25.250000      19.750000   1.0    0.326087
max    154.000000  140400.000000  140400.000000   1.0    2.500000

## answer eval ttest

In [75]:
from scipy import stats

In [76]:
dirty_answer_result = pd.read_csv('/projects/bces/lanl2/LLM4DC/evaluation/dirty_answer_result.csv')
dirty_answer_result = dirty_answer_result.iloc[:,1:]
gemma2_answer_result = pd.read_csv('/projects/bces/lanl2/LLM4DC/evaluation/gemma2_answer_result.csv')
gemma2_answer_result = gemma2_answer_result.iloc[:, 1:]
llama_answer_result = pd.read_csv('/projects/bces/lanl2/LLM4DC/evaluation/llama3.1_answer_result.csv')
llama_answer_result = llama_answer_result.iloc[:,1:]
mistral_answer_result = pd.read_csv('/projects/bces/lanl2/LLM4DC/evaluation/mistral_answer_result.csv')
mistral_answer_result = mistral_answer_result.iloc[:,1:]

In [77]:
answer_result = llama_answer_result.merge(gemma2_answer_result, on='pp_id', how='left', suffixes=('_llama3.1', '_gemma2')).merge(mistral_answer_result, on='pp_id', how='left', suffixes=('', '_mistral'))

In [78]:
answer_result = answer_result.merge(dirty_answer_result, on='pp_id', how='left', suffixes=('', '_dirty'))

In [79]:
answer_result.columns

Index(['accuracy_llama3.1', 'semantic_similarity_llama3.1',
       'precision_llama3.1', 'recall_llama3.1', 'f1_llama3.1',
       'bertscore_p_llama3.1', 'bertscore_r_llama3.1', 'bertscore_f1_llama3.1',
       'pp_id', 'accuracy_gemma2', 'semantic_similarity_gemma2',
       'precision_gemma2', 'recall_gemma2', 'f1_gemma2', 'bertscore_p_gemma2',
       'bertscore_r_gemma2', 'bertscore_f1_gemma2', 'accuracy',
       'semantic_similarity', 'precision', 'recall', 'f1', 'bertscore_p',
       'bertscore_r', 'bertscore_f1', 'accuracy_dirty',
       'semantic_similarity_dirty', 'precision_dirty', 'recall_dirty',
       'f1_dirty', 'bertscore_p_dirty', 'bertscore_r_dirty',
       'bertscore_f1_dirty'],
      dtype='object')

In [84]:
metric_names = ['accuracy','semantic_similarity', 'precision', 'recall', 'f1', 'bertscore_p', 'bertscore_r','bertscore_f1']

In [98]:
ttest_result = []
for m in metric_names:
    model_list = models[:3] + ['dirty'] #['llama', 'gemma2', 'mistral', 'dirty']
    llama_result = stats.ttest_rel(answer_result[f'{m}_dirty'].values, answer_result[f'{m}_llama3.1'].values)
    gemma_result = stats.ttest_rel(answer_result[f'{m}_dirty'].values, answer_result[f'{m}_gemma2'].values)
    # print(answer_result[f'{m}_llama'].values)
    mistral_result = stats.ttest_ind(answer_result[f'{m}_dirty'].values, answer_result[f'{m}'].values)
    ttest_result.append({f'{m}':[llama_result.pvalue.item(), gemma_result.pvalue.item(), mistral_result.pvalue.item()]})
    # print(gemma_result)
    # print(mistral_result)
    # break

KeyError: 'bertscore_p_llama3.1'

In [81]:
def ttest_answer(answer_result):
    ttest_result = []
    for m in metric_names:
        model_list = ['llama', 'gemma2', 'mistral', 'dirty']
        llama_result = stats.ttest_rel(answer_result[f'{m}_dirty'].values, answer_result[f'{m}_llama'].values)
        gemma_result = stats.ttest_rel(answer_result[f'{m}_dirty'].values, answer_result[f'{m}_gemma2'].values)
        # print(answer_result[f'{m}_llama'].values)
        mistral_result = stats.ttest_ind(answer_result[f'{m}_dirty'].values, answer_result[f'{m}'].values)
        ttest_result.append({f'{m}':[llama_result.pvalue.item(), gemma_result.pvalue.item(), mistral_result.pvalue.item()]})
    combined_data = {k: v for d in ttest_result for k, v in d.items()}

    ttest_result = pd.DataFrame(combined_data)
    return ttest_result

In [82]:
combined_data = {k: v for d in ttest_result for k, v in d.items()}

ttest_result = pd.DataFrame(combined_data)

NameError: name 'ttest_result' is not defined

In [83]:
ttest_result

NameError: name 'ttest_result' is not defined

In [ ]:
ppp_results = answer_result[answer_result['pp_id'] >= 62][answer_result['pp_id'] <=91]
ppp_ttest = ttest_answer(ppp_results)

In [ ]:
ppp_ttest

In [ ]:
dish_result= answer_result[answer_result['pp_id'] >= 92]
dish_ttest = ttest_answer(dish_result)
dish_ttest

In [ ]:
menu_results = answer_result[answer_result['pp_id'] < 31]
menu_ttest = ttest_answer(menu_results)
menu_ttest

In [ ]:
chi_results = answer_result[answer_result['pp_id'] >= 31][answer_result['pp_id'] <=61]
chi_ttest = ttest_answer(chi_results)
chi_ttest

In [ ]:
ppp_results = answer_result[answer_result['pp_id'] >= 62][answer_result['pp_id'] <=91]
ppp_ttest = ttest_answer(ppp_results)
ppp_ttest

In [4]:
def json_to_custom_string(data):
    # Serialize JSON with indentation for readability within each nested structure
    json_str = json.dumps(data, indent=None, separators=(r'')
    
    # Insert newline only after each top-level key-value pair
    # This keeps inner lists and dicts intact without adding extra line breaks
    formatted_str = json_str[1:-1].replace('", "', '",\n"')  # Exclude outer braces for custom formatting
    return f"{{\n{formatted_str}\n}}"

In [ ]:
json.dumps(data, indent=1, sepera)

In [11]:
data = {'table_caption': 'A mix of simple bibliographic description of the menus', 'columns': ['id', 'name', 'sponsor', 'event', 'venue', 'place', 'physical_description', 'occasion', 'notes', 'call_number', 'keywords', 'language', 'date', 'location', 'location_type', 'currency', 'currency_symbol', 'status', 'page_count', 'dish_count'], 'table_column_priority': [['id', '12579', '25121', '21960'], ['name', '', '', ''], ['sponsor', 'TRUSTEES OF THE MISSOURI BOTANICAL GARDEN', 'HOLLAND HOUSE', 'BATTERY PARK HOTEL'], ['event', '11TH ANNUAL BANQUET', 'LUNCHEON', 'CHRISTMAS DINNER'], ['venue', 'PROF;', 'COMMERCIAL', 'COMMERCIAL'], ['place', 'SOUTHERN HOTEL,ST. LOUIS,MO.', '', 'ASHVILLE, NC'], ['physical_description', 'BROADSIDE; ILLUS; 5.5 X 8.75;', 'CARD;6X8.75;', 'BOOKLET; ILLUS; COL; 6 X 8;'], ['occasion', 'ANNUAL', 'DAILY;', 'RELIGIOUS HOLIDAY'], ['notes', 'WINES LISTED FOR EACH COURSE;', 'ENGLISH ON ONE SIDE,FRENCH ON ONE SIDE;', 'PRINTED ON PARCHMENT-LIKE PAPER; RED LION; DRAWING OF HOTEL; TIED WITH TWINE AND SEALING WAX; MOST OF BOOKLET CONSISTS OF INFORMATION AND PRAISE ABOUT THE HOTEL;'], ['call_number', '1900-2627', '1900-517', '1898-432'], ['keywords', '', '', ''], ['language', '', '', ''], ['date', '1900-03-31', '1900-01-25', '1898-12-25'], ['location', 'Trustees Of The Missouri Botanical Garden', 'Holland House', 'Battery Park Hotel'], ['location_type', '', '', ''], ['currency', '', 'Dollars', ''], ['currency_symbol', '', '$', ''], ['status', 'complete', 'complete', 'complete'], ['page_count', '2', '2', '16'], ['dish_count', '22.0', '546.0', '28.0']]}

In [27]:
data_str = '\{\n'
for key, value in data.items():
    if key in ['table_caption', 'columns']:
        data_str += f'{key}: {value},\n'
    else:
        data_str += key + ': [\n'
        for l in value:
            data_str += f'  {l},\n'
data_str += '  ]\n}'

In [ ]:
type(data_str)

In [ ]:
pprint.pprint(data_str)

In [10]:
import pandas as pd
import pprint

In [ ]:
pprint.pprint(json_to_custom_string(data))

In [28]:
paragraph = "[    {'from': ['Luncheon', 'lunch'], 'to': 'Luncheon'},    {'from': ['Dinner'], 'to': 'Dinner'},  # No change needed for Dinner    {'from': ['Breakfast'], 'to': 'Breakfast'},  # No change needed for Breakfast    {'from': ['', 'Unknown', None], 'to': 'Unknown'},  # Replace missing values with Unknown    {'from': ['Banquet', 'Annual Banquet'], 'to': 'Annual Banquet'},    {'from': ['Tiffin'], 'to': 'Tiffin'}  # No change needed for Tiffin]"

In [3]:
raw_string = """```python
[
    {'from': ['HONOLULU', 'Honolulu'], 'to': 'Honolulu'},
    {'from': ['KANEOHE'], 'to': 'Kaneohe'},  # corrected spelling
    {'from': ['KIHEI'], 'to': 'Kihei'},  # corrected spelling
    {'from': ['Kailua Kona', 'KAUNAKAKAI', 'WAIMANALO', 'Waimea', 'kalaheo', 'Kahului'], 'to': 'Unknown'},  # unknown cities
    {'from': ['HONOLULUulu'], 'to': 'Honolulu'}  # corrected spelling
]
```"""

In [4]:
result = re.findall(r'(\[(:?\n?.*\n?)*\])', raw_string, re.DOTALL)

In [5]:
if result:
        for r in result:
            raw_string = r[0]

In [ ]:
raw_string

In [ ]:
eval(raw_string)

In [26]:
paragraph = re.sub(r'#.*\{$', '{', paragraph, flags=re.MULTILINE)

In [29]:
result = re.findall(r'(\[(:?\n?(^#.*\{|]}).*\n?)*\])', paragraph, re.DOTALL)

In [ ]:
line = "{'city':['hhhh'] #????ddfgtecg"

In [ ]:
input = '''
[{'foo':'bar'} # 000asd
]'''
eval(input)

In [ ]:
paragraph

In [ ]:
import pandas as pd
import json

def df_to_table_format(df, table_caption):
    # Extract column headers and index to form the first row in the table
    columns = ["competition"] + df.columns.tolist()
    
    # Prepare rows by combining index and corresponding row values in the DataFrame
    table_column_priority = [columns]  # Start with header row
    for idx, row in df.iterrows():
        table_column_priority.append([idx] + row.tolist())
    
    # Create the dictionary in the required format
    table_data = {
        "table_caption": table_caption,
        "columns": columns,
        "table_column_priority": table_column_priority
    }
    
    # Convert to JSON string with indentation for readability
    return json.dumps(table_data, indent=2)

# Example DataFrame
data = {
    "total matches": ["55", "2", "5"],
    "cardiff win": ["19", "0", "2"],
    "draw": ["16", "27", "0"],
    "swansea win": ["20", "2", "3"]
}
index = ["league", "fa cup", "league cup"]

df = pd.DataFrame(data, index=index)

# Convert DataFrame to the specified format and print
table_format_json = df_to_table_format(df, "south wales derby")
print(table_format_json)

In [ ]:
import pandas as pd
import json

def df_to_table_format(df, table_caption):
    # Extract column headers and index to form the first row in the table
    columns = ["competition"] + df.columns.tolist()
    
    # Prepare rows by combining index and corresponding row values in the DataFrame
    table_column_priority = [columns]  # Start with header row
    for idx, row in df.iterrows():
        table_column_priority.append([idx] + row.tolist())
    
    # Create the dictionary in the required format
    table_data = {
        "table_caption": table_caption,
        "columns": columns,
        "table_column_priority": table_column_priority
    }
    
    # Format 'columns' as a compact list and use json.dumps for the rest
    columns_str = f'"columns": {json.dumps(columns)}'
    table_column_priority_str = f'"table_column_priority": {json.dumps(table_column_priority)}'
    caption_str = f'"table_caption": "{table_caption}"'
    
    # Concatenate each component into a final JSON format
    final_output = f'{{\n  {caption_str},\n  {columns_str},\n  {table_column_priority_str}\n}}'
    
    return final_output

# Example DataFrame
data = {
    "total matches": ["55", "2", "5"],
    "cardiff win": ["19", "0", "2"],
    "draw": ["16", "27", "0"],
    "swansea win": ["20", "2", "3"]
}
index = ["league", "fa cup", "league cup"]

df = pd.DataFrame(data, index=index)

# Convert DataFrame to the specified format and print
table_format_json = df_to_table_format(df, "south wales derby")
print(table_format_json)

In [ ]:
import pandas as pd
import json

def df_to_table_format(df, table_caption):
    # Prepare rows for table_column_priority
    table_column_priority = []
    
    # The first list is the competition names (the DataFrame index)
    table_column_priority.append(["competition"] + df.index.tolist())
    
    # Append each DataFrame column values to table_column_priority
    for col in df.columns:
        table_column_priority.append([col] + df[col].tolist())
    
    # Create the final dictionary
    table_data = {
        "table_caption": table_caption,
        "columns": ["competition"] + df.columns.tolist(),
        "table_column_priority": table_column_priority
    }
    
    return table_data

# Example DataFrame
data = {
    "total matches": ["55", "2", "5"],
    "cardiff win": ["19", "0", "2"],
    "draw": ["16", "27", "0"],
    "swansea win": ["20", "2", "3"]
}
index = ["league", "fa cup", "league cup"]

df = pd.DataFrame(data, index=index)

# Convert DataFrame to the specified format
table_format = df_to_table_format(df, "south wales derby")

# Print the output in the desired format
print(json.dumps(table_format, indent=2))